### ISSUE TITLE
Award notice PUT results in internal server error but POST has no error

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#10]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
POST for award notice works but PUT does not

**To Reproduce**
PUT/POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_4648?parentId=2019-019725&projectId=26529 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foo
- sample request payload

**Expected behavior**
If POST does work, one would think that PUT does not fail with internal server error

**API response**
POST response:
Response status

200 OK
Response latency
1115 ms
Response content

Pragma: no-cache
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Fri, 31 Jan 2020 12:44:16 GMT
Content-Length: 181592
Content-Type: application/xml

<FORM_SECTION xmlns="http://publications.europa.eu/resource/schema/ted/R2.0.9/reception">
  <F03_2014 LG="FI" CATEGORY="ORIGINAL" FORM="F03">
...

PUT response:
InternalServerError
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Fri, 31 Jan 2020 11:49:53 GMT  

**Additional context**

**Comment by tuomastolvanen** [comment]
We have identifed the issu to be related to the notice size. The fix is currently in testing and will be published later today

**Comment by jannef** [comment]
Azure Dev Ops is currently experiencing issues, which is affecting our deployments. We are working on working around the current issues to get the deployments rolling again. Be prepared for possible delay.

**Comment by cloudia-jt** [comment]
Deployment still pending?

**Comment by tuomastolvanen** [comment]
The fix is published to production
