### ISSUE TITLE
Hilma rejects notice because invalid unicode control character \u0009, but we didn't find it from notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#100]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
etsidentifier: production_49103

We have about 5 notices about same error message

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
BadRequest Invalid unicode control character \u0009 in element: {http://publications.europa.eu/resource/schema/ted/R2.0.9/reception}P. Not allowed in XML 1.0. RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_49103
17.3.2021 8:12:28 ERROR TarjPyyn id 336687 julkaisu epäonnistui. BadRequest response headers: Pragma: no-cache Transfer-Encoding: chunked Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5 Strict-Transport-Security: max-age=2592000 X-Azure-Ref: 0y51RYAAAAADxCAnQ1RVqSZhoBsZSwBsfQlJVMzBFREdFMDQwOAAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc= Cache-Control: no-store, no-cache Date: Wed, 17 Mar 2021 06:12:27 GMT
**Additional context**

**Comment by jannef** [comment]
Please request the sample payload. If you are unwilling to share it here, send it to my email at janne.forsell@innofactor.com.

**Comment by jannef** [comment]
The offending character \u0009 is 'character tabulation'. In the UTF-8 request body this character would show up as \t. Control characters such as tabulator should be stripped from the request content prior to sending.

In .net, you could use something like this after forming the request body:
https://stackoverflow.com/questions/15259275/removing-hidden-characters-from-within-strings

**Comment by tuomastolvanen** [comment]
We will update the verification to allow the control characters that are valid in XML: U+0009 (TAB), U+000A (LF), U+000D (CR)

**Comment by tuomastolvanen** [comment]
The fix is testable now in the staging environment

**Comment by tuomastolvanen** [comment]
This fix has now been deployed.
