### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by jaandk** [Hankintailmoitukset/hilma-api#102]
**Describe the bug**
We get a 500 internal server error when trying to validate 

**To Reproduce**
POST https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/114406404?projectId=0
see attachment for body

**Expected behavior**
A valida responce or error description

[HilmaSchemaerrorV2.txt](https://github.com/Hankintailmoitukset/hilma-api/files/6220598/HilmaSchemaerrorV2.txt)

**Comment by jannef** [comment]
There is ongoing issue requiring our attention. We will get back to you as soon as possible.

**Comment by jannef** [comment]
EtsContract.Organisation.Information.NutsCodes: [ null ] is causing this issue. Please supply [] instead.

I've created task to our backlog improve error handling, but this will be worked on with lower priority.

**Comment by jannef** [comment]
A recent change introduced a null safety issue. The issue will be handled by filtering out garbage values as shown below.
```csharp
.NutsCodes?.Where(x => !string.IsNullOrEmpty(x)).Select(...)
```

The fix is now being deployed to staging/koulutus -environment, and validation on the supplied example should no longer crash.

**Comment by jaandk** [comment]
Thanks for the response, I'll have a look at it 👍

**Comment by jannef** [comment]
This fix has now also been deployed to production environment.
