### ISSUE TITLE
TED gives error (award notices): ESENDER_LOGIN element in wrong place

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#104]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
example notices

https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_57307?parentId=production_31168&projectId=45175
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_57278?parentId=production_49223&projectId=49489	
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_57259?parentId=production_29004&projectId=41964

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
BadRequest The notice cannot be published to TED: The element 'PROCUREMENT_DISCONTINUED' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'ESENDER_LOGIN' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'ORIGINAL_ENOTICES, ORIGINAL_TED_ESENDER, ORIGINAL_OTHER_MEANS' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , The element 'PROCUREMENT_DISCONTINUED' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'ESENDER_LOGIN' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'ORIGINAL_ENOTICES, ORIGINAL_TED_ESENDER, ORIGINAL_OTHER_MEANS' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , The element 'PROCUREMENT_DISCONTINUED' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'ESENDER_LOGIN' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'ORIGINAL_ENOTICES, ORIGINAL_TED_ESENDER, ORIGINAL_OTHER_MEANS' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , The element 'PROCUREMENT_DISCONTINUED' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'ESENDER_LOGIN' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'ORIGINAL_ENOTICES, ORIGINAL_TED_ESENDER, ORIGINAL_OTHER_MEANS' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , The element 'PROCUREMENT_DISCONTINUED' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'ESENDER_LOGIN' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'ORIGINAL_ENOTICES, ORIGINAL_TED_ESENDER, ORIGINAL_OTHER_MEANS' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , The element 'PROCUREMENT_DISCONTINUED' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'ESENDER_LOGIN' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'ORIGINAL_ENOTICES, ORIGINAL_TED_ESENDER, ORIGINAL_OTHER_MEANS' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , TED message formed: 

**Additional context**

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
Our ETS mapper was missing mapping for NoAwardedContract

**Comment by tuomastolvanen** [comment]
The fix will be deployed today

**Comment by tuomastolvanen** [comment]
Deployed to production
