### ISSUE TITLE
National notice not found from UI

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#105]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
this notice not found from UI and Search, but direct link works

https://www.hankintailmoitukset.fi/fi/public/procurement/51745/notice/70765/overview

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
Added to search index.
Will investigate why this wasn't added to the index automatically.

**Comment by AlexEngblom** [comment]
Didn't find the root cause behind this behavior. We made improvements for the error handling in case we could catch this next time if it happens again.
