### ISSUE TITLE
Notice published 3.5 but it is still in state "SendingToTed" in hilma

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#106]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**

etsidentifier: production_56223

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by tuomastolvanen** [comment]
Ted publish for this notice had failed due to unexpected network error while publishing to TED eSentool. The notice is now sent to TED.

**Comment by anttiremes** [comment]
Same problem with notice: production_57163

**Comment by JuhaHonkaranta** [comment]
Same issue as the previous one, the notice is now sent to TED.
