### ISSUE TITLE
problems with notice F03

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#108]
**Describe the bug**
production_53478

Ted message
"message": "D_ACCORDANCE_ARTICLE empty: Annex D-1: Justification: mandatory."
    
Notice

"annexes": {
      "d1": { "justification": ["Aiotusta hankinnasta...}
}

I don't know what is missing or wrong in notice

**Comment by jannef** [comment]
I will take a look at this tomorrow. Please provide a full notice body to here or my email. I suspect there might be unexpected element before justification: in that case, XML validator might emit an error about missing mandatory element.

**Comment by jannef** [comment]
The notice in question (production_53578) is not a F15 notice. It is of notice type F03 (Type = 300). What are you exactly trying to do?

**Comment by jannef** [comment]
The issue seemed to be, that there was no structured justification selected. Justification in the error message seems to be referring to these structured justifications, not the justification -text field, which is a sibling of the D_ACCORDANCE_ARTICLE in the TED XML-schema.
