### ISSUE TITLE
Tenders waiting to be published

### ISSUE THREAD

**Issue by mercell-lihe** [Hankintailmoitukset/hilma-api#109]
2 tenders are waiting to be published: Id 74491 and 74904. Can you see why they have not been published yet? They have been waiting for more than 48 hours.

**Comment by jannef** [comment]
Investigating

**Comment by jannef** [comment]
Notice 74491 was not sent to TED despite the retry policy and our process failed to catch the alert on the message being dead-lettered. This notice is now recieved by TED and status should reflect this.

Will get back to you about notice 74904 shortly.

**Comment by jannef** [comment]
Both notices are in AwaitingTedPublish (=3) state now. The other one required no intervention on our part. Perhaps the incremental retry (~12h or so) resolved the issue?
