### ISSUE TITLE
Re-parenting is not allowed when not reparenting

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#11]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
"Re-parenting is not allowed" error given when trying to publish award notice even though original Ojs given.

**To Reproduce**
RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_1920?parentId=2019-005153&projectId=16036
- sample request payload
Check email.

**Expected behavior**
No parenting error

**API response**
BadRequest response headers:
Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Thu, 30 Jan 2020 06:10:07 GMT

Given parent appears to have changed. Please supply the original parent identifier or leave it blank. Re-parenting is not allowed. Please create a new notice if the parent is wrong.

**Additional context**
POST does not give any error

**Comment by jannef** [comment]
It appears that the notice you are trying to put is already in the database, with a different parent (null). Currently there is no functionality to change the parent after the fact.

For now, please follow the advice from the error message, and create a new notice with correct parent (post it with a new EtsIdentifier and start tracking that instead).

In future, the API might be changed to allow re-parenting, however no timeline for such change is planned. Deleting 'abandoned' notices via API is also not yet possible, but will be implemented in the future.

**Comment by jannef** [comment]
The error message in question will be changed to include the values of parentId (old and new). Also adding a note that changing a parent from null to a value is considered reparenting. This should help to clarify the issue.
