### ISSUE TITLE
TED rejects contract award notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#110]
**Describe the bug**
TED gives error NOTICE_NUMBER_OJ missing

Notice ets: etsidfixed_63380

**To Reproduce**
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_63380?parentId=etsidfixed_32277&projectId=41842

**Comment by anttiremes** [comment]
Same problem with notice: etsidfixed_63047

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
PreviousNoticeOjsNumber was not provided in the request. Please provide it.

**Comment by anttiremes** [comment]
In documentation: 

previousNoticeOjsNumber string
Comment: IV.2.1) Previous publication concerning this procedure
If this tender is related to a tender previously published in TED, the TED OJS number
of that previous TED must be given.
If tender is not related, leave as null. If the previous tender was described by a notice
published via new Hilma or Hilma Ets API, parenting the new notice to that notice
will take care of filling the previous notice OJS number automatically.


this doesn't work "parenting the new notice to that notice will take care of filling the previous notice OJS number automatically."

**Comment by arinurkkala** [comment]
We released Hilma v 2.4.0 into production yesterday - could you verify if this bug is still valid?

I tried reproducing the problem, but could not.

**Comment by anttiremes** [comment]
etsidfixed_63047 gives same error

**Comment by arinurkkala** [comment]
We have identified that when a notice is updated via ETS api, the previousNoticeOjsNumber is not handled as per the comment. It is done only in create. If you want to publish those notices, you have 2 options:
1. Provide the previousNoticeOjsNumber in the contract award update.
2. Create a new contract award with the same data.

We will add the previousNoticeOjsNumber to update action as well in the near future.

**Comment by arinurkkala** [comment]
Should be fixed now. Can you verify and close, if ok?
