### ISSUE TITLE
Hilma rejects notice and gives error

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#112]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

Notice ets: production_66901

**Describe the bug**
The notice cannot be published to TED: The element 'CPV' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception' has invalid child element 'CPV_ADDITIONAL' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception'. List of possible elements expected: 'CPV_MAIN' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception'. , The element 'CPV' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception' has incomplete content. List of possible elements expected: 'CPV_MAIN' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception'.

```json
"LotNumber": "1",
"MainCpvCode": {
  "Code": "18143000",
  "Name": "Suojavaatteet ja -varusteet",
  "VocCodes": []
},
"AdditionalCpvCodes": [
  {
    "Code": "33000000",
    "Name": "Lääketieteelliset laitteet, farmaseuttiset valmisteet ja henkilökohtaiseen hygieniaan liittyvät tuotteet",
    "VocCodes": []
  }
],
```
```json
"LotNumber": "2",
"MainCpvCode": {
  "Code": "18143000",
  "Name": "Suojavaatteet ja -varusteet",
  "VocCodes": []
},
```

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
No response 

**Additional context**

**Comment by jannef** [comment]
There was an error when mapping object descriptions for defence notices: MainCpvCode was truncated. There is a fix pending deployment.

**Comment by jannef** [comment]
The fix will be deployed today afternoon.

**Comment by jannef** [comment]
Fix was deployed yesterday afternoon.
