### ISSUE TITLE
EU Dynamic procurement system publishing fails

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#113]
Hilma seems to send malformed request to TED
Procurement system in question: production_61520

BadRequest The notice cannot be published to TED: The element 'PROCEDURE' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'LANGUAGES' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'NOTICE_NUMBER_OJ, DATE_RECEIPT_TENDERS' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'.

**Comment by jannef** [comment]
The error message suggests NOTICE_NUMBER_OJ or DATE_RECEIPT_TENDERS is missing before LANGUAGES in PROCEDURE. In this case, the notice is missing TendersOrRequestsToParticipateDueDateTime.

Even if this is a procurement system, the TED XML spec does not allow this DATE_RECEIPT_TENDERS left empty. As shown in the following screen shot from the spec, it is unconditionally mantatory:

![image](https://user-images.githubusercontent.com/14314747/126112765-35540330-7701-479d-a0cf-0af064550482.png)
