### ISSUE TITLE
EU Contract (F02) Notice can not be published 

### ISSUE THREAD

**Issue by e-venalainen** [Hankintailmoitukset/hilma-api#116]
Notice: production_68669

Trying to publish EU-Contract notice (F02). Based on log, it seems that there could be something wrong with communication information. On the notice everything should be fine (URL addresses are provided etc.)

BadRequest The notice cannot be published to TED: The element 'CONTRACTING_BODY' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'CA_TYPE' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'URL_PARTICIPATION, ADDRESS_PARTICIPATION_IDEM, ADDRESS_PARTICIPATION' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'.

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
As the error states, CA_TYPE comes unexpected. The schema expects one of the elements as described.
The following fields should be set in communication information:
![image](https://user-images.githubusercontent.com/60182320/131958186-31b992ae-ebb4-4623-9abd-70cd6e0f4aa9.png)

**Comment by e-venalainen** [comment]
There was wrong SendTendersOption information. It seems that the notice is now visible in Hilma. I'll close this issue.
