### ISSUE TITLE
Corrigendum notice is rejected in TED

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#119]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
etsidentifier: etsidfixed_77110

Example
Hilma sends to ted:

 "section": "I.2",
      "label": "Y-tunnus",
      "oldText": ["FI27320952"],
      "newText": ["2732095-2"]

![kuva-20211021-060942](https://user-images.githubusercontent.com/60220798/140067920-371943f0-7583-4ac5-80e0-0995bae78a1a.png)

**Comment by anttiremes** [comment]
Almost same problem with notice:
production_77951

**Comment by JuhaHonkaranta** [comment]
investigating

**Comment by JuhaHonkaranta** [comment]
A fix for this has been deployed to production.

**Comment by anttiremes** [comment]
production_78991 same problem after fix deployment.

**Comment by JuhaHonkaranta** [comment]
I will look into this

**Comment by JuhaHonkaranta** [comment]
The previous fix didn't cover all cases. A new fix has been deployed to production. Try again and see if the issue still persists.
