### ISSUE TITLE
TED F17 divided into lots tenders may be submitted for one or more lots option missing from Hilma

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#12]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
TED F17 II.1.8) Lots contains option "one or more lots" option which is not available in Hilma. Not in web interface nor in api.

[TED F17](https://simap.ted.europa.eu/documents/10184/49059/sf_017_en.pdf)
Hilma options seem to cover only [TED F02](https://simap.ted.europa.eu/documents/10184/99173/EN_F02.pdf) options.

**Expected behavior**
Need new option or guide how to achieve desired selection with current options

**Comment by jannef** [comment]
Please use the option LotsSubmittedFor.LotsMax=4 for "one or more lots". LotsMaxAwardedQuantity has no effect on defense notices.

Hilma UI will be adjusted accordingly, and documentation will be updated to reflect this.

**Comment by cloudia-jt** [comment]
To clarify: So as a permanent solution there will not be new enum value to reflect this, but for defence "one or more lots" selection is done by LotsMax value as amount of lots?

**Comment by jannef** [comment]
This will be the final solution for the lifetime of the current defense notice family. This will be evaluated again if/when the e-notices replace the old defense notices.
