### ISSUE TITLE
Hilma response is 500 internal error

### ISSUE THREAD

**Issue by esaiko** [Hankintailmoitukset/hilma-api#121]
**Describe the bug**
Hilma response in production is 500 internal error when we POST a notice for verification.
Notice type 200.
Latest error at 2021-11-17 13:23:40

**To Reproduce**
POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/1156

**Expected behavior**
Hilma should response with 2xx or 4xx (with some explanation) but not with plain 5xx error code.

**API response**
500 Internal Server Error
Content-Length: 0
X-Cache: CONFIG_NOCACHE
X-Azure-Ref: 0POaUYQAAAADtkHb8jIqIQpdW5xUAr+tUQU1TMDRFREdFMTkxMgAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Wed, 17 Nov 2021 11:23:40 GMT
Connection: close

**Comment by jannef** [comment]
I've added the issue to the backlog on hotfix swimlane. We are currently working on a few higher priority issues.

**Comment by jannef** [comment]
As you are trying to validate a corrigendum (IsCorrigendum = true), please provide a parentId (from query parameter) so the API can generate a diff. This is required even in the validation action.

We will implement handling for this type of error.

**Comment by tieSari** [comment]
Error handling added and deployed to production.
