### ISSUE TITLE
EU notice stuck in hilmaStatus=WaitingToBePublished and tedStatus=SendingToTed

### ISSUE THREAD

**Issue by esaiko** [Hankintailmoitukset/hilma-api#122]
**Describe the bug**
EU notice 2021-086279 is stuck in hilmaStatus=WaitingToBePublished and tedStatus=SendingToTed.
The status has not changed since 15.11.2021 and the is no error or any other message.

**To Reproduce**
GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/1159

**Expected behavior**
We should receive an error message if there is a technical error, or TED should send a message if the manual verification fails.

**API response**
{"noticeNumber":"2021-086279","creationDate":"2021-11-15T10:24:10.4969894","modificationDate":"2021-11-15T10:24:10.7228927","hilmaStatus":4,"etsIdentifier":"1159","organisationId":"0825915-6","projectId":59202,"noticeId":86279,"tedStatus":1,"tedValidationReport":[]}

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
The message has been resent and notice is now awaiting publication from TED.
We will make a fix so this shouldn't happen again.
