### ISSUE TITLE
Awarded contractor disappeared

### ISSUE THREAD

**Issue by brianshdk** [Hankintailmoitukset/hilma-api#123]
Hi,
This is regarding this notice: https://www.hankintailmoitukset.fi/en/public/procurement/60502/notice/84913/overview

In the notice we have sent there where two awarded contractors ("FCG Finnish Consulting Group Oy" and "Ramboll Finland Oy"), but only one of them ("Ramboll Finland Oy") appears in the link above. Unfortunately we don't have the exact json that we sent, but we have a similar xml that is attached here.

Are you able to see what you have received and potentially why one of the contractors has disappeared?

Thanks,
Brian Hansen
Mercell
[84913.zip](https://github.com/Hankintailmoitukset/hilma-api/files/7633471/84913.zip)

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
It appears the first name contractor was not in the request.
Here is the request in full:
`{
  "Id": 0,
  "TotalValue": {
    "Type": 1,
    "Value": 220000.00,
    "MinValue": null,
    "MaxValue": null,
    "Currency": "EUR",
    "DisagreeToBePublished": false,
    "DoesNotExceedNationalThreshold": null
  },
  "LegalBasis": "32014L0024",
  "CommunicationInformation": {
    "ProcurementDocumentsAvailable": 0,
    "ProcurementDocumentsUrl": null,
    "AdditionalInformation": 0,
    "AdditionalInformationAddress": {
      "OfficialName": null,
      "NationalRegistrationNumber": null,
      "Department": null,
      "NutsCodes": [],
      "PostalAddress": null,
      "TelephoneNumber": null,
      "Email": null,
      "ContactPerson": null,
      "MainUrl": null,
      "ValidationState": 0
    },
    "OtherAddressForProcurementDocuments": {
      "OfficialName": null,
      "NationalRegistrationNumber": null,
      "Department": null,
      "NutsCodes": [],
      "PostalAddress": null,
      "TelephoneNumber": null,
      "Email": null,
      "ContactPerson": null,
      "MainUrl": null,
      "ValidationState": 0
    },
    "SendTendersOption": 0,
    "ElectronicAddressToSendTenders": null,
    "AddressToSendTenders": {
      "OfficialName": null,
      "NationalRegistrationNumber": null,
      "Department": null,
      "NutsCodes": [],
      "PostalAddress": null,
      "TelephoneNumber": null,
      "Email": null,
      "ContactPerson": null,
      "MainUrl": null,
      "ValidationState": 0
    },
    "ElectronicCommunicationRequiresSpecialTools": false,
    "ElectronicCommunicationInfoUrl": null,
    "DocumentsEntirelyInHilma": false,
    "SpecsAndAdditionalDocuments": 0,
    "SpecsAndAdditionalDocumentsAddress": null,
    "ElectronicAccess": null,
    "ValidationState": 2
  },
  "ComplementaryInformation": {
    "IsRecurringProcurement": false,
    "EstimatedTimingForFurtherNoticePublish": [],
    "ElectronicOrderingUsed": false,
    "ElectronicInvoicingUsed": false,
    "ElectronicPaymentUsed": false,
    "AdditionalInformation": [],
    "Defence": null,
    "ValidationState": 2
  },
  "ConditionsInformation": {
    "ProfessionalSuitabilityRequirements": null,
    "EconomicCriteriaToParticipate": false,
    "EconomicCriteriaDescription": null,
    "EconomicRequiredStandards": null,
    "TechnicalCriteriaToParticipate": false,
    "TechnicalCriteriaDescription": null,
    "TechnicalRequiredStandards": null,
    "RulesForParticipation": null,
    "RestrictedToShelteredWorkshop": false,
    "RestrictedToShelteredProgram": false,
    "ReservedOrganisationServiceMission": false,
    "DepositsRequired": null,
    "FinancingConditions": null,
    "LegalFormTaken": null,
    "QualificationSystemConditions": null,
    "CiriteriaForTheSelectionOfParticipants": null,
    "ExecutionOfServiceIsReservedForProfession": false,
    "ReferenceToRelevantLawRegulationOrProvision": null,
    "ParticipationIsReservedForProfession": false,
    "IndicateProfession": null,
    "ContractPerformanceConditions": null,
    "ObligationToIndicateNamesAndProfessionalQualifications": false,
    "ValidationState": 0
  },
  "ConditionsInformationDefence": {
    "DepositsRequired": null,
    "FinancingConditions": null,
    "LegalFormTaken": null,
    "OtherParticularConditions": null,
    "SecurityClearanceDate": null,
    "PersonalSituationOfEconomicOperators": null,
    "PersonalSituationOfSubcontractors": null,
    "EconomicCriteriaOfEconomicOperators": null,
    "EconomicCriteriaOfEconomicOperatorsMinimum": null,
    "EconomicCriteriaOfSubcontractors": null,
    "EconomicCriteriaOfSubcontractorsMinimum": null,
    "TechnicalCriteriaOfEconomicOperators": null,
    "TechnicalCriteriaOfEconomicOperatorsMinimum": null,
    "TechnicalCriteriaOfSubcontractors": null,
    "TechnicalCriteriaOfSubcontractorsMinimum": null,
    "RestrictedToShelteredWorkshops": false,
    "RestrictedToShelteredProgrammes": false,
    "RestrictedToParticularProfession": false,
    "RestrictedToParticularProfessionLaw": null,
    "StaffResponsibleForExecution": false,
    "ValidationState": 0
  },
  "ConditionsInformationNational": {
    "ParticipantSuitabilityCriteria": null,
    "RequiredCertifications": null,
    "AdditionalInformation": null,
    "ValidationState": 0,
    "ReservedForShelteredWorkshopOrProgram": false
  },
  "ContactPerson": {
    "Name": "Arttu Salonen",
    "Email": "arttu.salonen@loimaa.fi",
    "Phone": "+358 27614243"
  },
  "EstimatedValue": {
    "Type": 0,
    "Value": null,
    "MinValue": null,
    "MaxValue": null,
    "Currency": null,
    "DisagreeToBePublished": null,
    "DoesNotExceedNationalThreshold": null
  },
  "EstimatedValueCalculationMethod": [],
  "Links": [],
  "LotsInfo": {
    "DivisionLots": false,
    "QuantityOfLots": null,
    "LotsSubmittedFor": 0,
    "LotsSubmittedForQuantity": 0,
    "LotsMaxAwarded": false,
    "LotsMaxAwardedQuantity": 0,
    "LotCombinationPossible": false,
    "LotCombinationPossibleDescription": null,
    "ValidationState": 2
  },
  "MainCpvCode": {
    "Code": "71400000",
    "Name": "Yhdyskunta- ja maisemansuunnittelupalvelut",
    "VocCodes": []
  },
  "ObjectDescriptions": [
    {
      "Title": null,
      "LotNumber": "1",
      "MainCpvCode": {
        "Code": null,
        "Name": null,
        "VocCodes": null
      },
      "QuantityOrScope": null,
      "AdditionalCpvCodes": [
        {
          "Code": "71240000",
          "Name": "Arkkitehti-, insinööri- ja suunnittelupalvelut",
          "VocCodes": []
        },
        {
          "Code": "71410000",
          "Name": "Yhdyskuntasuunnittelupalvelut",
          "VocCodes": []
        }
      ],
      "Vehicles": null,
      "NutsCodes": [
        "FI1C1"
      ],
      "MainsiteplaceWorksDelivery": [
        "Loimaa"
      ],
      "DescrProcurement": [
        "Esitetyistä kysymyksistä ja niihin annetuista vastauksista laaditaan yhteenveto, joka julkaistaan viimeistään 18.6.2021 hankintajärjestelmässä tarjouspyyntöasiakirjojen mukaisesti.",
        "Tarjoajan huomiota kiinnitetään siihen, että tarjoajalla on velvollisuus tutustua huolellisesti lisäkysymysvastauksiin ennen tarjouksen jättämistä. Puhelintiedusteluja ei voida ottaa vastaan."
      ],
      "DisagreeAwardCriteriaToBePublished": false,
      "AwardCriteria": {
        "CriterionTypes": 5,
        "QualityCriteria": [
          {
            "Criterion": "Laatu",
            "Weighting": "60 %"
          }
        ],
        "CostCriteria": [],
        "PriceCriterion": {
          "Criterion": null,
          "Weighting": "Hinta 40 %"
        },
        "Criterion": [],
        "CriteriaStatedInProcurementDocuments": false
      },
      "EstimatedValue": {
        "Type": 0,
        "Value": null,
        "MinValue": null,
        "MaxValue": null,
        "Currency": null,
        "DisagreeToBePublished": null,
        "DoesNotExceedNationalThreshold": null
      },
      "TimeFrame": {
        "Type": 0,
        "Days": 0,
        "Months": 0,
        "Years": null,
        "BeginDate": null,
        "EndDate": null,
        "CanBeRenewed": false,
        "RenewalDescription": [],
        "ScheduledStartDateOfAwardProcedures": null
      },
      "CandidateNumberRestrictions": {
        "EnvisagedNumber": 0,
        "EnvisagedMinimumNumber": 0,
        "EnvisagedMaximumNumber": 0,
        "ObjectiveCriteriaForChoosing": [],
        "Selected": 0
      },
      "OptionsAndVariants": {
        "VariantsWillBeAccepted": false,
        "PartialOffersWillBeAccepted": false,
        "Options": false,
        "OptionsDescription": null,
        "OptionType": 0,
        "OptionsDays": null,
        "OptionsMonths": null
      },
      "TendersMustBePresentedAsElectronicCatalogs": false,
      "EuFunds": {
        "ProcurementRelatedToEuProgram": false,
        "ProjectIdentification": []
      },
      "AdditionalInformation": [],
      "AwardContract": {
        "ContractAwarded": 1,
        "NoAwardedContract": {
          "FailureReason": 0,
          "OriginalNoticeSentVia": 0,
          "OriginalEsender": {
            "Login": null,
            "CustomerLogin": null,
            "TedNoDocExt": null
          },
          "OriginalNoticeSentViaOther": null,
          "OriginalNoticeSentDate": null
        },
        "AwardedContract": {
          "ConclusionDate": "2021-10-06T00:00:00",
          "ContractNumber": null,
          "ContractTitle": "Loimaan kaupungin maankäytön suunnittelupalvelut puitejärjestelynä",
          "NumberOfTenders": {
            "DisagreeTenderInformationToBePublished": false,
            "Total": 5,
            "Sme": 0,
            "OtherEu": 0,
            "NonEu": 0,
            "Electronic": 5
          },
          "DisagreeContractorInformationToBePublished": false,
          "Contractors": [
            {
              "OfficialName": "Ramboll Finland Oy",
              "NationalRegistrationNumber": "0101197-5",
              "NutsCodes": [
                "FI197"
              ],
              "PostalAddress": {
                "StreetAddress": "Kansikatu 5B",
                "PostalCode": "33100",
                "Town": "Tampere",
                "Country": "FI"
              },
              "TelephoneNumber": null,
              "Email": "info@ramboll.fi",
              "MainUrl": null,
              "IsSmallMediumEnterprise": false,
              "ValidationState": 2
            }
          ],
          "InitialEstimatedValueOfContract": {
            "Value": 190000.00,
            "Currency": "EUR"
          },
          "FinalTotalValue": {
            "Type": 1,
            "Value": 190000.00,
            "MinValue": null,
            "MaxValue": null,
            "Currency": "EUR",
            "DisagreeToBePublished": false,
            "DoesNotExceedNationalThreshold": null
          },
          "LikelyToBeSubcontracted": false,
          "ValueOfSubcontract": {
            "Value": null,
            "Currency": null
          },
          "ProportionOfValue": 0.0,
          "SubcontractingDescription": [],
          "ExAnteSubcontracting": null,
          "PricePaidForBargainPurchases": {
            "Value": null,
            "Currency": null
          },
          "NotPublicFields": {
            "CommunityOrigin": false,
            "NonCommunityOrigin": false,
            "Countries": [
              null
            ],
            "AwardedToTendererWithVariant": false,
            "AbnormallyLowTendersExcluded": false
          },
          "ConcessionRevenue": {
            "Value": null,
            "Currency": null
          },
          "PricesAndPayments": null,
          "ConcessionValueAdditionalInformation": null
        },
        "AwardedContracts": []
      },
      "QualificationSystemDuration": null,
      "ValidationState": 2
    }
  ],
  "Organisation": {
    "DepartmentIdentifier": null,
    "Information": {
      "OfficialName": "Loimaan kaupunki",
      "NationalRegistrationNumber": "1927453-8",
      "Department": null,
      "NutsCodes": [
        "FI"
      ],
      "PostalAddress": {
        "StreetAddress": "Ylistaronkatu 36",
        "PostalCode": "32201",
        "Town": "Loimaa",
        "Country": "FI"
      },
      "TelephoneNumber": "+358 27614243",
      "Email": "arttu.salonen@loimaa.fi",
      "ContactPerson": "Arttu Salonen",
      "MainUrl": "https://permalink.mercell.com/157643625.aspx",
      "ValidationState": 2
    },
    "ContractingAuthorityType": 4,
    "ContractingType": 1,
    "MainActivity": 1,
    "MainActivityUtilities": 0,
    "OtherContractingAuthorityType": null,
    "OtherMainActivity": null
  },
  "NoticeOjsNumber": null,
  "PreviousNoticeOjsNumber": "2021/S 108-284958",
  "Project": {
    "Id": 0,
    "ContractType": 2,
    "ReferenceNumber": null,
    "Title": "Loimaan kaupungin maankäytön suunnittelupalvelut puitejärjestelynä",
    "ProcurementCategory": 1,
    "JointProcurement": false,
    "ProcurementLaw": [],
    "CentralPurchasing": false,
    "CoPurchasers": [],
    "DefenceWorks": 0,
    "DefenceSupplies": 0,
    "DefenceCategory": null,
    "DisagreeToPublishNoticeBasedOnDefenceServiceCategory4": null,
    "AgricultureWorks": 0
  },
  "ShortDescription": [
    "Hankinnan kohteena ovat Loimaan kaupungin tarvitsemat maankäytön suunnittelupalvelut puitejärjestelynä tarjouspyyntöasiakirjojen mukaisesti. Palveluntuottajan vastuulle kuuluvat tehtävät määritellään tarkemmin sopimuskauden aikana jokaisen tehtävän tilauksen osalta erikseen.",
    "Sopimus puitejärjestelystä tehdään kahden palveluntuottajan kanssa.",
    "Sopimus ei tuota valituille palveluntuottajille yksinoikeutta hankinnan toteuttamiseen."
  ],
  "Type": 300,
  "TenderingInformation": {
    "TendersOrRequestsToParticipateDueDateTime": null,
    "EstimatedDateOfInvitations": null,
    "Languages": [],
    "TendersMustBeValidOption": 0,
    "TendersMustBeValidUntil": null,
    "TendersMustBeValidForMonths": 0,
    "EstimatedDateOfContractNoticePublication": null,
    "TenderOpeningConditions": {
      "OpeningDateAndTime": null,
      "Place": [],
      "InformationAboutAuthorisedPersons": []
    },
    "Defence": {
      "PreviousPublicationExists": false,
      "PreviousPriorInformationNoticeOjsNumber": null,
      "HasPreviousContractNoticeOjsNumber": false,
      "PreviousContractNoticeOjsNumber": null,
      "HasPreviousExAnteOjsNumber": false,
      "PreviousExAnteOjsNumber": null,
      "TimeLimitForReceipt": null,
      "PayableDocuments": false,
      "DocumentPrice": null,
      "PaymentTermsAndMethods": null,
      "LanguageType": 0,
      "Languages": [],
      "OtherLanguage": false,
      "OtherLanguages": null
    },
    "EstimatedExecutionTimeFrame": {
      "Type": 3,
      "Days": null,
      "Months": null,
      "Years": null,
      "BeginDate": null,
      "EndDate": null,
      "CanBeRenewed": false,
      "RenewalDescription": null,
      "ScheduledStartDateOfAwardProcedures": null
    },
    "ScheduledStartDateOfAwardProcedures": null,
    "ValidationState": 2
  },
  "RewardsAndJury": {
    "PrizeAwarded": false,
    "NumberAndValueOfPrizes": null,
    "DetailsOfPayments": null,
    "ServiceContractAwardedToWinner": false,
    "DecisionOfTheJuryIsBinding": false,
    "NamesOfSelectedMembersOfJury": null,
    "ValidationState": 0
  },
  "ResultsOfContest": {
    "ContestWasTerminated": false,
    "NoPrizeType": 0,
    "OriginalNoticeSentVia": 0,
    "OriginalEsender": null,
    "OriginalNoticeSentViaOther": null,
    "OriginalNoticeSentDate": null,
    "DateOfJuryDecision": null,
    "ParticipantsContemplated": 0,
    "ParticipantsSme": 0,
    "ParticipantsForeign": 0,
    "DisagreeParticipantCountPublish": false,
    "Winners": null,
    "DisagreeWinnersPublish": false,
    "ValueOfPrize": null,
    "DisagreeValuePublish": false,
    "ValidationState": 0
  },
  "Language": "FI",
  "ProcedureInformation": {
    "ProcedureType": 1,
    "AcceleratedProcedure": false,
    "JustificationForAcceleratedProcedure": [],
    "ContestType": 0,
    "ContestParticipants": null,
    "FrameworkAgreement": {
      "IncludesFrameworkAgreement": false,
      "IncludesConclusionOfFrameworkAgreement": false,
      "FrameworkAgreementType": 0,
      "EnvisagedNumberOfParticipants": null,
      "FrameworkEnvisagedType": 0,
      "IncludesDynamicPurchasingSystem": false,
      "DynamicPurchasingSystemInvolvesAdditionalPurchasers": false,
      "JustificationForDurationOverFourYears": [],
      "JustificationForDurationOverSevenYears": null,
      "JustificationForDurationOverEightYears": null,
      "DynamicPurchasingSystemWasTerminated": false,
      "EstimatedTotalValue": {
        "Type": 0,
        "Value": null,
        "MinValue": null,
        "MaxValue": null,
        "Currency": null,
        "DisagreeToBePublished": null,
        "DoesNotExceedNationalThreshold": null
      },
      "Duration": {
        "Type": 0,
        "Days": null,
        "Months": null,
        "Years": null,
        "BeginDate": null,
        "EndDate": null,
        "CanBeRenewed": false,
        "RenewalDescription": null,
        "ScheduledStartDateOfAwardProcedures": null
      },
      "FrequencyAndValue": null
    },
    "ReductionRecourseToReduceNumberOfSolutions": false,
    "ReserveRightToAwardWithoutNegotiations": false,
    "ElectronicAuctionWillBeUsed": false,
    "AdditionalInformationAboutElectronicAuction": null,
    "NamesOfParticipantsAlreadySelected": null,
    "ProcurementGovernedByGPA": false,
    "CriteriaForEvaluationOfProjects": null,
    "DisagreeCriteriaForEvaluationOfProjectsPublish": false,
    "UrlNationalProcedure": null,
    "MainFeaturesAward": [],
    "Defence": null,
    "National": null,
    "ValidationState": 2
  },
  "ProceduresForReview": {
    "ReviewBody": {
      "OfficialName": "Markkinaoikeus",
      "NationalRegistrationNumber": null,
      "Department": null,
      "NutsCodes": [],
      "PostalAddress": {
        "StreetAddress": "Radanrakentajantie 5",
        "PostalCode": "00520",
        "Town": "Helsinki",
        "Country": "FI"
      },
      "TelephoneNumber": "+358 295643314",
      "Email": "markkinaoikeus@oikeus.fi",
      "ContactPerson": null,
      "MainUrl": "http://www.oikeus.fi/markkinaoikeus",
      "ValidationState": 0
    },
    "ReviewProcedure": [],
    "ValidationState": 2
  },
  "Modifications": {
    "MainCpvCode": null,
    "AdditionalCpvCodes": [],
    "NutsCodes": [],
    "MainsiteplaceWorksDelivery": null,
    "DescrProcurement": null,
    "TimeFrame": {
      "Type": 0,
      "Days": null,
      "Months": null,
      "Years": null,
      "BeginDate": null,
      "EndDate": null,
      "CanBeRenewed": false,
      "RenewalDescription": null,
      "ScheduledStartDateOfAwardProcedures": null
    },
    "JustificationForDurationOverFourYears": null,
    "JustificationForDurationOverEightYears": null,
    "TotalValue": {
      "Value": null,
      "Currency": null
    },
    "AwardedToGroupOfEconomicOperators": false,
    "Contractors": [],
    "Description": null,
    "Reason": 0,
    "ReasonDescriptionEconomic": null,
    "ReasonDescriptionCircumstances": null,
    "IncreaseBeforeModifications": {
      "Value": null,
      "Currency": null
    },
    "IncreaseAfterModifications": {
      "Value": null,
      "Currency": null
    },
    "ValidationState": 0
  },
  "Defence": {
    "MainsiteplaceWorksDelivery": null,
    "NutsCodes": [],
    "FrameworkAgreement": {
      "IncludesFrameworkAgreement": false,
      "IncludesConclusionOfFrameworkAgreement": false,
      "FrameworkAgreementType": 0,
      "EnvisagedNumberOfParticipants": null,
      "FrameworkEnvisagedType": 0,
      "IncludesDynamicPurchasingSystem": false,
      "DynamicPurchasingSystemInvolvesAdditionalPurchasers": false,
      "JustificationForDurationOverFourYears": null,
      "JustificationForDurationOverSevenYears": null,
      "JustificationForDurationOverEightYears": null,
      "DynamicPurchasingSystemWasTerminated": false,
      "EstimatedTotalValue": {
        "Type": 0,
        "Value": null,
        "MinValue": null,
        "MaxValue": null,
        "Currency": null,
        "DisagreeToBePublished": null,
        "DoesNotExceedNationalThreshold": null
      },
      "Duration": {
        "Type": 0,
        "Days": null,
        "Months": null,
        "Years": null,
        "BeginDate": null,
        "EndDate": null,
        "CanBeRenewed": false,
        "RenewalDescription": null,
        "ScheduledStartDateOfAwardProcedures": null
      },
      "FrequencyAndValue": null
    },
    "AdditionalCpvCodes": null,
    "Subcontract": {
      "TendererHasToIndicateShare": false,
      "TendererHasToIndicateChange": false,
      "CaMayOblige": false,
      "SuccessfulTenderer": false,
      "SuccessfulTendererMin": null,
      "SuccessfulTendererMax": null,
      "SuccessfulTendererToSpecify": false
    },
    "OptionsAndVariants": {
      "VariantsWillBeAccepted": false,
      "PartialOffersWillBeAccepted": false,
      "Options": false,
      "OptionsDescription": null,
      "OptionType": 0,
      "OptionsDays": null,
      "OptionsMonths": null
    },
    "TotalQuantityOrScope": {
      "Type": 0,
      "Value": null,
      "MinValue": null,
      "MaxValue": null,
      "Currency": null,
      "DisagreeToBePublished": null,
      "DoesNotExceedNationalThreshold": null
    },
    "TotalQuantity": null,
    "Renewals": {
      "CanBeRenewed": false,
      "Amount": null,
      "SubsequentContract": null
    },
    "TimeFrame": {
      "Type": 0,
      "Days": null,
      "Months": null,
      "Years": null,
      "BeginDate": null,
      "EndDate": null,
      "CanBeRenewed": false,
      "RenewalDescription": null,
      "ScheduledStartDateOfAwardProcedures": null
    },
    "AdditionalInformation": null
  },
  "IsCorrigendum": false,
  "IsCancelled": false,
  "CancelledReason": null,
  "Changes": [],
  "CorrigendumAdditionalInformation": [],
  "ContractAwardsDefence": [
    {
      "LotNumber": null,
      "LotTitle": null,
      "ContractNumber": null,
      "ContractAwardDecisionDate": null,
      "NumberOfTenders": {
        "DisagreeTenderInformationToBePublished": false,
        "Total": 0,
        "Sme": null,
        "OtherEu": null,
        "NonEu": null,
        "Electronic": null
      },
      "Contractor": {
        "OfficialName": null,
        "NationalRegistrationNumber": null,
        "NutsCodes": [],
        "PostalAddress": {
          "StreetAddress": null,
          "PostalCode": null,
          "Town": null,
          "Country": null
        },
        "TelephoneNumber": null,
        "Email": null,
        "MainUrl": null,
        "IsSmallMediumEnterprise": false,
        "ValidationState": 0
      },
      "EstimatedValue": {
        "Value": null,
        "Currency": null
      },
      "ContractValueType": 0,
      "FinalTotalValue": {
        "Value": null,
        "Currency": null
      },
      "LowestOffer": {
        "Value": null,
        "Currency": null
      },
      "HighestOffer": {
        "Value": null,
        "Currency": null
      },
      "AnnualOrMonthlyValue": {
        "Type": 0,
        "Days": null,
        "Months": null,
        "Years": null,
        "BeginDate": null,
        "EndDate": null,
        "CanBeRenewed": false,
        "RenewalDescription": null,
        "ScheduledStartDateOfAwardProcedures": null
      },
      "LikelyToBeSubcontracted": false,
      "ValueOfSubcontract": {
        "Value": null,
        "Currency": null
      },
      "ProportionOfValue": null,
      "ValueOfSubcontractNotKnown": false,
      "SubcontractingDescription": null,
      "AllOrCertainSubcontractsWillBeAwarded": false,
      "ShareOfContractWillBeSubcontracted": false,
      "ShareOfContractWillBeSubcontractedMinPercentage": null,
      "ShareOfContractWillBeSubcontractedMaxPercentage": null,
      "ValidationState": 0
    }
  ],
  "Annexes": {
    "D1": {
      "NoTenders": false,
      "ProcedureType": 0,
      "SuppliesManufacturedForResearch": false,
      "ProvidedByOnlyParticularOperator": false,
      "ReasonForNoCompetition": 0,
      "ExtremeUrgency": false,
      "AdditionalDeliveries": false,
      "RepetitionExisting": false,
      "DesignContestAward": false,
      "CommodityMarket": false,
      "AdvantageousTerms": false,
      "AdvantageousPurchaseReason": 0,
      "Justification": null
    },
    "D2": null,
    "D3": null,
    "D4": null,
    "DirectNational": null
  },
  "IsPrivateSmallValueProcurement": false,
  "HilmaStatistics": {
    "EnergyEfficiencyConsidered": false,
    "InnovationConsidered": false,
    "SMEParticipationConsidered": false,
    "ValidationState": 0
  }
}`

**Comment by brianshdk** [comment]
Thanks, we will investigate further here then!

**Comment by arinurkkala** [comment]
Best of luck!

**Comment by brianshdk** [comment]
Thanks, I can see the error is in our code somewhere :-)

**Comment by brianshdk** [comment]
I need to reopen this one.

I just tried the following piece of C# code with the attached xml file.

```
      NoticeXMLParser parser = new NoticeXMLParser();

      NoticeImportContract importModel = new NoticeImportContract()
      {
        FormNumber = 3,
        NoticeNumber = string.Empty, // Assigned by Hilma
        NoticeOjsNumber = null,
        NoticeType = null,
        HilmaSubmissionDate = DateTime.Now,
        Notice = xmlDoc.OuterXml,
      };

      NoticeContract notice = parser.ParseNotice(importModel);

```
as you can see the xml file contains 2 contractors but after parser has completed one of them is removed. So it looks like there is an error in the parser, that as far as I know is developed by you.

**Comment by brianshdk** [comment]
Sorry again, looks like the parser is our own :-(

The developer who usually handles this has left, so we are struggling with this currently.
