### ISSUE TITLE
Test-portal didn't show hilmastatistics

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#124]
Etsidentifier: devel_3051
https://hns-hilma-test-apim.portal.azure-api.net

From portal
"hilmaStatistics": {
      "validationState": 0
    }

sended: 
"HilmaStatistics": {
		"EnergyEfficiencyConsidered": false,
		"LowCarbon": false,
		"CircularEconomy": false,
		"Biodiversity": false,
		"SustainableFoodProduction": false,
		"ListedGreenCriteriaUsed": null,
		"JustWorkingConditions": true,
		"EmploymentCondition": false,
		"HowManyOpportunitiesIsEstimated": null,
		"CodeOfConduct": false,
		"InnovationConsidered": true,
		"SolutionNewToBuyer": false,
		"SolutionNewToMarketOrIndustry": true,
		"SmeParticipationConsidered": true

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
Iz fixed.
