### ISSUE TITLE
New statistics per 0102-2022

### ISSUE THREAD

**Issue by Elpaggio** [Hankintailmoitukset/hilma-api#125]
We (at Mercell) are ready to support the additional statistics fields per the 2'nd of January 2022.
In that regard we have a question:

1) Do we need to target the new endpoints stated in the README pr. the 2'nd of January?
Currently we target "https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/" in production and
"https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/" in staging.

2) What is the target endpoint for staging supporting the additional statistics?

**Comment by jannef** [comment]
There was wrong date in in the README. 2nd is on sunday, and we are not deploying anything on sunday. Instead, the deployment will take place 17.30 (Finnish time) on 3rd of january.

There is no changes to endpoints. Support for old type of statistics is no longer accepted after 3.1.2022.

Test environment supports the new statistics already. Staging reflects production.

**Comment by Elpaggio** [comment]
Thanks a lot for the quick reply @jannef.
We should be all set then :).
