### ISSUE TITLE
cannot publish f03 notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#126]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
BadRequest The notice cannot be published to TED: The element 'OBJECT_DESCR' in
 namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'AC' in
  namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. 
  List of possible elements expected: 'TITLE, LOT_NO, CPV_ADDITIONAL' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' 
  as well as 'NUTS' in namespace 'http://publications.europa.eu/resource/schema/ted/2021/nuts'. , 
  The element 'PROCUREMENT_DISCONTINUED' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'
   has invalid child element 'ESENDER_LOGIN' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'
   . List of possible elements expected: 'ORIGINAL_ENOTICES, ORIGINAL_TED_ESENDER, ORIGINAL_OTHER_MEANS' in n
   amespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'.

**To Reproduce**
etsidentifier: etsidfixed_84765

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by jannef** [comment]
There seems to be some issues in `ObjectDescriptions[0]`:

- Title is not required, and will be discarded, as this is not a lotted procurement. (not critical)
- $.ObjectDescriptions[0].NutsCodes is []. This in not allowed. A nuts code is required (critical)
- $.ObjectDescriptions[0].DescrProcurement is null. This is not allowed. A description is required (critical)
- $.ObjectDescriptions[0].AwardCriteria.CritearionTypes: 8 is not allowed value. Allowed values in this context are 2, 3, 4, 5
