### ISSUE TITLE
How to verify that you receive the new statistics?

### ISSUE THREAD

**Issue by mercell-lihe** [Hankintailmoitukset/hilma-api#127]
Hi :) I have tried to test the new additional statistic fields in our test environment at Mercell.
How can I verify that you receive the new statistics? I had a look at https://koulutus.hankintailmoitukset.fi/en/procurement/27516/procedure/33686 but there is no information on this here. 
![Hilma](https://user-images.githubusercontent.com/71319444/147934898-f7f0b471-b620-40f8-af14-e65a02ad6c0a.png)

**Comment by jannef** [comment]
Easiest way to verify would be to open your developer console (F12) and check the downloaded notice.

![image](https://user-images.githubusercontent.com/14314747/147950585-1daca3b6-9490-404b-a5ba-58009683ae41.png)

Please try sending the notice again now, new version should be up and running on koulutus-environment.
