### ISSUE TITLE
Hilma shows wrong information about national treshold

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#128]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
etsidentifier: production_82952

"EstimatedValue": {
"Type": 2,
"MinValue": 30000.0,
"MaxValue": 45000.0,
"Currency": "EUR",
"DisagreeToBePublished": false
},

https://www.hankintailmoitukset.fi/fi/public/procurement/63164/notice/89603/overview

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
Could you expand on the issue a bit more?
Hilma doesn't show any information about national thresholds in the public UI. The referenced link just shows a notice with given data. Currently Hilma does not validate national thresholds for notices at service level.

**Comment by anttiremes** [comment]
![kuva](https://user-images.githubusercontent.com/60220798/148532820-79f87001-e12e-49fa-a2b9-3eba17fe9fb4.png)

**Comment by anttiremes** [comment]
we didn't send boolean about treshold and it seem to be default true in Hilma

**Comment by arinurkkala** [comment]
![image](https://user-images.githubusercontent.com/60182320/148535109-c0178e7a-565f-4c4d-915b-ae5116e12677.png)
The law requires the boolean to be sent. The data hasn't defaulted to true, only the UI defaults null to true.. will investigate how this case should be handled with Hansel.

**Comment by arinurkkala** [comment]
Quoting the part from law to which this relates to:
102 §
Hankintailmoituksen sisältö
"4) hintahaarukka tai ennakoitu arvo ilman arvonlisäveroa taikka tieto siitä, onko hankinnan ennakoitu arvo vähintään 25 §:ssä tarkoitetun kansallisen kynnysarvon suuruinen;"

We will fix Hilma UI to hide the boolean flag when not required ASAP.

Petteri tested in your test environment by hiding the value and the boolean was still not sent:
https://koulutus.hankintailmoitukset.fi/fi/public/procurement/27524/notice/33696/overview

This case should be fixed, as it shows neither a value nor the boolean.
