### ISSUE TITLE
notice status is still sending to ted

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#129]
etsnotice: production_91411

"creationDate": "2022-02-23T13:30:59.168093",
  "modificationDate": "2022-02-24T12:30:12.529848",
  "hilmaStatus": 1,

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
Ted state is now NotPublished with reason code WL (Wrong Language).

**Comment by arinurkkala** [comment]
HilmaStatus: 1 = Draft.
