### ISSUE TITLE
Error publishing notice to ted

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#130]
production_72267

BadRequest The notice cannot be published to TED: The element 'PROCEDURE' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid 
child element 'LANGUAGES' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. 

<PROCEDURE>       
<PT_RESTRICTED />       
<MAIN_FEATURES_AWARD>         
<P>xxxx</P>       
</MAIN_FEATURES_AWARD>       
<LANGUAGES>         
<LANGUAGE VALUE="FI" />       
</LANGUAGES>     
</PROCEDURE>

**Comment by arinurkkala** [comment]
From request:
  "TenderingInformation": {
    "TendersOrRequestsToParticipateDueDateTime": null,
    
    TendersOrRequestsToParticipateDueDateTime is mandatory for F21.
