### ISSUE TITLE
avp-read-api didn't find notice 

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#131]
notice
https://www.hankintailmoitukset.fi/fi/public/procurement/51482/notice/82933/overview

etsidentifier: production_49664

search filter: 
{
"filter":"noticeOjsNumber eq '2021/S 194-505710'",
"top":"5",
"count":"true",
"searchMode":"any",
"orderby":"datePublished desc"
}

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
Was fixed in todays release update. Search now yields a result.
This notice had 201 lots and an Azure search limit was reached.
