### ISSUE TITLE
Ted rejects Corrigendum notice 

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#132]
etsidentified: production_105301
changed "sendTendersOption": 2 to "sendTendersOption": 1,

 "changes": [{
      "section": "I.3",
      "label": "Tiedot, tarjoukset tai osallistumishakemukset on tehtävä/jätettävä",
      "oldText": ["Ostajan osoitteesta"],
      "newText": ["Sähköisesti osoitteessa"]

![kuva](https://user-images.githubusercontent.com/60220798/171351654-b95c44c5-1721-46b7-aa62-ceb62dbfcee5.png)

**Comment by maijapyykonen** [comment]
Are you still investigating this issue, any updates?

**Comment by Juhisee** [comment]
hey, issue solved and I'm currently testing the implementation. Will try to get it in production soon
