### ISSUE TITLE
Cannot publish notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#133]
etsidentifier: production_107867

in json
"MainActivity": 1024,
"OtherMainActivity": "rakennuttaminen"

**Describe the bug**
BadRequest The notice cannot be published to TED: The element 'CONTRACTING_BODY' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'CA_ACTIVITY_OTHER' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'ADDRESS_PARTICIPATION_IDEM, ADDRESS_PARTICIPATION, URL_TOOL, CA_TYPE, CA_TYPE_OTHER, CE_ACTIVITY, CE_ACTIVITY_OTHER' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , TED message formed: <FORM_SECTION xmlns="http://publications.europa.eu/resource/schema/ted/R2.0.9/reception"> <F12_2014 LG="FI" CATEGORY="ORIGINAL" FORM="F12"> <LEGAL_BASIS VALUE="32014L0024" />

**Comment by tieSari** [comment]
otin työn alle

**Comment by tieSari** [comment]
@anttiremes Minä päivänä tämä on yritetty lähettää? Tänään 27.6.?

**Comment by tieSari** [comment]
Hei!
Testasin tuota. ContractingAuthorityTypen arvon puuttumisen takia skeeman validointi ei mene läpi.

**Comment by anttiremes** [comment]
![kuva](https://user-images.githubusercontent.com/60220798/176106773-60ff7215-d8b1-481a-ae72-7cd05bbda30b.png)

**Comment by anttiremes** [comment]
Nyt kyseessä on hankintayksikkö

**Comment by tieSari** [comment]
Hankintayksikön tapauksessa pitää asettaa projektin ProcurementCategory arvoksi 4 (Hilman puolella  enum ProcurementCategory.Utility) eli silloin ei ole pakollinen tuo 1.4. tieto.  Tällöin käytetään MainActivityUtilities-kenttää ei MainActivity.
