### ISSUE TITLE
Notice is published in ted, but not in hilma

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#134]
Etsidentifier: production_111139 and production_112663

Both is sended twice to TED

"type": "VALIDATION_RULES",
    "items": [{
      "name": "R013",
      "valid": false,
      "severity": "ERROR",
      "message": "Duplicate NO_DOC_EXT, a notice with the same identifier has already been received.",
      "details": "At least one notice with the same noDocExt '2022-108303' has already been submitted. 10 first existing notice(s) submission id is/are '20220913-006126'"

**Comment by Zamm** [comment]
This issue has been fixed. the possible reason related to the timeout handler.

**Comment by anttiremes** [comment]
same problem with notice: etsidfixed_115753
