### ISSUE TITLE
Ted rejects corriqendum notice because of changed text

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#135]
![kuva](https://user-images.githubusercontent.com/60220798/191681767-74f04c37-7a7f-423b-ba40-b6e10eedd17d.png)

etsidfixed_115694

**Comment by arinurkkala** [comment]
The parent notice has been fixed and resubmitting from Hilma will cause an issue with no-doc-ext. If you can resend the request, it will create a new notice and no-doc-ext will not be an issue. In short; resend the request.
