### ISSUE TITLE
Contract award notice is in published in ted state but not published in Hilma

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#137]
Notice ets: etsidfixed_115753

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
There were some production issues on 22.9 that may have caused this notice not being submitted to TED. I have now resubmitted the notice and it should proceed normally.

**Comment by arinurkkala** [comment]
Now published in TED as well.
