### ISSUE TITLE
Documentation does not work

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#14]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
https://www.hankintailmoitukset.fi/fi/documentation does not open.

**To Reproduce**
Get your favorite web browser and go to https://www.hankintailmoitukset.fi/fi/documentation

**Expected behavior**
Documentation opens

**Comment by arinurkkala** [comment]
Fixed.
There was a small problem that was quickly fixable.
