### ISSUE TITLE
How to get xsd schema for HILMA eForms?

### ISSUE THREAD

**Issue by jlouvrier** [Hankintailmoitukset/hilma-api#142]
Hi Ari,
Where can we download your xsd schemas?
Best,
Julien

**Comment by arinurkkala** [comment]
Hi,

They are the XSD:s from eForms SDK: https://github.com/OP-TED/eForms-SDK/tree/develop/schemas

Terveisin, Ari

From: Julien Louvrier ***@***.***>
Sent: perjantai 27. tammikuuta 2023 9.50
To: Hankintailmoitukset/hilma-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hankintailmoitukset/hilma-api] How to get xsd schema for HILMA eForms? (Issue #142)


Hi Ari,
Where can we download your xsd schemas?
Best,
Julien

-

**Comment by eduardsmirnov** [comment]
Hi Ari, follow-up question, are you adding some UBL extensions for HILMA-specific statistics fields?
Where could I find XPaths for all these fields?

**Comment by arinurkkala** [comment]
Hi,

The write API has not been implemented yet for Hilma statistics, but UBL extension is a good place to put them. Currently our web api sends the statistics completely separately from the eForm.

How important is it for you that the statistics are in UBL extension compared to a separate contract from the eForm?

Terveisin, Ari

**Comment by eduardsmirnov** [comment]
Hi Ari, 
after a long delay, it is not super important if new fields are part of a schema or something else.
What I am interested in is to 
* know the definitions of all fields (type, limits, XML path, mandatory or not)
* way how to validate data before sending to Hilma (XML schema, Schematron rules, we may even add some internal business logic if you would say the logic will not change over time)

What I can guess right now is that XML with extra fields would be not valid by TED schema, so probably we would need at least a new schema.

**Comment by arinurkkala** [comment]
Hi,

We haven't yet implemented the Hilma-specific fields into the write-api yet, so we haven't yet defined anything. But the changes should be coming soon (~1 month) and we will inform about the changes once it has been implemented. Currently we are working on Hilma UI and going through all notice types.
As for how the Hilma UI is structured, we have a procedure (fields: name, referencenumber and buyer) that contains notices, where eForm is the main part and Hilma statistics is the deviating part. The Hilma statistics will be implemented with the same restrictions as they are currently. Procedure name and buyer are mandatory.
Currently our eForms validation only executes XSD and schematron validation, but the plan is to include the Hilma statistics as well, once we implement them.
