### ISSUE TITLE
eForms Hilma specific validation rules

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#145]
Looking at https://github.com/Hankintailmoitukset/hilma-api/tree/master/validation

* Is it expected that every single custom validation would fully replace an appropriate field definition from TED SDK? Or only properties you defined in custom validation are replaced?
* Where could I find patterns for "ted_email", "nationalidentifierorvatnumber", "nationalorprivateroadidentifier" ?
* Per my understanding, "nationalidentifierorvatnumber" may affect companies being outside Finland, cause the rule is applied to any organization, including tenderers.

**Comment by eduardsmirnov** [comment]
More: 
* when you say "field path" is the path of the field in the notice, do you mean a path in XML or a path in your JSON model?
e.g. procurementProjectLot.procurementProject.plannedPeriod.durationMeasure
We are providing an XML to you and it makes additional difficulty to map JSON path to XML path.
* are you expecting some final (relatively small) number of custom validations that could be supported manually by developers or everything is expected to be fully dynamic and new custom validations would be released every month the same way as TED does?

**Comment by exttuosa** [comment]
- Field path is path in our json, which is generated from the Ted SDK schema. I'll add the absolute xpath to the fields as well.
- Yeah, we are expecting a relatively small number of custom validation. We do not expect them to change frequently at least not after go live.
