### ISSUE TITLE
Attempt to create a notice leads to error code 503

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#146]
**Attempt to call PUT https://hns-hilma-test-apim.azure-api.net/eforms/external-write/v1/eform/pin leads to error code 503**
I guess it does not dependent on file content, pass any xml, backend is crashing.
Same happens with API for CN and CAN

I tried with following XML

`<?xml version="1.0" encoding="utf-8"?>
<PriorInformationNotice xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:efac="http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1" xmlns:efext="http://data.europa.eu/p27/eforms-ubl-extensions/1" xmlns:efbc="http://data.europa.eu/p27/eforms-ubl-extension-basic-components/1" xmlns="urn:oasis:names:specification:ubl:schema:xsd:PriorInformationNotice-2">
  <ext:UBLExtensions>
    <ext:UBLExtension>
      <ext:ExtensionContent>
        <efext:EformsExtension>
          <efac:NoticeSubType>
            <cbc:SubTypeCode listName="notice-subtype">1</cbc:SubTypeCode>
          </efac:NoticeSubType>
		  <efbc:TransmissionDate>2023-02-24+00:00</efbc:TransmissionDate>
          <efbc:TransmissionTime>05:55:12+00:00</efbc:TransmissionTime>
          <efac:Organizations>
            <efac:Organization>
              <efac:Company>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="ENG">Buyer 1</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:CityName>Tallinn</cbc:CityName>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">EST</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">B1</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Telephone>112</cbc:Telephone>
                  <cbc:ElectronicMail>buyer@buyer.xx</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
            <efac:Organization>
              <efac:Company>
                <cbc:WebsiteURI>http://mercell.com/</cbc:WebsiteURI>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0002</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="ENG">Mercell Holding ASA</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:StreetName>Askekroken 11</cbc:StreetName>
                  <cbc:CityName>Oslo</cbc:CityName>
                  <cbc:PostalZone>0277</cbc:PostalZone>
                  <cbc:CountrySubentityCode listName="nuts">NO081</cbc:CountrySubentityCode>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">NOR</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">980921565</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Name>eSender</cbc:Name>
                  <cbc:Telephone>+47 21018800</cbc:Telephone>
                  <cbc:Telefax>+47 21018801</cbc:Telefax>
                  <cbc:ElectronicMail>post@mercell.com</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
          </efac:Organizations>
        </efext:EformsExtension>
      </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>
  <cbc:UBLVersionID>2.3</cbc:UBLVersionID>
  <cbc:CustomizationID>eforms-sdk-1.5</cbc:CustomizationID>
  <cbc:ID schemeName="notice-id">329ffbda-d4c2-42ee-afae-9b585d0a9519</cbc:ID>
  <cbc:IssueDate>2023-02-24+00:00</cbc:IssueDate>
  <cbc:IssueTime>05:55:12+00:00</cbc:IssueTime>
  <cbc:VersionID>01</cbc:VersionID>
  <cbc:RequestedPublicationDate>2023-03-24+02:00</cbc:RequestedPublicationDate>
  <cbc:RegulatoryDomain>32014L0024</cbc:RegulatoryDomain>
  <cbc:NoticeTypeCode listName="planning">pin-buyer</cbc:NoticeTypeCode>
  <cbc:NoticeLanguageCode>ENG</cbc:NoticeLanguageCode>
  <cac:ContractingParty>
    <cbc:BuyerProfileURI>http://buyer1.xx</cbc:BuyerProfileURI>
    <cac:ContractingPartyType>
      <cbc:PartyTypeCode listName="buyer-legal-type">body-pl</cbc:PartyTypeCode>
    </cac:ContractingPartyType>
    <cac:ContractingActivity>
      <cbc:ActivityTypeCode listName="authority-activity">defence</cbc:ActivityTypeCode>
    </cac:ContractingActivity>
    <cac:Party>
      <cac:PartyIdentification>
        <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
      </cac:PartyIdentification>
      <cac:ServiceProviderParty>
        <cbc:ServiceTypeCode listName="organisation-role">ted-esen</cbc:ServiceTypeCode>
        <cac:Party>
          <cac:PartyIdentification>
            <cbc:ID schemeName="organization">ORG-0002</cbc:ID>
          </cac:PartyIdentification>
        </cac:Party>
      </cac:ServiceProviderParty>
    </cac:Party>
  </cac:ContractingParty>
  <cac:ProcurementProject>
    <cbc:Name languageID="ENG">Title 1</cbc:Name>
    <cbc:Description languageID="ENG">Description 1</cbc:Description>
    <cbc:ProcurementTypeCode listName="contract-nature">services</cbc:ProcurementTypeCode>
    <cbc:Note languageID="ENG">Test notice</cbc:Note>
    <cac:MainCommodityClassification>
      <cbc:ItemClassificationCode listName="cpv">72243000</cbc:ItemClassificationCode>
    </cac:MainCommodityClassification>
  </cac:ProcurementProject>
</PriorInformationNotice>`

**Comment by Havunen** [comment]
Hi, thanks for reporting this issue. I will look into it tomorrow.

**Comment by Havunen** [comment]
This issue is now fixed in test environment, please note that notice subtype 1 is not supported notice type in Hilma.
You can find all supported notice types form Hilma web UI. 
https://testi.hankintailmoitukset.fi/fi/eforms/create
