### ISSUE TITLE
What is a difference between codes 201 and 200 returned from /eforms/external-write/v1/eform/can

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#147]
What is the difference between codes 201 and 200 returned from /eforms/external-write/v1/eform/can
Which one means the notice is submitted? 
Should I expect "hilmaNotice" to contain your notice id and "esentoolNotice" to be TED notice id?
Do I need to verify the content of "esentoolValidationReport" or it is enough to trust the response code 201 ?

**Comment by Havunen** [comment]
HTTP 201 means a new entry was created https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201
HTTP 200 means the request executed successfully in this case an existing notice was updated

**Comment by Havunen** [comment]
> Do I need to verify the content of "esentoolValidationReport" or it is enough to trust the response code 201 ?

We haven't yet finalized the API implementation and are not sure how it will be in the final version.

The initial plan is to validate the notice immediately and then fail the request if it does not pass the TED validations.
