### ISSUE TITLE
Not supported notice subtypes

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#148]
Could you confirm that Hilma is not supporting the following eForms subtypes
1, 2, 3, 10, 11, 12, 13, E1, E2, E3, E4, E5, T01, T02, X01, X02

How would you announce when any of mentioned forms would be supported?

**Comment by arinurkkala** [comment]
Yes, the list correct.

Out of these, E1 -> E5 notices will most likely be taken into use at some point. The problem with those is that the current TED api does not support them and the expected support is October 2023. We might take them into use before TED, but that will be decided by Hansel later. Currently updating the national notices are not our main priority.
