### ISSUE TITLE
Project specified in the request not owned by current writer

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#15]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
When trying to publish award notice hilma gives error Unauthorized Project specified in the request not owned by current writer. First of all. Parent and project should be for the writer. Migration issue from old hilma. Sencondly problem with not being able to publish award notices to projects originating from other than current api key was raised when optional parameter projectId stopped being optional.

This is issue atleast for two separate award notices.
parentId=2018-017897&projectId=28885
parentId=2018-013759&projectId=28874

**To Reproduce**
Request url:
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_7182?parentId=2018-017897&projectId=28885

Or
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_8250?parentId=2018-013759&projectId=28874

**Expected behavior**
Publishing should go ahead without unauthrozied error.

**API response**
401 Unauthorized
Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Wed, 19 Feb 2020 10:37:20 GMT 

Unauthorized Project specified in the request Id=28885 not owned by current writer=Foo. Specify a project created by current writer, or omit the project parameter to create a new project.

And

401 Unauthorized
Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Fri, 21 Feb 2020 09:56:07 GMT

Project specified in the request Id=28874 not owned by current writer=Foo. Specify a project created by current writer, or omit the project parameter to create a new project.

**Additional context**
POST should have ALL the same validations as PUT has. Both of these are ok by POST but when doing actual PUT suddenly errors appear.

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
There seems to be a migration bug, where some projects were not correctly assigned to their respective Ets user. I have created a hotfix defect for our migration team and they will fix this ASAP.

**Comment by arinurkkala** [comment]
Project ets ids have been fixed.

**Comment by cloudia-jt** [comment]
Id fixed? Does this require update to our database?

**Comment by arinurkkala** [comment]
No.
Just resend the request and it should work. The notice ets identifier was different from the project - they are now the same on all notices.
