### ISSUE TITLE
Cannot publish notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#150]
production_137379

The element 'CONTRACTING_BODY' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' 
has invalid child element 'CA_ACTIVITY_OTHER' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. 
List of possible elements expected: 'ADDRESS_PARTICIPATION_IDEM, ADDRESS_PARTICIPATION, URL_TOOL, CA_TYPE, CA_TYPE_OTHER, CE_ACTIVITY, CE_ACTIVITY_OTHER' 

<CA_ACTIVITY_OTHER>Kaupunkiympäristö</CA_ACTIVITY_OTHER>     </CONTRACTING_BODY>

no <CA_ACTIVITY> in xml

**Comment by Juhisee** [comment]
Investigating

**Comment by Juhisee** [comment]
Näyttäisi olevan sama tapaus kuin tässä: https://github.com/Hankintailmoitukset/hilma-api/issues/133

**Comment by Juhisee** [comment]
Closed as solved
