### ISSUE TITLE
TED xml is invalid

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#151]
"etsIdentifier": "production_138822",

"tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": false,
      "severity": "CRITICAL",
      "message": "Metadata could be retrieved from the XML file.",
      "details": "The xsd is not supported"
    }]

**Comment by Zamm** [comment]
Please try to send a new corrigendum. It seems like there maybe have been problems in TED.

**Comment by Zamm** [comment]
Removing nuts code '00' from the notice should resolve the issue. Hilma resolves nuts code '00' "Not specified" to old schema VERSION="R2.0.9.S03" what is deprecated in 27/04/2021.
