### ISSUE TITLE
Seems you allow only Finnish companies

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#152]
Added Mercell Group (org id 980921565) as eSender organization.
Got validation error 
`<svrl:failed-assert id="HILMA" location="ublExtensions.ublExtension.extensionContent.eformsExtension.organizations.organization.company.partyLegalEntity.companyID" xmlns:svrl="http://purl.oclc.org/dsdl/svrl">
        <svrl:text>Company Id (980921565) is not a valid National Identifier</svrl:text>
    </svrl:failed-assert>`

What about non-buyer types of organizations? like Procurement service provider, Review body, Tenderer etc?

**Comment by arinurkkala** [comment]
Yes, that is a valid point and I thank you for that.
We have created a ticket on our end and will plan this with Hansel. I hope to get to this as soon as possible.

**Comment by arinurkkala** [comment]
Hi,

The ticket is still in our backlog, but not in the current sprint, so it won't be completed in the following two weeks.
