### ISSUE TITLE
What is a value for nationalThreshold variable used in NoticeValidator.cs?

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#154]
Current GitHub project does not have a value for this variable. Is it some constant or something depending on notice subtype?

Also I see following code in NoticeValidator.cs, see below. What is a value behind GetTotalValue() ? Is it value of BT-27-Procedure
`if (eForm.IsContractAward() && eForm.GetTotalValue() < nationalThreshold)
            {
                return null;
            }`

**Comment by exttuosa** [comment]
Total value is the value in BT-161-NoticeResult and nationalThreshold is 60 000 (currently, and unlikely to change)
