### ISSUE TITLE
Function ValidateBT644()

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#155]
Function ValidateBT644() in NoticeValidator.cs is not clear

* what is a reason to limit an amount? it could be many billions of euro per my understanding

* could be a mistype here, you compare with 999999 but error stands for 999
`return values.Any(val => val is < 1 or > 999999)
                ? new ValidationError(path, "Maximum quantity has to be between 1 and 999")
                : null;`

**Comment by exttuosa** [comment]
This along with other similar validations with X amount of nines are placeholders for the actual limit that is still unfortunately unknown. These will  be updated as soon as we know the limits. 

This particular case will likely be javascript's max safe int (9007199254740991). And you are right, there is a mistype in the error message.
