### ISSUE TITLE
Notice statuses

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#158]
Could you share all notice statuses? would it be a different status for a notice published locally and published on ted?

What means status 2 below? Does it mean you are waiting for TED or does it mean Published?

`{
    "etsIdentifier": "606e1338-8588-498c-93a7-c5bc8d4b0816-01",
    "id": 2623,
    "procedureId": 2645,
    "hideFromOrganisationUsersWhileDraft": false,
    "hilmaState": 2,
    "tedState": 2
}`

**Comment by eduardsmirnov** [comment]
Now I got statuses changed, still not clear their meaning

`{
    "etsIdentifier": "606e1338-8588-498c-93a7-c5bc8d4b0816-01",
    "id": 2623,
    "procedureId": 2645,
    "hideFromOrganisationUsersWhileDraft": false,
    "hilmaState": 3,
    "tedState": 5
}`

**Comment by exttuosa** [comment]
Both of the enums added to the validation folder:

https://github.com/Hankintailmoitukset/hilma-api/blob/master/validation/HilmaState.cs
https://github.com/Hankintailmoitukset/hilma-api/blob/master/validation/TedState.cs

HilmaState 3 and TedState 5 means that the notice was successfully published in Ted.
