### ISSUE TITLE
What is a value of publication date in Hilma? I can find only TED publication date

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#160]
calling fetch API GET https://hns-hilma-test-apim.azure-api.net/eforms/external-write/v1/notice/{etsIdentifier}[?includeEForm]

I can get back hilmaState and tedState, also I can get back esentoolNotice.publicationDate.
How to get information on when exactly notice has been published on Hilma?

**Comment by exttuosa** [comment]
This is currently not available in the model. I'll make a ticket to add it.

**Comment by Havunen** [comment]
This has been implemented, please open a new ticket if there are any issues
