### ISSUE TITLE
Missing TED information in Fetch API

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#161]
I am calling API https://hns-hilma-test-apim.azure-api.net/eforms/external-write/v1/notice/606e1338-8588-498c-93a7-c5bc8d4b0816-01?includeEForm=False

which returns me TED state as published but no TED publication id and date
`{
    "etsIdentifier": "606e1338-8588-498c-93a7-c5bc8d4b0816-01",
    "id": 2623,
    "procedureId": 2645,
    "hideFromOrganisationUsersWhileDraft": false,
    "hilmaState": 3,
    "tedState": 5
}`

Is it because of notice value is below the national threshold of 60000? Unfortunately, I do not have any logic checking for national threshold during publication.

Is it possible to have some flag in the result saying that publication on TED was skipped?
Or would it be correct logic on our side to treat it this way that "tedState" == 5 AND "TedResponse" == null means "TED publication was skipped"?

**Comment by Havunen** [comment]
This is now implemented and should be working fine
