### ISSUE TITLE
What is a correct Hilma publication id?

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#163]
When I published my notice through API, I got the information below. What is the correct publication id which I can use further to refer to Hilma? is it "606e1338-8588-498c-93a7-c5bc8d4b0816-01" or something else? 
Also what is a full URL where I can see the published notice as a normal customer?

`{
    "etsIdentifier": "606e1338-8588-498c-93a7-c5bc8d4b0816-01",
    "id": 2623,
    "procedureId": 2645,
    "hideFromOrganisationUsersWhileDraft": false,
    "hilmaState": 3,
    "tedState": 5
}`

**Comment by eduardsmirnov** [comment]
To follow up a bit, my current understanding is that I need to know 2 numbers to be able to find my publication or open it as a public page. These are procedureId and id. Then I can build an URL like https://testi.hankintailmoitukset.fi/fi/public/procedure/2645/enotice/2623/participation

**Comment by Juhisee** [comment]
answer given in API meetings
