### ISSUE TITLE
TED rejects notice

### ISSUE THREAD

**Issue by anttiremesmercell** [Hankintailmoitukset/hilma-api#165]
etsidentifier: production_137799

BadRequest The notice cannot be published to TED: The element 'CONTRACTING_BODY'
 in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'CA_TYPE' 
 in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. 
 List of possible elements expected: 'URL_PARTICIPATION, ADDRESS_PARTICIPATION_IDEM, ADDRESS_PARTICIPATION' 
 in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , TED message formed: 
 <FORM_SECTION xmlns="http://publications.europa.eu/resource/schema/ted/R2.0.9/reception">   

 <F02_2014 LG="FI" CATEGORY="ORIGINAL" FORM="F02">  

<CA_TYPE VALUE="REGIONAL_AUTHORITY" />       
<CA_ACTIVITY VALUE="GENERAL_PUBLIC_SERVICES" />     
</CONTRACTING_BODY> 

hilma json
"ContractingAuthorityType": 4,
"MainActivity": 1

**Comment by Havunen** [comment]
Hi,

How is this different from the issues you posted previously? Can you apply the same fix?

https://github.com/Hankintailmoitukset/hilma-api/issues/133
https://github.com/Hankintailmoitukset/hilma-api/issues/150

**Comment by anttiremesmercell** [comment]
Different form now it is F02

**Comment by Havunen** [comment]
Ok, I will check

**Comment by Havunen** [comment]
In the JSON payload which you are sending to Hilma, `SendTendersOption` is `0` which is error case (undefined). You need to specify how you want the tenders to be sent. I'm guessing you need to select `1` which is the state for receiving tenders electronically because you have provided value for `ElectronicAddressToSendTenders`

Here is list of all possible values for `SendTendersOption`:

```csharp
/// <summary>
///     Default value, error state.
/// </summary>
Undefined = 0,   // 0 (int)

/// <summary>
///     Send tenders to a electronic address defined separately.
/// </summary>
[CorrigendumLabel("address_send_tenders", "I.3")]
AddressSendTenders = 1 << 0,   // 1 (int)

/// <summary>
///     Send tenders to a physical address given for the organisation earlier.
/// </summary>
[CorrigendumLabel("address_organisation_above", "I.3")]
AddressOrganisation = 1 << 1,   // 2 (int)

/// <summary>
///     Send tenders to physical address defined separately.
/// </summary>
[CorrigendumLabel("address_following", "I.3")]
AddressFollowing = 1 << 2,   // 4 (int)

/// <summary>
/// Send tenders to given email address. Only for national notices
/// </summary>
EmailSendTenders = 1 << 3,   // 8 (int)
```
