### ISSUE TITLE
My procedures -listing not working for my account

### ISSUE THREAD

**Issue by sv-citrus** [Hankintailmoitukset/hilma-api#166]
Yesterday the listing had 70 procedures from testing the ets-writing api.

Today listing is empty. 
From browsers devtool network tab i found out that  GET https://testi.hankintailmoitukset.fi/web/api/procedure/mine/page/0 fails with [HTTP/2 500 Internal Server Error 123ms]

The result includes the following json object.

{"type":"Hilma Application Error","title":"Something went wrong","status":500,"detail":"Something unexpected happened","traceId":"d4c7ca402e0aa65033e3ad0c0b33a0b5"}

Tried to use the Feedback link in https://testi.hankintailmoitukset.fi/en/feedback, but I'm not sure if it does anything.

My profile email is simo.viitanen@citrus.fi.

**Comment by Havunen** [comment]
Hi, thanks for reporting this issue. We are investigating it.

**Comment by Havunen** [comment]
I have fixed an issue with time formats, I'm guessing from logs that this was the issue you were having. Can you try again please

**Comment by sv-citrus** [comment]
seems to work now.
