### ISSUE TITLE
Documentation missing details on what is the actual data sent as "eForm"

### ISSUE THREAD

**Issue by kaskelotti** [Hankintailmoitukset/hilma-api#170]
The API docs state that when creating a notice to procede with type`CreateNoticeContract`, one should pass field `eForm` as string with "content of the eForm in base64".

What is this data type that is base64 encoded? Could not find anything appropriate for example in ets-write-eforms-api.json file. Documentation should be more clear on this for the users to know what to encode.

**Comment by Havunen** [comment]
It is the OP-TED eForms SDK XML notice
