### ISSUE TITLE
Hilma status code discrepancy between old and new API

### ISSUE THREAD

**Issue by kaskelotti** [Hankintailmoitukset/hilma-api#171]
The old ETS Write API uses HilmaStatus code values 0, 1, 2, 4, 8, 16 and the new eForms API uses values 0, 1, 2, 3, 4. The enum names are identical.

If there's no reason to change the numbering and the API is not public yet, it would be beneficial to keep the numbering the same. Otherwise this generates extra work on the client side.

**Comment by Juhisee** [comment]
The numbering was changed for technical reasons.
