### ISSUE TITLE
Notice is still "Sending to ted" Status

### ISSUE THREAD

**Issue by anttiremesmercell** [Hankintailmoitukset/hilma-api#172]
"modificationDate": "2023-05-11T07:52:20.4413422",
 "tedStatus": 1,

production_141318

**Comment by kallemarkkanen** [comment]
Thanks, I'll investigate

**Comment by anttiremes** [comment]
Same problem: production_147205

**Comment by kallemarkkanen** [comment]
The notice has been re-sent to ted and ted response and the new state is visible in notice. The state from TED 'rejected'

**Comment by anttiremes** [comment]
same issue.

production_149806
production_151237

**Comment by kallemarkkanen** [comment]
Thanks, we'll investigate

**Comment by kallemarkkanen** [comment]
We found that there where multiple notices from same sender, having the same problem. Notices with following EtsIdentifier have been sent to ted: 'etsidfixed_154072',  'production_149806' , 'production_147205',  'etsidfixed_154092', 'production_151237'

**Comment by anttiremes** [comment]
Same problem notice: production_158740

**Comment by jadefrantila** [comment]
Hi,

Notice with EtsIdentifier production_158740 has been resent to TED and its TED state has been updated accordingly.

**Comment by Juhisee** [comment]
Closed as resolved
