### ISSUE TITLE
Notice not found with search (eForms)

### ISSUE THREAD

**Issue by joosehuo** [Hankintailmoitukset/hilma-api#174]
https://testi.hankintailmoitukset.fi/fi/public/procedure/5371/enotice/6314/ not visible in Hilma search even though notice is published.

When notice is published it can be found with Hilma's search.

**Comment by jadefrantila** [comment]
We are looking into it!

**Comment by jadefrantila** [comment]
This issue is now fixed and you can find your notice 6314 within the search.
