### ISSUE TITLE
cannot publish notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#175]
BadRequest The notice cannot be published to TED: The element 'CONTRACTING_BODY' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has incomplete content. 
List of possible elements expected: 'URL_PARTICIPATION, ADDRESS_PARTICIPATION_IDEM, ADDRESS_PARTICIPATION, URL_TOOL, CE_ACTIVITY, CE_ACTIVITY_OTHER' in namespace 
'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , TED message formed: <FORM_SECTION xmlns="http://publications.europa.eu/resource/schema/ted/R2.0.9/reception">   
<F22_2014 LG="FI" CATEGORY="ORIGINAL" FORM="F22"> 

in cotracting_body
<ADDRESS_FURTHER_INFO_IDEM />     
</CONTRACTING_BODY>     

etsidentifier: production_149272

**Comment by Havunen** [comment]
Hi, were you able to resolve this issue? or is it still occuring?

**Comment by Juhisee** [comment]
closed as obsolete
