### ISSUE TITLE
TED publication ID

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#176]
Please help me to understand.
I am receiving following JSON data from API GET https://hns-hilma-test-apim.azure-api.net/eforms/external-write/v1/notice/4258901c-ca0b-4085-a466-bd63f718e986-01?includeEForm=False
{
    "etsIdentifier": "4258901c-ca0b-4085-a466-bd63f718e986-01",
    "id": 7670,
    "noticeNumber": "2023-007670",
    "procedureId": 6436,
    "hideFromOrganisationUsersWhileDraft": false,
    "hilmaState": 3,
    "tedState": 5,
    "datePublished": "2023-07-28T13:30:02.5645037Z"
}

Do I understand correctly that the field "noticeNumber" always means "TED publication ID" and in the case of national notice it will be always empty?

And what is a TED publication date? I can see only one "datePublished"

**Comment by Havunen** [comment]
Hi! I will look into this today

**Comment by Havunen** [comment]
`noticeNumber` is year of notice published + Hilma internal technical ID. 
`datePublished` is the publication date of Hilma notice

Do you need `Ted Publication Id` and TED publish date ? We can extend the model with that information

**Comment by Havunen** [comment]
The information is available when "includeEForms" is to true through the essentToolNotice dataset.

We shortly discussed this with the team, and decided that we can extend the main model with TED publication ID, TED submitted date, TED publish date information to ease the API usage.

**Comment by Havunen** [comment]
Hi @eduardsmirnov,

following properties have been added to the root of the API model to ease its usage.

```
{
    "etsIdentifier": "ets-identifier-uusi2-ef16",
    "id": 12706,
    "noticeNumber": "2023-012706",
    "procedureId": 12368,
    "hideFromOrganisationUsersWhileDraft": false,
    "hilmaState": 2,
    "tedState": 2,
    "tedPublicationId": null,
    "tedDateReceived": "2023-08-04T09:35:38+00:00",
    "tedDatePublished": null,
    "datePublished": null
}
```

I believe this resolves the issue you were having, please re-open this ticket if the issue still persists
