### ISSUE TITLE
Cannot re-submit a notice

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#178]
Maybe I do something totally wrong.

I submitted a notice (procedure=7004, id=8430) which was accepted by Hilma and later rejected by TED.
After some intermediate fixes on Mercell and Hilma sides, I want to re-submit a notice with correct information.

For that, I call Validate API (success) and then "Create a notice to a procedure" API.
Last call returns "Procedure already contains a notice in draft or waiting to be published state."

What should I do in this case?
@Havunen ?

**Comment by Havunen** [comment]
Hi, we will investigate this

**Comment by Havunen** [comment]
It is now possible to re-submit a eforms notice through the API, but only when Hilma state of the notice is DRAFT and Ted state is one of the following DELETED, STOPPED, VALIDATION_FAILED or NOT_PUBLISHED. It is important that the notice etsIdentifier must not change when resubmitting the notice. The hilma state will go back to draft automatically when TED returns one of those states from their API.

Please re-open if this is still an issue
