### ISSUE TITLE
Internal Server Error F15

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#18]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
POST/PUT for F15 form gives 500 internal server error

**To Reproduce**
POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/test_202003121330 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foo
`
{
	"TotalValue": {
		"Type": 1,
		"Value": 333333.3,
		"Currency": "EUR"
	},
	"LegalBasis": "32014L0024",
	"CommunicationInformation": {
		"AdditionalInformation": 1,
		"AdditionalInformationAddress": {
			"OfficialName": "Abrakadabra",
			"NationalRegistrationNumber": "0763840-2",
			"NutsCodes": [
				"FI"
			],
			"PostalAddress": {
				"StreetAddress": "Katukatulatie 77",
				"PostalCode": "33100",
				"Town": "Tampere",
				"Country": "FI"
			},
			"Email": "afdasasadf@foobarfoo.fo",
			"MainUrl": "http://hypertext.foofaa.fo"
		},
		"SendTendersOption": 0,
		"ElectronicCommunicationRequiresSpecialTools": false,
		"DocumentsEntirelyInHilma": false,
		"SpecsAndAdditionalDocuments": 0
	},
	"ComplementaryInformation": {},
	"ConditionsInformation": {
		"EconomicCriteriaToParticipate": false,
		"TechnicalCriteriaToParticipate": false,
		"RestrictedToShelteredWorkshop": false,
		"RestrictedToShelteredProgram": false,
		"ReservedOrganisationServiceMission": false,
		"ExecutionOfServiceIsReservedForProfession": false,
		"ObligationToIndicateNamesAndProfessionalQualifications": false
	},
	"ContactPerson": {
		"Email": "afdasasadf@foobarfoo.fo"
	},
	"EstimatedValue": {
		"Type": 1,
		"Value": 333333.3,
		"Currency": "EUR",
		"DisagreeToBePublished": true
	},
	"LotsInfo": {
		"DivisionLots": false,
		"LotsSubmittedFor": 0,
		"LotsMaxAwarded": false
	},
	"MainCpvCode": {
		"Code": "72267100",
		"Name": "ATK-ohjelmiston ylläpito",
		"VocCodes": []
	},
	"ObjectDescriptions": [
		{
			"MainCpvCode": {
				"Code": "72267100",
				"Name": "ATK-ohjelmiston ylläpito",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [
				"FI"
			],
			"DescrProcurement": [
				"Foobar teksti foofaa foo bar foo"
			],
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": {
				"ContractAwarded": 1,
				"NoAwardedContract": null,
				"AwardedContract": {
					"ConclusionDate": "2020-01-15T00:00:00",
					"ContractNumber": null,
					"ContractTitle": "Nimi foobar foo",
					"NumberOfTenders": {
						"Total": 0,
						"AwardedToGroupOfEconomicOperators": false,
						"Electronic": 0
					},
					"DisagreeContractorInformationToBePublished": null,
					"Contractors": [
						{
							"OfficialName": "Bronx cats",
							"NationalRegistrationNumber": "CZ12345678",
							"NutsCodes": [
								"CZ"
							],
							"PostalAddress": {
								"Town": "BRNO",
								"Country": "CZ"
							},
							"IsSmallMediumEnterprise": true
						}
					],
					"InitialEstimatedValueOfContract": {
						"Value": 333333.3,
						"Currency": "EUR"
					},
					"FinalTotalValue": {
						"Type": 1,
						"Value": 333333.3,
						"Currency": "EUR"
					},
					"LikelyToBeSubcontracted": false,
					"ExAnteSubcontracting": null,
					"PricePaidForBargainPurchases": null,
					"NotPublicFields": null,
					"ConcessionRevenue": null,
					"PricesAndPayments": null,
					"ConcessionValueAdditionalInformation": null
				}
			},
			"EstimatedValue": null,
			"TimeFrame": {
				"Type": 3,
				"BeginDate": "2020-01-15T00:00:00",
				"CanBeRenewed": false
			},
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": {
				"VariantsWillBeAccepted": false,
				"Options": true,
				"OptionsDescription": [
					"Foofaa baafoo asdf asdfasdf"
				],
				"OptionType": 0,
				"OptionsDays": 0,
				"OptionsMonths": 0
			},
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		}
	],
	"Organisation": {
		"Information": {
			"OfficialName": "Abrakadabra",
			"NationalRegistrationNumber": "0763840-2",
			"NutsCodes": [
				"FI"
			],
			"PostalAddress": {
				"StreetAddress": "Katukatulatie 77",
				"PostalCode": "33100",
				"Town": "Tampere",
				"Country": "FI"
			},
			"Email": "afdasasadf@foobarfoo.fo",
			"MainUrl": "http://hypertext.foofaa.fo"
		},
		"ContractingAuthorityType": 1,
		"MainActivity": 2
	},
	"Project": {
		"ContractType": 2,
		"Title": "Nimi foobar foo",
		"ProcurementCategory": 1,
		"JointProcurement": false,
		"CoPurchasers": [],
		"CentralPurchasing": false
	},
	"PublishToTed": false,
	"ShortDescription": [
		"Oafsdfa fsda fsda asdf"
	],
	"Type": 1500,
	"TenderingInformation": {
		"Languages": [],
		"TendersMustBeValidOption": 0,
		"TenderOpeningConditions": {}
	},
	"Language": "FI",
	"ProcedureInformation": {
		"ProcedureType": 15,
		"FrameworkAgreement": {
			"IncludesFrameworkAgreement": false
		},
		"ElectronicAuctionWillBeUsed": false,
		"ProcurementGovernedByGPA": true
	},
	"ProceduresForReview": {
		"ReviewBody": {
			"OfficialName": "Markkinaoikeus",
			"NutsCodes": [],
			"PostalAddress": {
				"StreetAddress": "Radanrakentajantie 5",
				"PostalCode": "00520",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"TelephoneNumber": "+358 295643300",
			"Email": "markkinaoikeus@oikeus.fi",
			"MainUrl": "http://www.oikeus.fi/markkinaoikeus"
		}
	},
	"IsCorrigendum": false,
	"Annexes": {
		"D1": {
			"ProvidedByOnlyParticularOperator": true,
			"ReasonForNoCompetition": 3,
			"Justification": [
				"Asdf sdf sfd sdf sfdsdfs",
				"Ofsdf sofds oimkl lkö jölkjlkfdsj fdshui ksdjh fkjhdfjsu "
			]
		}
	},
	"ContractAwardsDefence": null
}
`

**Expected behavior**
No internal server error

**API response**
Response status

500 Internal Server Error
Response latency
505 ms
Response content

Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Thu, 12 Mar 2020 11:31:06 GMT
Content-Length: 0

**Additional context**

**Comment by JuhaHonkaranta** [comment]
Annex D1 has no ProcedureType set and also ReasonForNoCompetition = 3 while the allowed values are 1, 2 and 4. We will clarify the errors in the future instead of returning a 500.
