### ISSUE TITLE
Exclusion grounds validation - required for subtype 4

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#180]
Trying to validate an XML using Hilma API, see attached.

Getting an error saying that exclusion grounds is missing. Is it really missing in case of subtype 4?

`{"type":"Hilma API Error","title":"Validation error","status":400,"detail":"Content validation failed, see errors and tedValidationResult for details","errors":{"tenderingTerms.tendererQualificationRequest.specificTendererRequirement.tendererRequirementTypeCode":["Mandatory exclusion ground fraud is missing!","Mandatory exclusion ground terr-offence is missing!","Mandatory exclusion ground finan-laund is missing!","Mandatory exclusion ground human-traffic is missing!","Mandatory exclusion ground tax-pay is missing!","Mandatory exclusion ground socsec-pay is missing!","Mandatory exclusion ground nati-ground is missing!"]}

[64d358ad5f6ff75142798a84.txt](https://github.com/Hankintailmoitukset/hilma-api/files/12321160/64d358ad5f6ff75142798a84.txt)
`

**Comment by arinurkkala** [comment]
I tried the validation endpoint with the same request with modified IssueDate and received 200 OK as response. Are you able to reproduce this issue?
The validation logic publicly available and shouldn't concern subtype 4.

**Comment by Juhisee** [comment]
Closed as resolved
