### ISSUE TITLE
Below EU threshold notices in the read API?

### ISSUE THREAD

**Issue by jokjadk** [Hankintailmoitukset/hilma-api#181]
I'm aware that you do not have national forms ready for the eForms write api.
But will we get below EU threshold notices from the eForms read API? i.e. because you are making a transformation from the current format to eForms?
Or do we need to read from the old as well as the new API to get both above and below threshold tenders?

**Comment by Juhisee** [comment]
Please see updated documentation for read API here: https://github.com/Hankintailmoitukset/hilma-api/blob/master/endpoints/avpendpoints.md
