### ISSUE TITLE
Notices of the same subtype cannot be submitted in the same procedure

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#185]
Published form with subtype 16
ets: 7db024af-96c6-47b4-9722-f8a7dab96e22-01
procedure id: 7875
form id: 9438

Using this form as a parent, attempted to submit 4 forms with subtype 29
all with procedure id 7875 and subtype 29
ets: 
	1cc4a6ba-a6cc-48c1-96ff-cc279c1a9b18-01
	e17534d5-7c0e-4965-be51-e266e424432b-01
	c5db215d-a96a-49ad-879f-be6fbf3362a8-01
	2f07508a-0246-48db-9954-065d272a35f1-01
	
A form with ets 2f07508a-0246-48db-9954-065d272a35f1-01 has been validated and submitted, then got a status not published with a TED status "STOPPED". Why it has been stopped?

The other 3 forms (see ets above) were validated but not accepted with the error message "Procedure already contains a notice in draft or waiting to be published state."

By our logic, it should be allowed to be able to submit many notices of the same subtype per procedure but it does not work as expected.
What do we do wrong? Is it our issue or Hilma issue?

**Comment by JuhaHakli** [comment]
I'm looking into it. I'll keep you updated.

**Comment by JuhaHakli** [comment]
This is probably our bad. We were testing the stop publication functionality in enotices2 preview around the same time, in preparation for a test case in production, and it is possible that the form 2f07508a-0246-48db-9954-065d272a35f1-01 was an unintended casualty.

We reckon that, either we manually and unintentionally stopped that notice, or something went wrong on the TED side of things. Either way, please notify us if this ever happens again.

**Comment by eduardsmirnov** [comment]
We had a meeting with @arinurkkala and agreed this issue with many forms of the same subtype created for a single published parent is treated as a bug and should be fixed.
Please notify us when we can test it. Thanks.

**Comment by arinurkkala** [comment]
The change has been approved and is in our pipeline. In about 1h it should be in all test environments.

**Comment by arinurkkala** [comment]
The fix is now in Hilma test environment.

**Comment by jlouvrier** [comment]
Thank you for a swift reaction!

**Comment by eduardsmirnov** [comment]
Tested. Seems to work. You could close it.
