### ISSUE TITLE
Not allowed to create a change notice of subtype 16

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#186]
TEST environment (https://hns-hilma-test-apim.azure-api.net/eforms)

Published form with subtype 16
ets: a7743683-5233-44e2-878e-e66a08327771-01
procedure id: 7938
form id: 9508

Using this form as a parent, attempted to submit a CHANGE notice which is a form of subtype 16 with added Changes information.
same procedure id 7938 and subtype 16
ets: 52a58ed5-e6ab-45fd-81b2-1f97372c7927-01

A form with ets 52a58ed5-e6ab-45fd-81b2-1f97372c7927-01 has been validated but cannot be submitted due to error "{"type":"Hilma API Error","title":"Validation error","status":400,"detail":"Procedure already has a contract notice.","traceId":"5d51cc45f351d86be53cf02818271dfc"}"

By our logic, it should be allowed to be able to submit many notices of the same subtype per procedure (in this case, one more notice of subtype 16 being a change notice) but it does not work as expected.
What do we do wrong? Is it our issue or Hilma issue?

TED documentation for SDK 1.7 says (https://docs.ted.europa.eu/eforms/1.7/schema/change-notice.html):
"While changes may apply to notices of any form type, the Change notice Form Type and Notice Type values must be identical to the ones of the original notice."

**Comment by JuhaHakli** [comment]
Hello.

It appears that that specific validation is still using the deprecated notice type == "corr" for checking whether a notice is a change notice. I'll add this bug to the backlog and inform you on how it is progressing.

**Comment by jlouvrier** [comment]
@JuhaHakli Any update on this one? We had a quick sync with @arinurkkala yesterday and he said that it would be fixed during the day.

**Comment by eduardsmirnov** [comment]
@JuhaHakli I was able to re-submit mentioned change notice and it is now published (fake). Thanks.

**Comment by JuhaHakli** [comment]
Good. Closing then.
