### ISSUE TITLE
Error code 500 "Something went wrong"

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#190]
Could you please investigate, I got the following message in the Production environment when calling the get status API.
Could you confirm it is a message from Hilma? More details? What shall we do in this case?

{"type":"Hilma Application Error","title":"Something went wrong","status":500,"detail":"Something unexpected happened","traceId":"be19ec9490eb5b516eb9762cc1eabf0b"}
Executed at 2023-09-20T18:16:58+03:00

Attempt to call same API again was successful.

**Comment by arinurkkala** [comment]
Hilma was being updated during that time, so it was a short and temporary issue.

**Comment by Juhisee** [comment]
closed as resolved
