### ISSUE TITLE
National notice (created from API draft) can't be published in test environment (updated)

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#191]
National notices that can't be published in Hilma test environment. Notice is created through draft notice from SC Software APi

- Tilastotiedot-tab is not working (the page is blank)
- Esikatselu ja julkaisu -tab is not working (the page is blank)

All minimum data has been set and notice is otherwise ready for publishing.

![image](https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/31bea53d-8fc2-4278-ada5-169615ff7604)
![image](https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/3a7d6c57-0f1c-4f8e-9a53-f12997f009a1)

https://testi.hankintailmoitukset.fi/fi/procurement/114797/procedure/122298/nationalcontract/122298/project

**Comment by kallemarkkanen** [comment]
Can you include the url section for the screenshots so id values are visible

**Comment by OlliSurakka** [comment]
https://testi.hankintailmoitukset.fi/fi/procurement/114801/procedure/122305/nationalcontract/122305/project also this notice

**Comment by kallemarkkanen** [comment]
For some reason the statistics where null for this notice. The issue should be fixed now(if statistics are null, they are initialized again)

**Comment by Juhisee** [comment]
Closed as resolved, please open a new ticket if there are any issues
