### ISSUE TITLE
Hilma not providing link to procurement documents for all notice types

### ISSUE THREAD

**Issue by joosehuo** [Hankintailmoitukset/hilma-api#194]
See for example: https://www.hankintailmoitukset.fi/fi/public/procedure/437/enotice/454/ 

Procurement documents link is not provided in the notice even if BT-15 has content. 

We'd suggest that Hilma would provide similar link as with BT-18 if only BT-15 has been published.

**Comment by joosehuo** [comment]
To clarify this, there should be the "participate button" similar to BT-18 that directs to procurement documents if only BT-15 is provided.

**Comment by Juhisee** [comment]
Ticket HILMA-7038 created to backlog.
