### ISSUE TITLE
Stuck notice - what to do?

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#198]
Notice ETS is 63d4cd56-3ec6-469d-8ebf-c111af689b39-01
Current status you can see in an attached screenshot.
![image](https://github.com/Hankintailmoitukset/hilma-api/assets/59865467/51f462d9-6a92-4d51-9437-5a821b01544e)

What should we do? 
Is it really our problem that you were not able to authorize to TED?

**Comment by eduardsmirnov** [comment]
I re-submitted it but still not clear why internal HIlma issues should bring to a notice being stuck

**Comment by Havunen** [comment]
The only TedErrorStates in production DB are about TED maintenance break: 
```
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>

```

**Comment by eduardsmirnov** [comment]
@Havunen I re-submitted 63d4cd56-3ec6-469d-8ebf-c111af689b39-01
and also a couple of other notices.

But the main question is why you move a notice into the status which requires us to re-submit a notice.

**Comment by Havunen** [comment]
> But the main question is why you move a notice into the status which requires us to re-submit a notice.

Ah, yes. We have a technical improvement about it.

**Comment by exttuosa** [comment]
The fix going live in next release will only fix known retriable errors, such as 503 and similar codes. The original problem in this ticket (which seems to have been misconfiguration in TED's end) will not be retried. There currently is no way of knowing if a TED error is transient or not. They did promise to clarify this in the future releases though.
