### ISSUE TITLE
BT-507 validation is wrong

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#199]
Attempting to validate a notice containing an Organization with a Country=Israel and missing NUTS code gives us an error "CountrySubentityCode cannot be empty for company ...".
It comes from ENoticeValidator.cs, ValidateBT507OrganizationCompany(). This code expects all companies to have a NUTS code. However, Israel does not have NUTS codes so this condition cannot be valid.

Please fix it it ASAP as our customer cannot publish a notice due to this issue.

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
Fix incoming. Should be in prod in ~30 min

**Comment by arinurkkala** [comment]
Fix should now be in production.
BT507 validation was removed.

**Comment by eduardsmirnov** [comment]
Seems to work, I was able to submit a notice.
You could close this one.

**Comment by arinurkkala** [comment]
Closed
