### ISSUE TITLE
F17 Corrigendum POST TED validation internal server error

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#2]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Trying to validate form 17 Corrigendum with POST and internal server error given as response

**To Reproduce**
`curl -d infernal.json -H 'Ocp-Apim-Subscription-Key: foo' -H 'Content-Type: application/json' -X POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/manual_202001271530?parentId=2019-025368&projectId=25445`

- HTTP method: POST
- HTTP headers
```
POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/manual_202001271530?parentId=2019-025368&projectId=25445 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key:

```
- sample request payload
sent as email

**Expected behavior**
Response: TED validation info

**API response**
```
500 Internal Server Error
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Mon, 27 Jan 2020 13:30:46 GMT
Content-Length: 0
```

**Additional context**

**Comment by tuomastolvanen** [comment]
According to the parent id (2019-017081) for the notice to be corrected is of type F05. Could you send the original notice number.

**Comment by cloudia-jt** [comment]
Edited correct parent and project id. Though no change in response. Internal server error all the same

**Comment by tuomastolvanen** [comment]
The main issue here is that the notice is missing both notice.legalBasis and project.procurementCategory. This results in Undfined ProcurementCategory and procurement category must be same than the original (Defence). Adding either correct legal basis or  ProcurementCategory.Defence will resolve the issue. 

The error does not result internal server error any more. Here is the local version of the validation error.

Updating procurement category, contract type is not allowed for published projects
Notice validation failed System.Net.Http.StringContent:
BadRequest: Bad Request

**Comment by cloudia-jt** [comment]
POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/test_202002041141?parentId=2019-025368&projectId=25445 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foo

same payload than previously

Response status

500 Internal Server Error
Response latency
200 ms
Response content

Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Tue, 04 Feb 2020 09:41:32 GMT
Content-Length: 0

**Comment by cloudia-jt** [comment]
Fixed payload with ProcurementCategory but not with legalbasis

POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/test_202002041235?parentId=2019-025368&projectId=25445 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foo

Payload: Check email. 

Response status

500 Internal Server Error
Response latency
627 ms
Response content

Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Tue, 04 Feb 2020 10:35:17 GMT
Content-Length: 0

**Comment by cloudia-jt** [comment]
LegalBasis and ProcurementCategory fixed

POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/test_202002041250?parentId=2019-025368&projectId=25445 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foo

Check email for payload.


Response status

500 Internal Server Error
Response latency
1178 ms
Response content

Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Tue, 04 Feb 2020 10:50:23 GMT
Content-Length: 0

**Comment by tuomastolvanen** [comment]
We are continuing investigation

**Comment by tuomastolvanen** [comment]
The main remaining issue is that the organisation is missing Nuts code in organisation.information. If not nuts, it should be initialized with [] and preferably added NUTS code. 

There were additional null reference issues in non required fields. We are releasing hotfix for those issues today.

**Comment by tuomastolvanen** [comment]
The hotfix for Defence corrigendum notices has been published to production. Technically the notice can be published now. There seems to bee still some information missing compared to the original notice:
project.referenceNumber (not required but there is one on original notice)
lotsInfo.lotsSubmittedFor (when divisionLots == true)
procedureInformation.includesFrameworkAgreement (when framework agreement)

**Comment by cloudia-jt** [comment]
> 
> 
> The main remaining issue is that the organisation is missing Nuts code in organisation.information. If not nuts, it should be initialized with [] and preferably added NUTS code.
> 
> There were additional null reference issues in non required fields. We are releasing hotfix for those issues today.

What do you mean nuts is missing?
[TED F17](https://www.hankintailmoitukset.fi/fi/documentation/1700) in your documentation organisation.information does not contain nuts codes.

**Comment by tuomastolvanen** [comment]
You are correct, for defence notices the organisation nuts code is not used. It is ok now to leave it undefined and the handling is fixed to support the situation.
