### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by eduardsmirnov** [Hankintailmoitukset/hilma-api#200]
The polling notice for status returned us "Internal server error".  Production environment,
Could you explain what exactly happened and what shall we do in this case?

ETS: bc9f2695-0871-4ff9-90e1-20078dbe8e1c-01
"executedAt": "2023-10-14T23:31:37.55Z",
"errorMessage": "{ \"statusCode\": 500, \"message\": \"Internal server error\", \"activityId\": \"b34de179-aba4-419f-b5fb-bb25ddcefdc3\" }"

**Comment by arinurkkala** [comment]
Couldn't find any specific backend logs related to this. Seems like there is some transient issue close to midnight. For now I would recommend to ignore this.

**Comment by Havunen** [comment]
Lets add alert for this to avoid these in future
