### ISSUE TITLE
All requests fails to CORS error in Hilma API portal

### ISSUE THREAD

**Issue by ScRistinen** [Hankintailmoitukset/hilma-api#201]
All requests fails to CORS error in Hilma API portal
![image](https://github.com/Hankintailmoitukset/hilma-api/assets/141320416/22980cb0-2d65-44ea-b708-fc8876872f91)

**To Reproduce**
1. Go to https://hns-hilma-test-apim.developer.azure-api.net/apis
2. Open some API (I tested with [Write API](https://hns-hilma-test-apim.developer.azure-api.net/api-details#api=ets-write-api) and[Write API (EForms)](https://hns-hilma-test-apim.developer.azure-api.net/api-details#api=ets-write-eforms-api) )
3. Run test query to some end point

**Comment by Havunen** [comment]
Thanks for reporting this issue. We will look into it.

**Comment by Havunen** [comment]
This was configuration error. It should work now! :)
