### ISSUE TITLE
Linkage between parent CAN for terminated CN not visible in Hilma UI

### ISSUE THREAD

**Issue by joosehuo** [Hankintailmoitukset/hilma-api#202]
**Describe the bug**
Linkage between parent CAN for terminated CN not visible in Hilma UI

 CN: 4677/02.05.00.01/2023 / Purku-urakka, talven pienkohteet 2023, Lahti 

 CAN: 4677/02.05.00.01/2023 / KESKEYTYSILMOITUS: Purku-urakka, talven pienkohteet 2023, Lahti

**Comment by arinurkkala** [comment]
Investigating

**Comment by Havunen** [comment]
Closing, as this issue has been fixed!
