### ISSUE TITLE
Stop API available for stopped eForm Notices ?

### ISSUE THREAD

**Issue by ankur-mercell** [Hankintailmoitukset/hilma-api#206]
Hi Team, 

Any stop api available to stop e-Form notices. please suggest if you have any information related to this.

referring below docs

https://hns-hilma-test-apim.developer.azure-api.net/api-details#api=ets-write-api&operation=post-external-api-v1-notice-etsidentifier-stop-publication

**Comment by jadefrantila** [comment]
Hi!

Thanks, this is a great suggestion. We will add this to our backlog.
