### ISSUE TITLE
"401 This API Key does not exist." error when communicated with HILMA test API

### ISSUE THREAD

**Issue by jlouvrier** [Hankintailmoitukset/hilma-api#209]
Hi! 
We are receiving the above error when trying to publish to your test API. Have you made changes recently? Should we move to your stage API?

**Comment by jadefrantila** [comment]
Hi!

Test API should work, so there's no need to move to staging. We will investigate this.

**Comment by jadefrantila** [comment]
Hi!

This issue has been resolved, there was a configuration issue on our part. Publishing should work now also on dev and test environments!

**Comment by jlouvrier** [comment]
Thanks! I will test again.
