### ISSUE TITLE
avp-read-api search notices doesn't find published notice

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#21]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
avp read api's search notices does not find notice that is published with ojs number.

**To Reproduce**
POST https://api.hankintailmoitukset.fi/avp/notices/docs/search HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json
Ocp-Apim-Subscription-Key: foobar

{
	"search":"\"noticeOjsNumber\": \"2020/S 026-059207\"",
	"count":"true",
	"searchMode":"any",
	"orderby":"datePublished desc"
}

**Expected behavior**
Notice is found and it's info is given in response message.

**API response**
Response status
200 OK
Response latency
186 ms
Response content

Pragma: no-cache
request-id: 744cea0a-700b-45b3-bb38-eb5fa810f1fd
elapsed-time: 14
OData-Version: 4.0
Preference-Applied: odata.include-annotations="*"
Strict-Transport-Security: max-age=15724800; includeSubDomains
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-cache
Date: Thu, 19 Mar 2020 08:33:33 GMT
Content-Length: 134
Content-Type: application/json; odata.metadata=minimal
Expires: -1

{
  "@odata.context": "https://hns-hilma-prod-search.search.windows.net/indexes('notices')/$metadata#docs(*)",
  "@odata.count": 0,
  "value": []
}

**Additional context**
Notice id in hilma 40695, etsidentifier etsidfixed_9752

**Comment by jannef** [comment]
There seems to be multiple problems with the query:

1. The request JSON is not valid
2. Syntax (disregarding JSON errors) is not correct
3. The notice ojs number is not correct for notice Id=40695

Please refer to documentation for correct syntax:
https://docs.microsoft.com/fi-fi/rest/api/searchservice/Search-Documents

Relevant part for your query:
``` http
POST /indexes/hotels/docs/search?api-version=2019-05-06 
    {  
      "search": "hôtel",  
      "searchFields": "Description_fr"
    }  
```

Closing the issue as there seems to be nothing wrong with the API

**Comment by cloudia-jt** [comment]
According to write api ojs for notice Id=40695 is "2020/S 047-110322"

HTTP request
GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_9752?includeNotice=False HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key: foo

Response status
200 OK
Response latency
178 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Thu, 19 Mar 2020 10:49:45 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-040695",
  "noticeOjsNumber": "2020/S 047-110322",
  "creationDate": "2020-03-03T17:05:38.1935329",
  "modificationDate": "2020-03-06T08:00:02.9031899",
  "hilmaStatus": 2,
  "hilmaPublicationDate": "2020-03-05T17:10:04.3696611",
  "etsIdentifier": "etsidfixed_9752",
  "organisationId": "0203107-0",
  "projectId": 32231,
  "noticeId": 40695,
  "tedPublicationInfo": {
    "documentNumber": "2020/S 047-110322",
    "links": {
      "fi": "http://ted.europa.eu/udl?uri=TED:NOTICE:110322-2020:TEXT:FI:HTML"
    },
    "orderNumberInSeries": "047",
    "publicationDate": "2020-03-06T08:00:00",
    "publicationRequestedDate": "2020-03-03T17:05:40.5934069"
  },
  "tedStatus": 4,
  "tedSubmissionId": "20200303-006575",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": []
  }]
}

**Comment by jannef** [comment]
Seems like there is an issue in the search index too, the ojs number is null.

``` json
{
"id": "40695",
"noticeOjsNumber": null,
}
```

**Comment by cloudia-jt** [comment]
Example of working read api query

POST https://api.hankintailmoitukset.fi/avp/notices/docs/search HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json
Ocp-Apim-Subscription-Key: foobar

{
	"search":"\"noticeOjsNumber\": \"2020/S 026-059207\"",
	"count":"true",
	"searchMode":"any",
	"orderby":"datePublished desc"
}

Response status
200 OK
Response latency
172 ms
Response content

Pragma: no-cache
request-id: 6343f7ef-49f5-4bc4-91a1-030f4b3ffd4b
elapsed-time: 19
OData-Version: 4.0
Preference-Applied: odata.include-annotations="*"
Strict-Transport-Security: max-age=15724800; includeSubDomains
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-cache
Date: Thu, 19 Mar 2020 10:54:21 GMT
Content-Length: 2992
Content-Type: application/json; odata.metadata=minimal
Expires: -1

{
  "@odata.context": "https://hns-hilma-prod-search.search.windows.net/indexes('notices')/$metadata#docs(*)",
  "@odata.count": 1,
  "value": [{
    "@search.score": 0.19552347,
    "id": "37816",
    "noticeOjsNumber": "2020/S 026-059207",
    "datePublished": "2020-02-05T05:50:03.016Z",
    "dateModified": "2020-02-06T07:00:03.045Z",
    "procurementProjectId": 30298,
    "type": 200,
    "mainType": "ContractNotices",
    "projectTitle": "Yle Tokyo 2020 Broadcasting unit rental services",
    "projectTitleNormalized": "YLE TOKYO 2020 BROADCASTING UNIT RENTAL SERVICES",
    "cpvCodes": "92221000 Television production services",
    "organisationName": "Yleisradio Oy",
    "organisationNationalRegistrationNumber": "0215438-8",
    "organisationAddress": "Radiokatu 5 00024 Yleisradio FI",
    "nutsCodes": " FI1B1  00",
    "organisationDepartment": null,
    "projectShortDescription": null,
    "objectDescriptions": " Yle search for service provider to act as the provider of certain multilateral and unilateral production facilities and related services in the name of Yle.   Yle\u2019s goal is a production facility with equipment, planning, onsite setup, onsite maintenance, onsite support and derigg done by the supplier in this tender. Also freight to test setup in Finland, freight to IBC and back to supplier is on the supplier.   In such cases where the offered equipment is more unknown to Yle personnel operative training will be needed. Persons involved per topic would be 3-5. This operative training must be included in the tender.  Yle search a production facility for receiving, routing, processing and finally sending to Helsinki  both video and audio signals obtained from Host and from own sources. Yle takes care of the transmission equipment and telecom capacity. Yle\u00b4s supplier Lawo will include V-matrix units, V_remote and A_Mic8 units as interface units and Arista switches for broadcast IP network. In addition to this routing and conversion Yle also request 3 edit suites with Avid Composer connected to an Avid Nexis/Isis storage server as the facility's editing capacity.  The requirements and objectives concerning the offered system, the tenderer and the offered services for submitting the tender are described with details in appendices: Appendix 1 Description of the Broadcasting unit rental services  Appendix 2A Scope of work  Appendix 2B Technical requirements  Appendix 2C Technical drawings  Appendix 2D Floor plans of the room Appendix 2E Video sources  Appendix 2F Intercom map Appendix 3 Service Agreement  Appendix 4 General Terms of Public Procurement in Supply Contracts (JYSE 2014 Supplies)  ",
    "tendersOrRequestsToParticipateDueDateTime": "2020-03-06T12:00:00Z",
    "expirationDate": "2020-03-06T12:00:00Z",
    "parentId": null,
    "isLatest": true,
    "isCorrigendum": false,
    "isCancelled": false,
    "includesDynamicPurcharingSystem": false,
    "includesFrameworkAgreement": false,
    "isNationalProcurement": false,
    "noticeNumber": "2020-037816",
    "estimatedValue": 0.0,
    "currency": null,
    "energyEfficiencyConsidered": false,
    "innovationConsidered": false,
    "smeParticipationConsidered": false
  }]
}

**Comment by jannef** [comment]
How is the request possibly working? Are you using non-standard tooling? There is unescaped quatation marks inside a string, which causes the JSON to parse as follows:

``` json
{
	"search": ""
	noticeOjsNumber ": "
	2020 / S 026 - 059207 "",
	"count": "true",
	"searchMode": "any",
	"orderby": "datePublished desc"
}
```
```
Error: Parse error on line 2:
{	"search": ""	noticeOjsNumber ": "
---------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'
```

The issue anyhow seems to be that the ojs number is null for the given notice. It will be under investigation shortly.

**Comment by jannef** [comment]
Issue has been identified, and a fix will be deployed at later date. The notice search index has been rebuild to fix the current notices.

``` http
POST https://hns-hilma-prod-search.search.windows.net/indexes/notices/docs/search?api-version=2019-05-06
{
	"filter": "noticeOjsNumber eq '2020/S 047-110322'",
	"select": "noticeOjsNumber, id"
}
```

``` json
{
    "@odata.context": "https://hns-hilma-prod-search.search.windows.net/indexes('notices')/$metadata#docs(*)",
    "value": [
        {
            "@search.score": 1.0,
            "id": "40695",
            "noticeOjsNumber": "2020/S 047-110322"
        }
    ]
}
```

**Comment by arinurkkala** [comment]
Should be fixed now
