### ISSUE TITLE
Customer not able to change primary buyer with change notice

### ISSUE THREAD

**Issue by joosehuo** [Hankintailmoitukset/hilma-api#213]
Customer had provided wrong information for OPP-050 field for initial notice and when they tried to change this Hilma API sent this error and prevented publication: {"type":"Hilma API Error","title":"Validation error","status":400,"detail":"Notice primary buyer organisation is not the same the organisation procedure was created for","traceId":"422376fba94e697b879b2a97b4a67ddc"}

How should we instruct our customer to fix this information about primary buyer?

**Comment by arinurkkala** [comment]
Is creating a new procedure / notice an option?

**Comment by joosehuo** [comment]
Well, it is an active notice published in 25.3. so it will lead to a delay in the procedure. But we can ask from the customer if this is possible.

https://www.hankintailmoitukset.fi/fi/public/procedure/5884/enotice/7449/
