### ISSUE TITLE
URGENT - Validation errors when submitting 1.7 notices to HILMA in production

### ISSUE THREAD

**Issue by jlouvrier** [Hankintailmoitukset/hilma-api#214]
Hi Ari,

All our forms are failing after submission to HILMA. It looks like the forms are validated against 1.10, but we are still sending in 1.7.

See for example b31054a3-2c75-4ab3-8e30-4013afa44f82-01

Could you please get back to us as soon as possible?

Best,
Julien

**Comment by arinurkkala** [comment]
On it.


-Ari
From: Julien Louvrier ***@***.***>
Sent: perjantai 12. huhtikuuta 2024 12.02
To: Hankintailmoitukset/hilma-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hankintailmoitukset/hilma-api] URGENT - Validation errors when submitting 1.7 notices to HILMA in production (Issue #214)


Hi Ari,

All our forms are failing after submission to HILMA. It looks like the forms are validated against 1.10, but we are still sending in 1.7.

See for example b31054a3-2c75-4ab3-8e30-4013afa44f82-01

Could you please get back to us as soon as possible?

Best,
Julien

-

**Comment by jlouvrier** [comment]
Also experiencing errors when submitting a notice after fixing it even though we always increase the version number when resubmitting.
Hilma API Error","title":"Duplicate entry error","status":409,"detail":"A record with same value already exists!","traceId":"2e290a574d2aa3b74af2d96bb5159aeb

**Comment by arinurkkala** [comment]
TED validator uses the SDK version defined in the EForms CustomizationID. Still investigating if there's something else..


-Ari
From: Julien Louvrier ***@***.***>
Sent: perjantai 12. huhtikuuta 2024 12.02
To: Hankintailmoitukset/hilma-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hankintailmoitukset/hilma-api] URGENT - Validation errors when submitting 1.7 notices to HILMA in production (Issue #214)


Hi Ari,

All our forms are failing after submission to HILMA. It looks like the forms are validated against 1.10, but we are still sending in 1.7.

See for example b31054a3-2c75-4ab3-8e30-4013afa44f82-01

Could you please get back to us as soon as possible?

Best,
Julien

-

**Comment by arinurkkala** [comment]
Found the bug. During the publish phase, it was sent using SDK 1.10. Sorry for the inconvenience. Fix in prod ~30 minutes

-Ari

**Comment by jlouvrier** [comment]
@arinurkkala Thank you for your swift action. Please let us know as soon as the fix is in production, we have plenty of notices awaiting to be resubmitted.

**Comment by jlouvrier** [comment]
@arinurkkala What about the following error: Hilma API Error","title":"Duplicate entry error","status":409,"detail":"A record with same value already exists!","traceId":"2e290a574d2aa3b74af2d96bb5159aeb

**Comment by arinurkkala** [comment]
I'll look into this as well

**Comment by arinurkkala** [comment]
> @arinurkkala Thank you for your swift action. Please let us know as soon as the fix is in production, we have plenty of notices awaiting to be resubmitted.

Fix should now be in production.

**Comment by arinurkkala** [comment]
> @arinurkkala What about the following error: Hilma API Error","title":"Duplicate entry error","status":409,"detail":"A record with same value already exists!","traceId":"2e290a574d2aa3b74af2d96bb5159aeb

It appears you are sending a new EtsIdentifier for each version, so Hilma understands it as a new notice. It then throws an exception, because a notice with the same GUID already exists. For resubmitting, you should use the same EtsIdentifier (in this case the version 1).

**Comment by jlouvrier** [comment]
@arinurkkala We have always done that version increase when resubmitting. We submit the same ID, but we increase the version -01, -02 etc... It's never been an issue.

We submitted this one: 26f5bbfc-34d1-4a7e-b415-43b8d55da781-01, it failed due to 1.7 / 1.10 issue
then it was resubmitted as : 26f5bbfc-34d1-4a7e-b415-43b8d55da781-02

**Comment by arinurkkala** [comment]
Inside the EForms, yes it should be increased. Byt the EtsIdentifier -query param should not change, as it is the same notice from Hilma perspective.
If you want a quick fix, we can do a hard delete for the 2 notices that are currently in that state?

**Comment by jlouvrier** [comment]
Yes, that would be very helpful. Please go ahead!

**Comment by arinurkkala** [comment]
The notices listed above have been hard deleted. You may resubmit them.

**Comment by arinurkkala** [comment]
Verified that all notices have been successfully resubmitted. Closing issue.
