### ISSUE TITLE
BT-15, field loses prior data

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#215]
There is a problem with field BT-15 losing the prior data in the Hilma UI.

Steps:
1.	Draft notice is created through draft API (ef16 tested)
2.	In the field BT-15 (url) the imported data from SC Software is shown correctly. Data can be saved and works normally.
3.     The user moves to Ilmoitukset tiedot -tab and saves.
4.	The user moves back to Ilmoituksen yleiset tiedot-tab.

Actual:

The prior saved data in the field BT-15 is missing.

Expected:

The prior saved data in the field BT-15 is not missing.

A video about the problem is enclosed.

https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/ae2635c6-0cbe-44f7-a145-5845a031d2de

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
Fix coming to test. ETA ~50 min.

**Comment by OlliSurakka** [comment]
Tested with two different testnotices (ef16) -> The problem still exist: data is lost when the user moves to Ilmoitukset tiedot -tab and saves.

**Comment by arinurkkala** [comment]
Just to be sure - the fix was to Hilma UI and it requires that you have the latest bundle. Did you try Ctrl + F5 and then test?

**Comment by OlliSurakka** [comment]
Yes, problem still exist after Ctrl + F5

**Comment by arinurkkala** [comment]
Can you provide the JSON, so I can try to reproduce the issue?

**Comment by OlliSurakka** [comment]
Here is example of the JSON.

Lähettäjä: Ari Nurkkala ***@***.***>
Lähetetty: torstai 18. huhtikuuta 2024 8.46
Vastaanottaja: Hankintailmoitukset/hilma-api ***@***.***>
Kopio: Olli Surakka ***@***.***>; Author ***@***.***>
Aihe: Re: [Hankintailmoitukset/hilma-api] BT-15, field loses prior data (Issue #215)


Can you provide the JSON, so I can try to reproduce the issue?

**Comment by OlliSurakka** [comment]
Here is example for JSON

[eFormsEsimerkki.json](https://github.com/Hankintailmoitukset/hilma-api/files/15024328/eFormsEsimerkki.json)

**Comment by arinurkkala** [comment]
There is a second fix in DEV -environment. Could you test it there?
Also deploying to staging at the moment.

**Comment by arinurkkala** [comment]
TEST -environment has also been updated with these changes.

**Comment by OlliSurakka** [comment]
Tested with ef16 in test environment. Problem still exist (video). Also now field BT-18 makes an error after moving to Osa-välilehti (image).

https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/66ab4e11-bc57-4b7e-a1ca-cfa4846af7af

<img width="516" alt="BT-18" src="https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/d216d3d4-28a8-4916-bfca-1f4d79f5108d">

**Comment by arinurkkala** [comment]
There was an issue with out cleaner that turned out to be an issue. I have made another fix.. sorry for the nth time this has been fixed. Hopefully now it is ok?

**Comment by OlliSurakka** [comment]
Yes, this is ok and fixed, thank you!
