### ISSUE TITLE
Hilma draft API changes procurementProjectLot identifier

### ISSUE THREAD

**Issue by ScRistinen** [Hankintailmoitukset/hilma-api#216]
**Describe the bug**Hilma draft API changes procurementProjectLot identifier. Procurement project lot data cannot be synchronized between applications because identifier does not match.

**To Reproduce**
1. Create notice draft
- API endpoint that the request was sent to: https://test-api.hankintailmoitukset.fi/eforms/external-write/v1/procedure/{procedureId}/notice/{etsIdentifier}/draft[?parentEtsIdentifier][&isCorrigendum]
- sample request payload: eFormsExampleSend.json
2. Read notice draft
- API endpoint that the request was sent to: https://test-api.hankintailmoitukset.fi/eforms/external-write/v1/notice/{etsIdentifier}/eform
- sample reponse payload: eFormsExampleRead.json

**Actual behavior**
Procurement project lot with identifier "LOT-0001" is sent.
Procurement project lot with identifier "LOT-0000" is read.

**Expected behavior**
Procurement project lot with identifier "LOT-0001" is sent.
Procurement project lot with identifier "LOT-0001" is read.

**Additional context**
[eFormsExampleRead.json](https://github.com/Hankintailmoitukset/hilma-api/files/15059758/eFormsExampleRead.json)
[eFormsExampleSend.json](https://github.com/Hankintailmoitukset/hilma-api/files/15059759/eFormsExampleSend.json)

**Comment by Havunen** [comment]
If there is only one ProcurementProjectLot the ID must be "LOT-0000", if there are more than one lot the ID must start LOT-0001. This is requirement in eForms SDK

**Comment by ScRistinen** [comment]
Ok. Hilma draft API didn't have this requirement before. This is breaking change and I haven't seen any notice about this change.

**Comment by Havunen** [comment]
this is requirement from TED since the implementation of eForms

**Comment by ScRistinen** [comment]
Well, I'm using Hilma draft API and it's behavior has changed without any notice. Originally, when the draft API was implemented, it was agreed that the draft API will do any necessary data mappings and cleaning so that we can always use the same data set. Now this is changed, without notice.

**Comment by ScRistinen** [comment]
No need to change response.
