### ISSUE TITLE
Negotiated procedure correction does not show Deadline section (draft API and Hilma UI)

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#217]
**Describe the bug**
Negotiated procedure correction does not show Deadline section.

**To Reproduce**

Background: Negotiated procedure, test environment

1.	The user has published a notice through draft API.
2.	The user makes a correction to a negotiated procedure and creates a new notice based on the correction through the API interface.
3.	The deadline section (Määräajat) is not visible in the Hilma user interface. (image)
<img width="688" alt="Määräajat" src="https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/0714c4ec-50d5-47c8-a874-2130886b0e8c">

4.	The same user interface problem also occurs in the correction of the negotiated procedure made directly in the Hilma user interface (without any draft API-notice). This happens when moving to preview and back to modification. (video)

https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/fe521b3f-52c1-40ba-a306-6df038e4c855

**Expected behavior**
The Deadline section would be visible in the Hilma user interface, with fields for the deadline for tenders. Notice can be sent.

**Comment by arinurkkala** [comment]
Can you provide the initial payload used in draft API?

**Comment by OlliSurakka** [comment]
[Neuvottelumenettely.json](https://github.com/Hankintailmoitukset/hilma-api/files/15198684/Neuvottelumenettely.json)
Here is json for corrected negotiated procedure

**Comment by arinurkkala** [comment]
The tendering -flag is different in the video compared to example. I also tried to reproduce this, but could not.. 
Are you still able to reproduce this issue? Asking, because it looks very similar to the issue that was recently closed.
Do you have the original json as well?
It looks like this has been deleted, and since there is a hard delete, I cannot access it easily.

**Comment by OlliSurakka** [comment]
This problem is fixed based on testing. This can be closed
