### ISSUE TITLE
National prior information notice / market consultation can't be published (through Draft API)

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#218]
**Describe the bug**
National prior information notice / market consultation can't be published. Notice has been created through Draft API

**To Reproduce**
User creates a National prior information notice / market consultation through Draft API
User fills all mandatory fields.
![image](https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/bec7ab77-06e8-4c04-8f18-c54f1f6bc605)

User open preview and publishing page
The preview doesn't work properly (image)
![image](https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/34397f55-94b9-4437-98e8-1741e3a8e315)

The notice can't be published.

**Expected behavior**
Notice can be previewed and puslished.

**Comment by arinurkkala** [comment]
Can you provide the initial payload used in draft API?

**Comment by arinurkkala** [comment]
There is one fix in Test -environment. Hopefully it resolves this issue

**Comment by OlliSurakka** [comment]
Fix is ok, issue resolved
