### ISSUE TITLE
Notices validated but later rejected, but we don't knwo the error 

### ISSUE THREAD

**Issue by MaxKholoshnyi** [Hankintailmoitukset/hilma-api#219]
Good afternoon guys.

We have couple notices that were submitted to Hilma but later chnaged status to not-published. Problem is that we don't understand the reason for rejection as it passed validation and was registered at 1st by Hilma. 
Can you please have a look 2 latest examples (let me know if I need to provide more) :
9d374f55-dd33-41b9-8cf2-c2eaf63571bb-01
01a29243-02ea-4456-9373-5153ca3ed9d3-01

Thank you.
Max

**Comment by solita-reddy** [comment]
Hey Max, 

Correct me if I'm wrong, looks like the two examples you supplied above are duplicates?

Regards,
Jake

**Comment by MaxKholoshnyi** [comment]
Umm honestly I can't say, could be that customer tried to create another one, but for me it's different notices.
Fresh exmaple :
 141eba55-82c3-4567-aba4-b13e487f0721-01

**Comment by solita-reddy** [comment]
The ID provided above is also rejected due to it being a duplicate.

One of my colleagues mentioned that this could be linked to the TED outage we experienced last week. Regardless I am happy to continue to investigate any issues that continue to arise.

**Comment by MaxKholoshnyi** [comment]
Well if it's duplicate it's still fine, we shall have a look to it as well than, But need to know if it's UUIUD: 141eba55-82c3-4567-aba4-b13e487f0721-01 is duplicate,  or somethign else triggers it as duplicate. Thanks

**Comment by solita-reddy** [comment]
Yes, the above UUID is a duplicate. Find the original here: https://www.hankintailmoitukset.fi/fi/public/procedure/7250/enotice/9477/

**Comment by MaxKholoshnyi** [comment]
Hmm that is a bit odd, when from the link you provided to TED it's actually shows NoticeId:  61f4d94f-54e6-4545-9f1b-590bf3af98c4 - 01 Which is indeed published notice in our system.
So I'm a bit confused how could it be duplicate

**Comment by solita-reddy** [comment]
Hey Max, sorry for the confusion. 

It appears the UUID's you provided above are all corrigendum notices. 
For some reason the ChangedNoticeIdentifier (BT-758) Is pointing to a version that doesn't exist in our system.

For example, the case `141eba55-82c3-4567-aba4-b13e487f0721-01` is a change notice for `61f4d94f-54e6-4545-9f1b-590bf3af98c4-02` which is pointing to version 2 that is not in our system. We only currently have version 1.

This is that same for:
9d374f55-dd33-41b9-8cf2-c2eaf63571bb-01
01a29243-02ea-4456-9373-5153ca3ed9d3-01

**Comment by MaxKholoshnyi** [comment]
Hi Jake, 
Thanks for investigating. I guess the reason is that ETS indentifer for Hilma is can't chage but for TED we need to upgrade a version every time. I guess that's where it gone sideways.
Ye think oyu cna close the issue I will follow up.

**Comment by MaxKholoshnyi** [comment]
Closing. Got needed info.
