### ISSUE TITLE
F17 corrigendum internal server error

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#22]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
PUT/POST Corrigendum for F17 results in internal server error

**To Reproduce**
POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/test_202003191634?parentId=production_5813&projectId=31443 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foobar

{
	"LegalBasis": "32009L0081",
	"CommunicationInformation": {
		"ProcurementDocumentsUrl": "https://hanki.tarjouspalvelu.fi/hanki?id=284430&tpk=ae2ebb8b-aca0-4b34-8042-09fec4412399",
		"AdditionalInformation": 1,
		"AdditionalInformationAddress": {
			"OfficialName": "Poliisihallitus",
			"NationalRegistrationNumber": "2288666-6",
			"NutsCodes": [],
			"PostalAddress": {
				"StreetAddress": "Asemapäällikönkatu 14",
				"PostalCode": "00521",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"Email": "hankinnat.poliisihallitus@poliisi.fi",
			"MainUrl": "http://www.poliisi.fi"
		},
		"SendTendersOption": 1,
		"ElectronicAddressToSendTenders": "https://hanki.tarjouspalvelu.fi/hanki?id=284430&tpk=ae2ebb8b-aca0-4b34-8042-09fec4412399",
		"ElectronicCommunicationRequiresSpecialTools": false
	},
	"ComplementaryInformation": {
		"IsRecurringProcurement": false,
		"Defence": {
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		}
	},
	"ConditionsInformationDefence": {
		"DepositsRequired": [],
		"FinancingConditions": [],
		"LegalFormTaken": [],
		"OtherParticularConditions": [],
		"PersonalSituationOfEconomicOperators": [
			"katso kohta Soveltuvuusvaatimukset"
		],
		"EconomicCriteriaOfEconomicOperators": [
			"katso kohta Soveltuvuusvaatimukset"
		],
		"TechnicalCriteriaOfEconomicOperatorsMinimum": [
			"katso kohta Soveltuvuusvaatimukset"
		],
		"RestrictedToShelteredWorkshops": false,
		"RestrictedToShelteredProgrammes": false,
		"RestrictedToParticularProfession": false,
		"StaffResponsibleForExecution": false
	},
	"ContactPerson": {
		"Email": "hankinnat.poliisihallitus@poliisi.fi"
	},
	"LotsInfo": {
		"DivisionLots": true,
		"QuantityOfLots": 3,
		"LotsSubmittedFor": 1,
		"LotsMaxAwarded": false
	},
	"MainCpvCode": {
		"Code": "35330000",
		"Name": "Ampumatarvikkeet",
		"VocCodes": []
	},
	"ObjectDescriptions": [
		{
			"Title": "Pistoolin, konepistoolin ja kiväärin patruunat",
			"LotNumber": "1",
			"MainCpvCode": {
				"Code": "35330000",
				"Name": "Ampumatarvikkeet",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [],
			"DescrProcurement": [
				"Osa-alueen tarkempi erittely erillisenä toimitettavassa liitteessä. Katso tarkemmin kohta Muut tiedot - Tarjouksen/hakemuksen lähettäminen"
			],
			"AgreeAwardCriteriaToBePublished": true,
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": null,
			"EstimatedValue": null,
			"TimeFrame": null,
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": null,
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		},
		{
			"Title": "Simulaatiopatruunat",
			"LotNumber": "2",
			"MainCpvCode": {
				"Code": "35330000",
				"Name": "Ampumatarvikkeet",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [],
			"DescrProcurement": [
				"Osa-alueen tarkempi erittely erillisenä toimitettavassa liitteessä. Katso tarkemmin kohta Muut tiedot - Tarjouksen/hakemuksen lähettäminen"
			],
			"AgreeAwardCriteriaToBePublished": true,
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": null,
			"EstimatedValue": null,
			"TimeFrame": null,
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": null,
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		},
		{
			"Title": "Haulikon patruunat",
			"LotNumber": "3",
			"MainCpvCode": {
				"Code": "35330000",
				"Name": "Ampumatarvikkeet",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [],
			"DescrProcurement": [
				"Osa-alueen tarkempi erittely erillisenä toimitettavassa liitteessä. Katso tarkemmin kohta Muut tiedot - Tarjouksen/hakemuksen lähettäminen"
			],
			"AgreeAwardCriteriaToBePublished": true,
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": null,
			"EstimatedValue": null,
			"TimeFrame": null,
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": null,
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		}
	],
	"Organisation": {
		"Information": {
			"OfficialName": "Poliisihallitus",
			"NationalRegistrationNumber": "2288666-6",
			"NutsCodes": [],
			"PostalAddress": {
				"StreetAddress": "Asemapäällikönkatu 14",
				"PostalCode": "00521",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"Email": "hankinnat.poliisihallitus@poliisi.fi",
			"MainUrl": "http://www.poliisi.fi"
		},
		"ContractingAuthorityType": 2,
		"MainActivity": 4
	},
	"Project": {
		"Id": 31443,
		"ContractType": 1,
		"Title": "Patruunat (korjausilmoitus)",
		"ProcurementCategory": 2,
		"JointProcurement": false,
		"DefenceSupplies": 1
	},
	"PublishToTed": false,
	"ShortDescription": [
		"Hankinnan kohteena on patruunat poliisin, Suojelupoliisin, Rajavartiolaitoksen, Tullin ja Rikosseuraamuslaitoksen käyttöön",
		"",
		"HUOM! TÄMÄ ILMOITUS ON KORJAUSILMOITUS 11.12.2019 JULKAISTUUN HANKINTAILMOITUKSEEN 2019-025368 / 2019/S 239-587823. ",
		"HILMA-portaalissa ilmenneiden tietoteknisten ongelmien vuoksi hankintayksikkö on pakotettu julkaisemaan korjausilmoituksen kokonaan uudella hankintaimoituksella. Tällä ilmoituksella ei aloiteta uutta hankintamenettelyä. ",
		"",
		"Osallistumishakemukset tulee laatia tässä korjausilmoituksessa annettujen tietojen perusteella.",
		"",
		"Yritysten, jotka ovat jo lähettäneet hankintayksikölle Kohdassa Muut tiedot - tarjouksen lähettäminen pyydetyt dokumentit ei tarvitse lähettää niitä uudelleen. "
	],
	"Type": 1700,
	"TenderingInformation": {
		"TendersOrRequestsToParticipateDueDateTime": "2020-04-24T14:00:00",
		"TenderOpeningConditions": {},
		"Defence": {
			"PreviousPublicationExists": false,
			"PayableDocuments": false,
			"LanguageType": 2,
			"Languages": [
				"FI"
			],
			"OtherLanguage": false
		}
	},
	"Language": "FI",
	"ProcedureInformation": {
		"ProcedureType": 2,
		"ElectronicAuctionWillBeUsed": false,
		"Defence": {
			"CandidateNumberRestrictions": {},
			"AwardCriteria": {
				"CriterionTypes": 2,
				"EconomicCriteriaTypes": 8
			}
		}
	},
	"ProceduresForReview": {
		"ReviewBody": {
			"OfficialName": "Markkinaoikeus",
			"NutsCodes": [],
			"PostalAddress": {
				"StreetAddress": "Radanrakentajantie 5",
				"PostalCode": "00520",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"TelephoneNumber": "+358 295643300",
			"Email": "markkinaoikeus@oikeus.fi",
			"MainUrl": "http://www.oikeus.fi/markkinaoikeus"
		}
	},
	"Defence": {
		"NutsCodes": [],
		"Subcontract": {
			"TendererHasToIndicateShare": true,
			"TendererHasToIndicateChange": true,
			"CaMayOblige": false,
			"SuccessfulTenderer": false,
			"SuccessfulTendererMin": 0.0,
			"SuccessfulTendererMax": 0.0,
			"SuccessfulTendererToSpecify": true
		},
		"OptionsAndVariants": {
			"VariantsWillBeAccepted": false,
			"Options": false,
			"OptionType": 0,
			"OptionsDays": 0,
			"OptionsMonths": 0
		},
		"TotalQuantityOrScope": {
			"Type": 2,
			"Currency": "EUR",
			"MinValue": 8500000.0,
			"MaxValue": 9500000.0
		},
		"TotalQuantity": [
			"Sopimus tehdään toistaiseksi voimassaolevana. Hankinnan ennakoitu ja sitomaton arvio on laskettu 48 kuulkauden hankinta-arvion perusteella. "
		],
		"Renewals": {}
	},
	"IsCorrigendum": true,
	"ContractAwardsDefence": null
}

**Expected behavior**
Proper error or publishing of notice

**API response**
Response status
500 Internal Server Error
Response latency
1237 ms
Response content

Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Thu, 19 Mar 2020 14:35:17 GMT
Content-Length: 0

**Additional context**

**Comment by jannef** [comment]
There seems to be an issue generating changes for AdditionalCpvCodes. Null safety is not properly implemented in the changes factory for defense notices. There is no workaround you can use, as the null is encountered on the previous notice, not the currently posted one.

**Comment by arinurkkala** [comment]
Should be fixed now
