### ISSUE TITLE
Date/Time sent in UTC is not adjusted to Finnish time zone in HILMA's UI

### ISSUE THREAD

**Issue by jlouvrier** [Hankintailmoitukset/hilma-api#220]
See: https://www.hankintailmoitukset.fi/fi/public/procedure/7193/enotice/9391/lot/LOT-0000

<img width="1725" alt="Screenshot 2024-05-23 at 18 12 02" src="https://github.com/Hankintailmoitukset/hilma-api/assets/64864592/f09f2b5c-f856-4b84-9973-e3980dfeaefb">

Dates sent by us in UTC in XML:
<cac:PlannedPeriod>
        <cbc:StartDate>2021-04-28+00:00</cbc:StartDate>
        <cbc:EndDate>2028-06-29+00:00</cbc:EndDate>
      </cac:PlannedPeriod>

Updated (27.5.2024) Full XML communicated to Jake by email on Friday.

**Comment by solita-reddy** [comment]
Hey Julien, I've opened a ticket for this internally and we will continue to investigate. I noticed that the XML you sent is mal-formatted and I'm having troubles viewing it, would you kindly email me a copy of the XML to jake.reddy@solita.fi.

**Comment by solita-reddy** [comment]
@jlouvrier Sorry for the delay. I'm a little confused on the issue you are reporting, the date you are sending is being displayed correctly. If you wish for the date to be displayed in EEST you would need to handle it internally and send that format to us.

**Comment by jlouvrier** [comment]
@solita-reddy 

I tried to remove the time from one of our XML and it does not pass HILMA's validation. Please consider the regex for BT-537 for example.

**Sending this, note that I removed the time after the date**
<cac:PlannedPeriod>
        <cbc:StartDate>2024-06-19</cbc:StartDate>
        <cbc:EndDate>2024-08-30</cbc:EndDate>
      </cac:PlannedPeriod>

**Getting following validation error**
<svrl:failed-assert id=\"BR-BT-00537-0104\" location=\"/cn:ContractNotice/cac:ProcurementProjectLot/cac:ProcurementProject/cac:PlannedPeriod/cbc:EndDate\" test=\"matches(normalize-space(.),'^((((1[6-9]|[2-9]\\d)\\d{2})-(((0[13578]|1[02]))-31|((0[13-9]|1[0-2])-(29|30))))|(((((1[6-9]|[2-9]\\d)(0[48]|[2468][048]|[13579][26])|((16|[2468][048]|[3579][26])00)))-02-29))|(((1[6-9]|[2-9]\\d)\\d{2})-((0[1-9])|(1[0-2]))-(0[1-9]|1\\d|2[0-8])))(Z|[-+]((0[0-9]|1[0-3]):([03]0|45)|14:00))$')\" role=\"ERROR\">\n    <svrl:text>'Duration end date' (BT-537-Lot) must match the following pattern: Date</svrl:text>\n 

This is in line with what I tried to explain earlier today in the API meeting: time is expected.

**Comment by solita-reddy** [comment]
The section of the XML you are referencing does not have a time, it is only date. 

```
      <cac:PlannedPeriod>
        <cbc:StartDate>2021-04-28+00:00</cbc:StartDate>
        <cbc:EndDate>2028-06-29+00:00</cbc:EndDate>
      </cac:PlannedPeriod>
```

The '+00:00' is a reference to the time zone, +00:00 is UTC +03:00 is EEST.

you can find more information on XML date formats here: https://www.w3schools.com/xml/schema_dtypes_date.asp

If including a StartTime and EndTime into the PlannedPeriod is something you require we can discus adding in a future feature release.

**Comment by jlouvrier** [comment]
@solita-reddy We do not have such a request. Hansel users do not understand why the date displayed in HILMA does not correspond to the date they chose in Mercell. You could convert our date to EEST or indicate that the date is UTC and it would solve the problem.

**Comment by solita-reddy** [comment]
Hey Julian, I don't think converting the date is a possibility. We can display the time zone next to the date, yes. Petteri will schedule us a teams meeting regarding this issue.

**Comment by MaxKholoshnyi** [comment]
> The section of the XML you are referencing does not have a time, it is only date.
> 
> ```
>       <cac:PlannedPeriod>
>         <cbc:StartDate>2021-04-28+00:00</cbc:StartDate>
>         <cbc:EndDate>2028-06-29+00:00</cbc:EndDate>
>       </cac:PlannedPeriod>
> ```
> 
> The '+00:00' is a reference to the time zone, +00:00 is UTC +03:00 is EEST.
> 
> you can find more information on XML date formats here: https://www.w3schools.com/xml/schema_dtypes_date.asp
> 
> If including a StartTime and EndTime into the PlannedPeriod is something you require we can discus adding in a future feature release.

Do I understand correctly that we shall send the date with "Z" instead of time zone?
   <cac:PlannedPeriod>
        <cbc:StartDate>2021-04-28Z</cbc:StartDate>
        <cbc:EndDate>2028-06-29Z</cbc:EndDate>
      </cac:PlannedPeriod>

**Comment by solita-reddy** [comment]
Yes that is correct, using either 'Z' or '+00:00' will send the date it UTC time zone.

**Comment by solita-reddy** [comment]
If there is nothing else needed could you go ahead and close the ticket :)

**Comment by solita-reddy** [comment]
Closed due to inactivity.
