### ISSUE TITLE
Test environment - National notice can't be published

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#221]
National notice can't be published in test environment

**To Reproduce**
- User creates a new national notice through DRAFT API
- User fills all mandatory fields
- User tries to publish the notice
- System gives a error and the user is unable to publish the notice
https://testi.hankintailmoitukset.fi/fi/procurement/115230/procedure/122836/nationalcontract/122836/project
![image](https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/a9084152-5fb3-4c99-8248-f0514b6630e5)

Other notices with similar data can be published.

**Expected behavior**
The notice can be published

**Comment by solita-reddy** [comment]
Hey @OlliSurakka we have flagged this issue internally and are currently investigating.

**Comment by OlliSurakka** [comment]
At the moment we cannot post the copy of the XML. 

In the UI, there is "undefined" markings with the "Arvioitu kokonaisarvo"-field?
![Uploading image.png…]()

**Comment by solita-reddy** [comment]
Sorry for the delayed reply. The data looks good on our end, the "undefined" should not be showing up as the currency value in present (EUR). It seems that you are having a similar issue with issue #223. Could we arrange a teams chat and go through both these issues? I'm leaving for vacation today, I'll hand this over to Diego to arrange.
