### ISSUE TITLE
Notice TED EF07 publication is not possible (validation error) / test environment

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#222]
Notice type: PRIOR INFORMATION NOTICE USED TO SHORTEN TIME LIMITS FOR RECEIPT OF TENDERS – GENERAL DIRECTIVE (TED EF07

The notice type is created through draft API. Test environment in Hilma.
The publication is not possible because of validation error in publication page.

We ask for rapid response/fix to this.

Example::
 
Error "Elementti 'cac:ProcurementProjectLot[cbc:ID/@schemeName='Part']' ei ole sallittu tässä polussa: /*"
--> not clear to us, because we sent:
                "id": {
                    "schemeName": "lot",
                    "value": "LOT-0000"
                },
 
 
Example in test Hilma: https://testi.hankintailmoitukset.fi/fi/preview/procedure/18731/enotice/20848/
[esimerkkiPayload.txt](https://github.com/user-attachments/files/16049643/esimerkkiPayload.txt)

**Comment by OlliSurakka** [comment]
Add to earlier post:

Also notice type EF04 - same kind of error about partID is blocking the notice publication:
<img width="891" alt="2024-07-01_13-15-33" src="https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/22a03ae6-b795-4160-95af-ea35a523c190">

https://testi.hankintailmoitukset.fi/fi/preview/procedure/18732/enotice/20849/

**Comment by solita-reddy** [comment]
We are looking into this. We've reproduced this issue and we'll get back to you asap.

**Comment by solita-reddy** [comment]
We identified two issues.
- EF07: We discovered a bug in our sanitization logic that was parsing procurementProjectLot Scheme's to invalid format. We are currently testing a fix and will inform you once it reaches the TEST env
- EF04: We checked the data for `Notice 20849`. The data in the ID object for the procurementProject is invalid. The value you submitted is `PAR-3828232195312164` when it should be formatted as `PAR-000X`

We are currently investigating whether there is a need to sanitize the ID object into incremental values, as we currently use the values provided in the payload which has caused this issue.

**Comment by solita-reddy** [comment]
The changes for EF07 are now in the TEST environment.

**Comment by OlliSurakka** [comment]
Tested EF07 and EF04, fix works and validation works.

**Comment by solita-reddy** [comment]
If there is nothing else needed could you go ahead and close the ticket :)

**Comment by solita-reddy** [comment]
Closed due to inactivity.
