### ISSUE TITLE
Notice error when saving (test environment)

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#223]
**Describe the bug**
Notice draft gives an error when saving the data for the first time

**To Reproduce**
1. User creates a notice draft through draft API.
2. User tries to save data in Hilma UI
3. An error occurs in Ilmoituksen yleiset tiedot tab and Ilmoituksen tiedot tab. (video enclosed)

**Expected behavior**
No errors occur when saving the data.

https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/82d51195-d121-4e7a-9e78-8713cf696adc

**Comment by solita-diego** [comment]
Hi @OlliSurakka,

We haven't been able to reproduce this yet on our end. Does this occur every time for you when you try to save data in Hilma or did it happen in this single case only?

**Comment by OlliSurakka** [comment]
This happens only when the user: 

- open the draft notice
- data in Ilmoituksen yleiset tiedot -tab is saved for the first time (no green marks in front of fold)

**Comment by solita-reddy** [comment]
Closed due to inactivity.
