### ISSUE TITLE
Notice validation error NationalIdentifier not found

### ISSUE THREAD

**Issue by MercellPeter** [Hankintailmoitukset/hilma-api#224]
Hi,

We have got a notice error:

{"type":"Hilma API Error","title":"Validation error","status":400,"detail":"Content validation failed, see errors and tedValidationResult for details","errors":{"NationalIdentifier":["Organisation FI02012566 was not found in Hilma or YTJ."]},"traceId":"39bd0ebfa642284f90afdc721e5298e4"}

Have you made any changes to the validation so Finnish VAT is not allowed to be used as National identifier anymore?

**Comment by solita-reddy** [comment]
We haven't made any changes, what endpoint are you using? so we can investigate.

**Comment by jlouvrier** [comment]
Hi! We are using HILMA write API. This is the very first time we have experienced an issue with Finnish VAT numbers. Any update?

**Comment by solita-reddy** [comment]
Based on the error message you provided above, you are either trying to create a procedure or create a procurement plan? Neither of these end point accept VAT number as a value for "NationalIdentifier" or "BuyerOrganization:CompanyID".

Some of our endpoints do accept VAT numbers namely when dealing with EForm/ENotices. 

Could there be some confusion regarding where VAT numbers have been in use, as we have no made any changes to these endpoints.

**Comment by solita-reddy** [comment]
Closed due to inactivity.
