### ISSUE TITLE
[Production] Weird error during publication

### ISSUE THREAD

**Issue by stefan-sluijter-mercell** [Hankintailmoitukset/hilma-api#225]
Hello Hilma,

I'm investigation for Mercell.
During publication we get a weird error, that doesn't tell us anything.
Could you investigate and tell us if we should try again?

` {
      "status": "NOT_PUBLISHED",
      "createdAt": "2024-06-14T14:43:58.892Z",
      "executedAt": "2024-06-14T14:43:58.892Z",
      "errorMessage": "<div style=\"display: block; margin: auto;  width: 600px; height: 500px; text-align: center; font-family: 'Courier', cursive, sans-serif;\"><h1 style=\"color: 747474\">:( Application Error</h1><p style=\"color:#666\">If you are the application administrator, you can access the <a style=\"color: grey\"href=\"https://hns-hilma-prod-api-wapp.scm.azurewebsites.net/detectors\">diagnostic resources</a>.</div>\n"
}`

Environment: Production
Reproduce: Error is during publication.
Notice ID: 2f05f510-210a-43a9-b930-eddc8907fd72
CustomizationId": "eforms-sdk-1.10",

Kind regards,

Stefan

**Comment by solita-reddy** [comment]
Hey Stefan,

Base on the above information I cannot definitively say what the issue is.
If you require further investigation of this issue could you please provide the information as defined in our bug report template found here: https://github.com/Hankintailmoitukset/hilma-api/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Kind regards,
Jake

**Comment by stefan-sluijter-mercell** [comment]
@solita-reddy 

It has been solved by simply resubmitting the notice.
This error message on your end suggested you had a temporary outage during that time.

In my honest opinion. The Notice ID, the time of execution and the SDK version should be enough for you to determine the problem in the future.
Or do you not keep any logs of requests coming in?

KR,

Stefan

**Comment by Hallo** [comment]
Hey @stefan-sluijter-mercell 

it doesn't take a lot from a reporter to add the needed information in the bug report, as there is the template ready when one is creating a new issue. 

The template is designed to streamline the process and ensure we have all the necessary details right from the start. While the information you’ve provided might be sufficient in some instances, it often requires additional effort from our team to gather the full context of the issue.

We kindly request your assistance in this matter. By filling out the template when you create a new issue, you’re helping us understand the problem more quickly and accurately.

So I hope that in future you could help us to help you. 

Best regards, Ville

**Comment by stefan-sluijter-mercell** [comment]
Hi Vile,

Creating a ticket is a last resort for us.
Being a developer I like to empower my clients with meaningful error messages.
Sadly the error message we received was not up to those standards.

Next time I will use the template to create my ticket.
Hopefully, I won't have to as the error messages will provide more information. 

KR,

Stefan
