### ISSUE TITLE
Field TED BT-501 disabled in draft API notice

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#228]
**Describe the bug**
Field: Organisaation tunniste * Pakollinen TED BT-501 is disabled in the notice created through draft API. Notice cannot be published.

**To Reproduce**
Hilma test environment
The user creates a notice draft ef16 through Draft API.
The user has brought organizations to "Mukana oleva organisaatio" fold.
The data brought is: organization name (BT-500) and country (BT-514)
The user tries to fill mandatory fields in the notice.
The field BT-501 "Organisaation tunniste" is empty and disabled in the notice.
The user can not publish the notice because mandatory field is missing.
![image](https://github.com/user-attachments/assets/ce11e0f0-b2a7-4b4b-8bdd-9bdcb6539920)

**Expected behavior**
The user can fill data field BT-501 "Organisaation tunniste" and publish the notice.

**Additional context**
The bug did not occur in similar test case 2.10.2024.

**Comment by solita-reddy** [comment]
Thank you for raising this to our attention, we are currently testing some changes to BT-501 as it has been causing quite a few issues. We will modify our solution to take into consideration this use case. We'll get back to you shortly.
