### ISSUE TITLE
Notice shows Information about reserved contracts even though none selected

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#24]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Notice send with API has restrictedToShelteredWorkshop as false but value is shown as if it were true. Even ets=1 shows it as false. Nevertheless "Participation in the procedure is reserved to organisations pursuing a public service mission and fulfilling the conditions set in Article 77(2) of Directive 2014/24/EU" is shown on notice.

**To Reproduce**
GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_9862?includeNotice=true HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key: foobar

**Expected behavior**
JSON received from API has "restrictedToShelteredWorkshop": false, then https://www.hankintailmoitukset.fi/en/public/procurement/33066/notice/41921/participation should not show "Participation in the procedure is reserved to organisations pursuing a public service mission and fulfilling the conditions set in Article 77(2) of Directive 2014/24/EU" as selected.

**API response**
Response status
200 OK
Response latency
148 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Tue, 24 Mar 2020 14:58:59 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-041921",
  "noticeOjsNumber": "2020/S 056-133044",
  "creationDate": "2020-03-18T06:47:44.2291536",
  "modificationDate": "2020-03-19T08:00:31.0469648",
  "hilmaStatus": 2,
  "hilmaPublicationDate": "2020-03-19T08:00:31.0454873",
  "etsIdentifier": "production_9862",
  "organisationId": "0210469-8",
  "projectId": 33066,
  "noticeId": 41921,
  "tedPublicationInfo": {
    "documentNumber": "2020/S 056-133044",
    "links": {
      "fi": "http://ted.europa.eu/udl?uri=TED:NOTICE:133044-2020:TEXT:FI:HTML"
    },
    "orderNumberInSeries": "056",
    "publicationDate": "2020-03-19T08:00:00",
    "publicationRequestedDate": "2020-03-18T06:47:44.9366124"
  },
  "tedStatus": 4,
  "tedSubmissionId": "20200318-005077",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": []
  }],
  "notice": {
    "id": 41921,
    "legalBasis": "32014L0024",
    "communicationInformation": {
      "procurementDocumentsAvailable": 2,
      "procurementDocumentsUrl": "https://tarjouspalvelu.fi/justia?id=289238&tpk=49c60483-15d9-46a3-b6cd-4e30da64315e",
      "additionalInformation": 2,
      "additionalInformationAddress": {
        "officialName": "Justia Oy",
        "nutsCodes": ["FI1B1"],
        "postalAddress": {
          "town": "Espoo",
          "country": "FI"
        },
        "email": "kilpailutus@justia.fi",
        "mainUrl": "https://www.justia.fi",
        "validationState": 0
      },
      "otherAddressForProcurementDocuments": {
        "nutsCodes": [],
        "validationState": 0
      },
      "sendTendersOption": 1,
      "electronicAddressToSendTenders": "https://tarjouspalvelu.fi/justia?id=289238&tpk=49c60483-15d9-46a3-b6cd-4e30da64315e",
      "addressToSendTenders": {
        "nutsCodes": [],
        "validationState": 0
      },
      "electronicCommunicationRequiresSpecialTools": false,
      "documentsEntirelyInHilma": false,
      "specsAndAdditionalDocuments": 0,
      "validationState": 0
    },
    "complementaryInformation": {
      "isRecurringProcurement": false,
      "estimatedTimingForFurtherNoticePublish": [],
      "electronicOrderingUsed": false,
      "electronicInvoicingUsed": false,
      "electronicPaymentUsed": false,
      "additionalInformation": [],
      "validationState": 0
    },
    "conditionsInformation": {
      "professionalSuitabilityRequirements": ["- Ulkomainen tarjoaja täyttää laissa ulkomaisista vakuutusyhtiöistä (398/1995)", "asetetut edellytykset ja muut määräykset.", "- Suomalainen tarjoaja täyttää vakuutusyhtiölaissa (521/2008) asetetut edellytykset ja muut määräykset.", "- Tarjoajalla on voimassa oleva toimilupa vakuutuspalvelujen tarjoamiseen ja", "tarjoaja on rekisteröity kaupparekisteriin sijoittumismaansa lainsäädännön", "mukaisesti.", "- Tarjoaja on merkitty ennakkoperintärekisteriin sekä työnantajarekisteriin ja tarjoaja on huolehtinut sijoittumismaansa lainsäädännön mukaisten verojen,", "sosiaaliturvamaksujen ja eläkevakuutusmaksujen maksamisesta.", "- Tarjoajaa ei koske julkista hankinnoista annetuin lain (1397/2016) 80 §:n tai 81§:n poissulkemisperusteet.", "- Tarjoajan on esitettävä selvityksenä soveltuvuusedellytysten täyttämisestä EU asetuksen 2016/7 mukaisella ESPD-asiakirjalla. "],
      "economicCriteriaToParticipate": true,
      "technicalCriteriaToParticipate": true,
      "restrictedToShelteredWorkshop": false,
      "restrictedToShelteredProgram": false,
      "reservedOrganisationServiceMission": true,
      "executionOfServiceIsReservedForProfession": true,
      "referenceToRelevantLawRegulationOrProvision": ["Vakuutusyhtiölaki 521/2008", "Laki ulkomaisista vakuutusyhtiöistä 398/1995"],
      "participationIsReservedForProfession": false,
      "obligationToIndicateNamesAndProfessionalQualifications": false,
      "validationState": 0
    },
    "conditionsInformationDefence": {
      "restrictedToShelteredWorkshops": false,
      "restrictedToShelteredProgrammes": false,
      "restrictedToParticularProfession": false,
      "staffResponsibleForExecution": false,
      "validationState": 0
    },
    "conditionsInformationNational": {
      "validationState": 0,
      "reservedForShelteredWorkshopOrProgram": false
    },
    "contactPerson": {
      "email": "kilpailutus@justia.fi"
    },
    "estimatedValue": {
      "type": 0
    },
    "estimatedValueCalculationMethod": [],
    "links": [],
    "lotsInfo": {
      "divisionLots": false,
      "lotsSubmittedFor": 0,
      "lotsSubmittedForQuantity": 0,
      "lotsMaxAwarded": false,
      "lotsMaxAwardedQuantity": 0,
      "lotCombinationPossible": false,
      "validationState": 0
    },
    "mainCpvCode": {
      "code": "66000000",
      "name": "Rahoitus- ja vakuutuspalvelut",
      "vocCodes": []
    },
    "objectDescriptions": [{
      "mainCpvCode": {
        "code": "66000000",
        "name": "Rahoitus- ja vakuutuspalvelut",
        "vocCodes": []
      },
      "additionalCpvCodes": [],
      "nutsCodes": ["FI1D7"],
      "descrProcurement": ["Vahinkovakuutuspalvelujen hankinta sisältäen työtapaturma-, ryhmätapaturma-, matka-, vastuu- ja oikeusturva-, omaisuus-, keskeytys-, rakennus- ja asennustyö-, metsä- ja ajoneuvovakuutukset sekä niihin liittyvät palvelut."],
      "disagreeAwardCriteriaToBePublished": false,
      "awardCriteria": {
        "criterionTypes": 8,
        "qualityCriteria": [],
        "costCriteria": [],
        "priceCriterion": {},
        "criterion": [],
        "criteriaStatedInProcurementDocuments": false
      },
      "estimatedValue": {
        "type": 0
      },
      "timeFrame": {
        "type": 3,
        "beginDate": "2020-08-01T00:00:00",
        "canBeRenewed": true,
        "renewalDescription": ["Toistaiseksi voimassa oleva sopimus  "]
      },
      "candidateNumberRestrictions": {
        "envisagedNumber": 0,
        "envisagedMinimumNumber": 0,
        "envisagedMaximumNumber": 0,
        "selected": 0
      },
      "optionsAndVariants": {
        "variantsWillBeAccepted": false,
        "partialOffersWillBeAccepted": false,
        "options": false,
        "optionType": 0,
        "optionsDays": 0,
        "optionsMonths": 0
      },
      "tendersMustBePresentedAsElectronicCatalogs": false,
      "euFunds": {
        "procurementRelatedToEuProgram": false
      },
      "awardContract": {
        "contractAwarded": 1,
        "noAwardedContract": {
          "failureReason": 0,
          "originalNoticeSentVia": 0
        },
        "awardedContract": {
          "conclusionDate": "2020-08-01T00:00:00",
          "contractTitle": "Keminmaan kunta, vahinkovakuutuspalveluiden kilpailutus ",
          "numberOfTenders": {
            "disagreeTenderInformationToBePublished": false,
            "total": 0,
            "electronic": 0
          },
          "disagreeContractorInformationToBePublished": false,
          "contractors": [],
          "initialEstimatedValueOfContract": {},
          "finalTotalValue": {
            "type": 0
          },
          "likelyToBeSubcontracted": false,
          "valueOfSubcontract": {},
          "notPublicFields": {
            "communityOrigin": false,
            "nonCommunityOrigin": true,
            "countries": [],
            "awardedToTendererWithVariant": false,
            "abnormallyLowTendersExcluded": false
          }
        }
      },
      "validationState": 0
    }],
    "organisation": {
      "information": {
        "officialName": "Keminmaan kunta",
        "nationalRegistrationNumber": "0210469-8",
        "nutsCodes": ["FI1D7"],
        "postalAddress": {
          "streetAddress": "Rantatie 21",
          "town": "Keminmaa",
          "country": "FI"
        },
        "email": "kilpailutus@justia.fi",
        "mainUrl": "https://www.keminmaa.fi/",
        "validationState": 0
      },
      "contractingAuthorityType": 4,
      "contractingType": 0,
      "mainActivity": 1,
      "mainActivityUtilities": 0
    },
    "noticeOjsNumber": "2020/S 056-133044",
    "project": {
      "id": 33066,
      "contractType": 2,
      "title": "Keminmaan kunta, vahinkovakuutuspalveluiden kilpailutus ",
      "procurementCategory": 1,
      "jointProcurement": false,
      "procurementLaw": [],
      "centralPurchasing": false,
      "coPurchasers": [],
      "defenceWorks": 0,
      "defenceSupplies": 0,
      "agricultureWorks": 0
    },
    "shortDescription": ["Vahinkovakuutukset ja niihin liittyvät palvelut", "", ""],
    "type": 200,
    "tenderingInformation": {
      "tendersOrRequestsToParticipateDueDateTime": "2020-05-15T14:00:00",
      "languages": ["FI"],
      "tendersMustBeValidOption": 1,
      "tendersMustBeValidUntil": "2020-12-31T00:00:00",
      "tenderOpeningConditions": {
        "openingDateAndTime": "2020-05-15T14:15:00",
        "informationAboutAuthorisedPersons": ["Avaustilaisuus ei ole julkinen "]
      },
      "defence": {
        "previousPublicationExists": false,
        "hasPreviousContractNoticeOjsNumber": false,
        "hasPreviousExAnteOjsNumber": false,
        "payableDocuments": false,
        "languageType": 0,
        "languages": [],
        "otherLanguage": false
      },
      "estimatedExecutionTimeFrame": {
        "type": 3,
        "canBeRenewed": false
      },
      "validationState": 0
    },
    "rewardsAndJury": {
      "prizeAwarded": false,
      "serviceContractAwardedToWinner": false,
      "decisionOfTheJuryIsBinding": false,
      "validationState": 0
    },
    "resultsOfContest": {
      "contestWasTerminated": false,
      "noPrizeType": 0,
      "originalNoticeSentVia": 0,
      "participantsContemplated": 0,
      "participantsSme": 0,
      "participantsForeign": 0,
      "disagreeParticipantCountPublish": false,
      "disagreeWinnersPublish": false,
      "disagreeValuePublish": false,
      "validationState": 0
    },
    "language": "FI",
    "procedureInformation": {
      "procedureType": 1,
      "acceleratedProcedure": false,
      "contestType": 0,
      "frameworkAgreement": {
        "includesFrameworkAgreement": false,
        "includesConclusionOfFrameworkAgreement": false,
        "frameworkAgreementType": 0,
        "frameworkEnvisagedType": 0,
        "includesDynamicPurchasingSystem": false,
        "dynamicPurchasingSystemInvolvesAdditionalPurchasers": false,
        "dynamicPurchasingSystemWasTerminated": false,
        "estimatedTotalValue": {
          "type": 0
        },
        "duration": {
          "type": 0,
          "canBeRenewed": false
        }
      },
      "reductionRecourseToReduceNumberOfSolutions": false,
      "reserveRightToAwardWithoutNegotiations": false,
      "electronicAuctionWillBeUsed": false,
      "procurementGovernedByGPA": true,
      "disagreeCriteriaForEvaluationOfProjectsPublish": false,
      "validationState": 0
    },
    "proceduresForReview": {
      "reviewBody": {
        "officialName": "Markkinaoikeus",
        "nutsCodes": [],
        "postalAddress": {
          "streetAddress": "Radanrakentajantie 5",
          "postalCode": "00520",
          "town": "Helsinki",
          "country": "FI"
        },
        "telephoneNumber": "+358 295643300",
        "email": "markkinaoikeus@oikeus.fi",
        "mainUrl": "http://www.oikeus.fi/markkinaoikeus",
        "validationState": 0
      },
      "validationState": 0
    },
    "modifications": {
      "additionalCpvCodes": [],
      "nutsCodes": [],
      "timeFrame": {
        "type": 0,
        "canBeRenewed": false
      },
      "totalValue": {},
      "awardedToGroupOfEconomicOperators": false,
      "contractors": [],
      "reason": 0,
      "increaseBeforeModifications": {},
      "increaseAfterModifications": {},
      "validationState": 0
    },
    "defence": {
      "nutsCodes": [],
      "frameworkAgreement": {
        "includesFrameworkAgreement": false,
        "includesConclusionOfFrameworkAgreement": false,
        "frameworkAgreementType": 0,
        "frameworkEnvisagedType": 0,
        "includesDynamicPurchasingSystem": false,
        "dynamicPurchasingSystemInvolvesAdditionalPurchasers": false,
        "dynamicPurchasingSystemWasTerminated": false,
        "estimatedTotalValue": {
          "type": 0
        },
        "duration": {
          "type": 0,
          "canBeRenewed": false
        }
      },
      "subcontract": {
        "tendererHasToIndicateShare": false,
        "tendererHasToIndicateChange": false,
        "caMayOblige": false,
        "successfulTenderer": false,
        "successfulTendererToSpecify": false
      },
      "optionsAndVariants": {
        "variantsWillBeAccepted": false,
        "partialOffersWillBeAccepted": false,
        "options": false,
        "optionType": 0
      },
      "totalQuantityOrScope": {
        "type": 0
      },
      "renewals": {
        "canBeRenewed": false
      },
      "timeFrame": {
        "type": 0,
        "canBeRenewed": false
      }
    },
    "isCorrigendum": false,
    "isCancelled": false,
    "corrigendumAdditionalInformation": [],
    "contractAwardsDefence": [{
      "numberOfTenders": {
        "disagreeTenderInformationToBePublished": false,
        "total": 0
      },
      "contractor": {
        "nutsCodes": [],
        "postalAddress": {},
        "isSmallMediumEnterprise": false,
        "validationState": 0
      },
      "estimatedValue": {},
      "contractValueType": 0,
      "finalTotalValue": {},
      "lowestOffer": {},
      "highestOffer": {},
      "annualOrMonthlyValue": {
        "type": 0,
        "canBeRenewed": false
      },
      "likelyToBeSubcontracted": false,
      "valueOfSubcontract": {},
      "valueOfSubcontractNotKnown": false,
      "allOrCertainSubcontractsWillBeAwarded": false,
      "shareOfContractWillBeSubcontracted": false,
      "validationState": 0
    }]
  }
}

**Additional context**

**Comment by arinurkkala** [comment]
You have set reservedOrganisationServiceMission = true, to which this text is referring to.
