### ISSUE TITLE
F17 corrigendum rejected by TED for unclear reason

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#25]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
F17 corrigendum was rejected by TED but reason is unclear.

**To Reproduce**
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_12519?parentId=production_5813&projectId=31443  

{
	"LegalBasis": "32009L0081",
	"CommunicationInformation": {
		"AdditionalInformation": 1,
		"AdditionalInformationAddress": {
			"OfficialName": "Poliisihallitus",
			"NationalRegistrationNumber": "2288666-6",
			"NutsCodes": [],
			"PostalAddress": {
				"StreetAddress": "Asemapäällikönkatu 14",
				"PostalCode": "00521",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"Email": "hankinnat.poliisihallitus@poliisi.fi",
			"MainUrl": "http://www.poliisi.fi"
		},
		"SendTendersOption": 1,
		"ElectronicAddressToSendTenders": "https://hanki.tarjouspalvelu.fi/hanki?id=284430&tpk=ae2ebb8b-aca0-4b34-8042-09fec4412399",
		"ElectronicCommunicationRequiresSpecialTools": false
	},
	"ComplementaryInformation": {
		"IsRecurringProcurement": false,
		"Defence": {
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		}
	},
	"ConditionsInformationDefence": {
		"DepositsRequired": [],
		"FinancingConditions": [],
		"LegalFormTaken": [],
		"OtherParticularConditions": [],
		"PersonalSituationOfEconomicOperators": [
			"katso kohta Soveltuvuusvaatimukset"
		],
		"EconomicCriteriaOfEconomicOperators": [
			"katso kohta Soveltuvuusvaatimukset"
		],
		"TechnicalCriteriaOfEconomicOperatorsMinimum": [
			"katso kohta Soveltuvuusvaatimukset"
		],
		"RestrictedToShelteredWorkshops": false,
		"RestrictedToShelteredProgrammes": false,
		"RestrictedToParticularProfession": false,
		"StaffResponsibleForExecution": false
	},
	"ContactPerson": {
		"Email": "hankinnat.poliisihallitus@poliisi.fi"
	},
	"Links": [
		{
			"Url": "https://www.supo.fi/turvallisuusselvitykset/henkiloturvallisuusselvitys"
		},
		{
			"Url": "https://www.supo.fi/instancedata/prime_product_julkaisu/intermin/embeds/supowwwstructure/75568_OHJE_henkiloturvallisuusselvityksen_tayttamiseen.pdf?9d630269e2fad688"
		},
		{
			"Url": "https://www.finlex.fi/fi/laki/ajantasa/2011/20111531"
		}
	],
	"LotsInfo": {
		"DivisionLots": true,
		"QuantityOfLots": 3,
		"LotsSubmittedFor": 1,
		"LotsMaxAwarded": false
	},
	"MainCpvCode": {
		"Code": "35330000",
		"Name": "Ampumatarvikkeet",
		"VocCodes": []
	},
	"ObjectDescriptions": [
		{
			"Title": "Pistoolin, konepistoolin ja kiväärin patruunat",
			"LotNumber": "1",
			"MainCpvCode": {
				"Code": "35330000",
				"Name": "Ampumatarvikkeet",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [],
			"DescrProcurement": [
				"Osa-alueen tarkempi erittely erillisenä toimitettavassa liitteessä. Katso tarkemmin kohta Muut tiedot - Tarjouksen/hakemuksen lähettäminen"
			],
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": null,
			"EstimatedValue": null,
			"TimeFrame": null,
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": null,
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		},
		{
			"Title": "Simulaatiopatruunat",
			"LotNumber": "2",
			"MainCpvCode": {
				"Code": "35330000",
				"Name": "Ampumatarvikkeet",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [],
			"DescrProcurement": [
				"Osa-alueen tarkempi erittely erillisenä toimitettavassa liitteessä. Katso tarkemmin kohta Muut tiedot - Tarjouksen/hakemuksen lähettäminen"
			],
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": null,
			"EstimatedValue": null,
			"TimeFrame": null,
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": null,
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		},
		{
			"Title": "Haulikon patruunat",
			"LotNumber": "3",
			"MainCpvCode": {
				"Code": "35330000",
				"Name": "Ampumatarvikkeet",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [],
			"DescrProcurement": [
				"Osa-alueen tarkempi erittely erillisenä toimitettavassa liitteessä. Katso tarkemmin kohta Muut tiedot - Tarjouksen/hakemuksen lähettäminen"
			],
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": null,
			"EstimatedValue": null,
			"TimeFrame": null,
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": null,
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		}
	],
	"Organisation": {
		"Information": {
			"OfficialName": "Poliisihallitus",
			"NationalRegistrationNumber": "2288666-6",
			"NutsCodes": [],
			"PostalAddress": {
				"StreetAddress": "Asemapäällikönkatu 14",
				"PostalCode": "00521",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"Email": "hankinnat.poliisihallitus@poliisi.fi",
			"MainUrl": "http://www.poliisi.fi"
		},
		"ContractingAuthorityType": 2,
		"MainActivity": 4
	},
	"Project": {
		"Id": 31443,
		"ContractType": 1,
		"Title": "KORJAUSILMOITUS: Patruunat (korjausilmoitus)",
		"ProcurementCategory": 2,
		"JointProcurement": false,
		"DefenceSupplies": 1
	},
	"PublishToTed": false,
	"ShortDescription": [
		"Hankinnan kohteena on patruunat poliisin, Suojelupoliisin, Rajavartiolaitoksen, Tullin ja Rikosseuraamuslaitoksen käyttöön",
		"",
		"HUOM! TÄMÄ ILMOITUS ON KORJAUSILMOITUS 11.12.2019 JULKAISTUUN HANKINTAILMOITUKSEEN 2019-025368 / 2019/S 239-587823. ",
		"HILMA-portaalissa ilmenneiden tietoteknisten ongelmien vuoksi hankintayksikkö on pakotettu julkaisemaan korjausilmoituksen kokonaan uudella hankintaimoituksella. Tällä ilmoituksella ei aloiteta uutta hankintamenettelyä. ",
		"",
		"Osallistumishakemukset tulee laatia tässä korjausilmoituksessa annettujen tietojen perusteella.",
		"",
		"Yritysten, jotka ovat jo lähettäneet hankintayksikölle Kohdassa Muut tiedot - tarjouksen lähettäminen pyydetyt dokumentit ei tarvitse lähettää niitä uudelleen. "
	],
	"Type": 1700,
	"TenderingInformation": {
		"TendersOrRequestsToParticipateDueDateTime": "2020-05-04T14:00:00",
		"TenderOpeningConditions": {},
		"Defence": {
			"PreviousPublicationExists": false,
			"PayableDocuments": false,
			"LanguageType": 2,
			"Languages": [
				"FI"
			],
			"OtherLanguage": false
		}
	},
	"Language": "FI",
	"ProcedureInformation": {
		"ProcedureType": 2,
		"ElectronicAuctionWillBeUsed": false,
		"Defence": {
			"CandidateNumberRestrictions": {},
			"AwardCriteria": {
				"CriterionTypes": 2,
				"EconomicCriteriaTypes": 8
			}
		}
	},
	"ProceduresForReview": {
		"ReviewBody": {
			"OfficialName": "Markkinaoikeus",
			"NutsCodes": [],
			"PostalAddress": {
				"StreetAddress": "Radanrakentajantie 5",
				"PostalCode": "00520",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"TelephoneNumber": "+358 295643300",
			"Email": "markkinaoikeus@oikeus.fi",
			"MainUrl": "http://www.oikeus.fi/markkinaoikeus"
		}
	},
	"Defence": {
		"NutsCodes": [],
		"Subcontract": {
			"TendererHasToIndicateShare": true,
			"TendererHasToIndicateChange": true,
			"CaMayOblige": false,
			"SuccessfulTenderer": false,
			"SuccessfulTendererMin": 0.0,
			"SuccessfulTendererMax": 0.0,
			"SuccessfulTendererToSpecify": true
		},
		"OptionsAndVariants": {
			"VariantsWillBeAccepted": false,
			"Options": false,
			"OptionType": 0,
			"OptionsDays": 0,
			"OptionsMonths": 0
		},
		"TotalQuantityOrScope": {
			"Type": 2,
			"Currency": "EUR",
			"MinValue": 8500000.0,
			"MaxValue": 9500000.0
		},
		"TotalQuantity": [
			"Sopimus tehdään toistaiseksi voimassaolevana. Hankinnan ennakoitu ja sitomaton arvio on laskettu 48 kuulkauden hankinta-arvion perusteella. "
		],
		"Renewals": {}
	},
	"IsCorrigendum": true,
	"ContractAwardsDefence": null
}

**Expected behavior**
If there is something wrong in the notice we expect to get info about what that is.

**API response**
{"noticeNumber":"2020-042380","creationDate":"2020-03-24T11:19:00.2514666Z","modificationDate":"2020-03-24T11:19:00.5122357Z","hilmaStatus":4,"etsIdentifier":"production_12519","organisationId":"2288666-6","projectId":31443,"noticeId":42380,"tedStatus":1,"tedValidationReport":[]}

**Additional context**
As this is rejected by TED the original response is not too informative. Now if you do GET for notice this is result we get

GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_12519?includeNotice=False HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key: foo

Response status
200 OK
Response latency
221 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Thu, 26 Mar 2020 10:21:27 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-042380",
  "creationDate": "2020-03-24T11:19:00.2514666",
  "modificationDate": "2020-03-25T11:55:01.5933836",
  "hilmaStatus": 1,
  "etsIdentifier": "production_12519",
  "organisationId": "2288666-6",
  "projectId": 31443,
  "noticeId": 42380,
  "tedStatus": 7,
  "tedSubmissionId": "20200324-005678",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": [{
      "name": "R108",
      "valid": false,
      "severity": "INFO",
      "message": "LOGIN[@CLASS='B'], CUSTOMER_LOGIN='TEDE0MUT': CUSTOMER_LOGIN is mandatory and reserved for eSender from the D class."
    }]
  }]
}

**Comment by arinurkkala** [comment]
There is a bug in Hilma, where the message login part is sent with the wrong class. Fix should be inbound ASAP.

**Comment by cloudia-jt** [comment]
Now we have TED rejecting F02 notice without clear reason.
F02 etsIdentifier production_13312

{
  "noticeNumber": "2020-042767",
  "creationDate": "2020-03-30T07:40:30.6330791",
  "modificationDate": "2020-03-30T10:06:37.6134919",
  "hilmaStatus": 1,
  "etsIdentifier": "production_13312",
  "organisationId": "0210469-8",
  "projectId": 33066,
  "noticeId": 42767,
  "tedStatus": 7,
  "tedSubmissionId": "20200330-005248",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": []
  }]
}

**Comment by cloudia-jt** [comment]
Could we hurry this as production_13312 is on quite tight schedule.

**Comment by arinurkkala** [comment]
Hard to say why the F02 is failing. It would require another issue that should be solved separately.

As for the F17, there are some extra mandatory parameters in class C login that are unclear (tried by guessing - didn't work). We sent email to TED requesting further information about this, but they haven't responded yet. 
Since you brought up the tight schedule, I will proceeding by 'doing whatever works'. Hopefully we can get a new hotfix release today.

**Comment by cloudia-jt** [comment]
Note that production_13312 is F02, not F17

**Comment by arinurkkala** [comment]
Yes, and the two have different outcomes. Can't say why F02 is invalid at this time. The response is very unclear.

**Comment by arinurkkala** [comment]
Now staging has a version, where F17 corrigendum will work. The final fix will come at a later point in time and hopefully not cause any issues.

**Comment by arinurkkala** [comment]
Production environment updated, should work now.

**Comment by cloudia-jt** [comment]
F02 solved too?

**Comment by arinurkkala** [comment]
No. Please create a separate issue for that or try resending?
