### ISSUE TITLE
Corrigendum error in staging

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#26]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Corrigendum fails in staging environment with only TED XML error.

**To Reproduce**
https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/devel_1018?parentId=devel_1016&projectId=23502

[request payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4387654/request.payload.txt)

**Expected behavior**
Corrigendum to be published

**API response**
Response status:
400 Bad Request

[response.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4387611/response.txt)

**Additional context**
Original published notice:
https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/devel_1016

[original payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4387646/original.payload.txt)

**Comment by arinurkkala** [comment]
Seems like a bug. Will fix this now

**Comment by arinurkkala** [comment]
Production environment updated, should work now.
