### ISSUE TITLE
F02 corrigendum rejected with by TED without clear reason

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#28]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
TED has rejected F02 corrigendum and reason is not clear.

**To Reproduce**
GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_13312?includeNotice=false HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key: foo

**Expected behavior**
If problem is in notice payload, we need clear info what is wrong. Otherwise notice should be published.

**API response**
Response status
200 OK
Response latency
39 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Tue, 31 Mar 2020 05:35:23 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-042767",
  "creationDate": "2020-03-30T07:40:30.6330791",
  "modificationDate": "2020-03-30T10:06:37.6134919",
  "hilmaStatus": 1,
  "etsIdentifier": "production_13312",
  "organisationId": "0210469-8",
  "projectId": 33066,
  "noticeId": 42767,
  "tedStatus": 7,
  "tedSubmissionId": "20200330-005248",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": []
  }]
}

**Additional context**
Original and corrigendum payloads:
[corrigendum.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4406983/corrigendum.txt)
[original.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4406984/original.txt)

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
Got this response from TED:

Submission Id | 20200330-005248
-- | --
Tiedot
Tiedot, joita haluatte muuttaa kohdassa III.1.5), eivät vastaa   TED-sivustolla (viite 2020/S 056-133044) julkaistun alkuperäisen ilmoituksen   tai minkään sen korjausilmoituksen tietoja. Oikaistava tieto -kohdassa   esitettävän muutettavan tekstin on vastattava täsmällisesti alkuperäisessä   ilmoituksessa julkaistua tekstiä. Olkaa hyvä ja toimittakaa korjausilmoitus,   jossa oikaistavat tiedot on ilmoitettu oikein. Kiitos.

So in your request, you had:
ReservedOrganisationServiceMission = true
and in the corrigendum you did not set it (defaults to false)

Thus the rejection. Could you please fix the field ReservedOrganisationServiceMission so it also comes in the corrigendum and resubmit?

**Comment by cloudia-jt** [comment]
That is precisely what there should be changed. ReservedOrganisationServiceMission never should have been in the original JSON file thus corrigendum to unset it.

**Comment by cloudia-jt** [comment]
"Oikaistava tieto -kohdassa esitettävän muutettavan tekstin on vastattava täsmällisesti alkuperäisessä ilmoituksessa julkaistua tekstiä" So Hilma did not generate TED XML correctly?

**Comment by arinurkkala** [comment]
https://www.hankintailmoitukset.fi/fi/documentation/200
The field isn't even on F02, so it isn't sent.
You should be using:
https://www.hankintailmoitukset.fi/fi/documentation/2100
Second problem is that ReservedOrganisationServiceMission has a specific MainCpvCode range in which it must be in:
            "75121000",
            "75122000",
            "75123000",
            "79622000",
            "79624000",
            "79625000",
            "80110000",
            "80300000",
            "80420000",
            "80430000",
            "80511000",
            "80520000",
            "80590000",
            "85000000",
            "92500000",
            "92600000",
            "98133000"

**Comment by cloudia-jt** [comment]
ReservedOrganisationServiceMission never should have been in the original JSON. So the aim of this corrigendum is remove that incorrect information.

**Comment by arinurkkala** [comment]
I have created a bug report and will discuss with our team about how to resolve this.

**Comment by cloudia-jt** [comment]
Pending deployment. So you found a way to resolve this?

**Comment by arinurkkala** [comment]
Yes, the public view takes the configs into consideration while displaying. There was a small bug in this, where the section was displayed if any config or bool for restrictedToShelteredWorkshop, restrictedToShelteredProgram or reservedOrganisationServiceMission were true. I fixed it by checking each field individually. (both config has to exist and value must be true)

https://www.hankintailmoitukset.fi/fi/public/procurement/33964/notice/41921/participation
will not display 'Information about reserved contracts' -section after the next hotfix release. So you do not have to create a corrigendum to this notice regarding reservedOrganisationServiceMission.

**Comment by tuomastolvanen** [comment]
The fix has been deployed to production
