### ISSUE TITLE
Notice waiting to be published since 16.1.2020

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#3]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Notice sent to hilma via PUT api stuck in waiting to be published limbo since 16.1.2020

**To Reproduce**
No idea if reproducable, we just need to get notice either published or rejected (if reason for that)
- API endpoint that the request was sent to
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_2273
- HTTP method
PUT

**Expected behavior**
Notice should have been published or rejected long time ago by now

**Additional context**
Info from GET endopint

GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_2273?includeNotice=False HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key: foo

response:
ragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Mon, 27 Jan 2020 09:20:52 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-036375",
  "creationDate": "2020-01-16T09:01:06.8228075",
  "modificationDate": "2020-01-16T09:01:07.2337972",
  "hilmaStatus": 4,
  "etsIdentifier": "etsidfixed_2273",
  "organisationId": "2454638-2",
  "projectId": 29240,
  "noticeId": 36375,
  "tedStatus": 1
}

**Comment by tuomastolvanen** [comment]
We have identified this to be a technical issue in ted publishing process. The fix for the issue is complete and the notice is now sent to ted to be published

**Comment by tuomastolvanen** [comment]
ADDRESS_CONTRACTING_BODY_ADDITIONAL/NATIONALID with value 'Liite 4': This value does not seem to be the national registration number, please verify the content.
