### ISSUE TITLE
F02 corrigendum TED validation fails on DATE_DISPATCH_ORIGINAL

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#30]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Can not publish corrigendum for F02 because hilma returns error TED XML error "The element 'COMPLEMENTARY_INFO' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has incomplete content. List of possible elements expected: 'DATE_DISPATCH_ORIGINAL' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'."

**To Reproduce**
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_13828?parentId=etsidfixed_12649&projectId=33387
Payload: [production_13828.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4419351/production_13828.txt)

**Expected behavior**
Corrigendum to be published without error.

**API response**
400 Bad Request
[production_13828_error.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4419376/production_13828_error.txt)

**Additional context**

**Comment by arinurkkala** [comment]
Fixes issue for this notice. You may resend the request.
There are a bunch of others that may have this issue and a fix for them all is pending production hotfix.
