### ISSUE TITLE
TED F03 for F02 that is part of DPS can not be published because of contractType mismatch

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#31]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
F03 can not be published for F02 that is part of DPS and has different contractType than the DPS notice.

**To Reproduce**
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_13787?parentId=2018-026384&projectId=26424
Payload: [etsidfixed_13787_payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4421250/etsidfixed_13787_payload.txt)

**Expected behavior**
F03 to be published without error

**API response**
`400 BadRequest
Updating procurement category, contract type is not allowed for published projects`

**Additional context**
Parent indeed is the DPS notice. F02 that this F03 is for is never published in Hilma/TED

**Comment by cloudia-jt** [comment]
I have to ask to hurry this please.

**Comment by rantati7** [comment]
This has to be tried - there are no rules for this from the Commission (TED). We will remove contractType matching - even though this does not make sense. In normal F03 the contractType should (logically) match with F02 as the object of the contract cannot change between contract notice and contract award notice.

**Comment by tuomastolvanen** [comment]
The changes has been deployed to production
