### ISSUE TITLE
MainActivityUtilities broken

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#32]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
MainActivityUtilities seems to have disappeared from the documentation. When doing F15 notice with buyer as "Contracting entity" instead of "Contracting authority" in https://koulutus.hankintailmoitukset.fi resulting json with ets=1 has both mainActivity and mainActivityUtilities as zero. Also when trying to publish F15 with "Contracting entity" TED XML error "The notice cannot be published to TED: The element 'CONTRACTING_BODY' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has incomplete content. List of possible elements expected: 'CA_TYPE, CA_TYPE_OTHER, CE_ACTIVITY, CE_ACTIVITY_OTHER' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'.
" is given.

**To Reproduce**
PUT https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/test_202004071013
[put_payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4442660/put_payload.txt)

**Expected behavior**
Not expecting error

**API response**
Response status
400 Bad Request
Response latency
343 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:60071d4c-cdb6-420c-9fe4-6e9d212ede47
Cache-Control: no-store, no-cache
Date: Tue, 07 Apr 2020 07:14:07 GMT
Content-Type: text/plain; charset=utf-8
`
The notice cannot be published to TED: The element 'CONTRACTING_BODY' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has incomplete content. List of possible elements expected: 'CA_TYPE, CA_TYPE_OTHER, CE_ACTIVITY, CE_ACTIVITY_OTHER' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'.
, TED message formed:
<FORM_SECTION xmlns="http://publications.europa.eu/resource/schema/ted/R2.0.9/reception">
  <F15_2014 LG="FI" CATEGORY="ORIGINAL" FORM="F15">
    <LEGAL_BASIS VALUE="32014L0023" />
    <CONTRACTING_BODY>
      <ADDRESS_CONTRACTING_BODY>
        <OFFICIALNAME>Demolan seudun hankintatoimi</OFFICIALNAME>
        <NATIONALID>1088146-2</NATIONALID>
        <ADDRESS>Postitusosoitekatu 1</ADDRESS>
        <TOWN>Joensuu</TOWN>
        <POSTAL_CODE>80100</POSTAL_CODE>
        <COUNTRY VALUE="FI" />
        <CONTACT_POINT>Jyri Turkia</CONTACT_POINT>
        <PHONE>+358 123456789</PHONE>
        <E_MAIL>jyri.turkia@cloudia.fi</E_MAIL>
        <n2016:NUTS CODE="FI" xmlns:n2016="http://publications.europa.eu/resource/schema/ted/2016/nuts" />
        <URL_GENERAL>http://www.demonilanseutu.fi/hankintatoimi</URL_GENERAL>
      </ADDRESS_CONTRACTING_BODY>
    </CONTRACTING_BODY>
    <OBJECT_CONTRACT>
      <TITLE>
        <P>Käyttöoikeussopimus</P>
      </TITLE>
      <CPV_MAIN>
        <CPV_CODE CODE="34511100" />
      </CPV_MAIN>
      <TYPE_CONTRACT CTYPE="WORKS" />
      <SHORT_DESCR>
        <P>Ffds</P>
      </SHORT_DESCR>
      <VAL_RANGE_TOTAL CURRENCY="EUR">
        <LOW>123123.0</LOW>
        <HIGH>132456.0</HIGH>
      </VAL_RANGE_TOTAL>
      <NO_LOT_DIVISION />
      <OBJECT_DESCR ITEM="1">
        <n2016:NUTS CODE="FI" xmlns:n2016="http://publications.europa.eu/resource/schema/ted/2016/nuts" />
        <SHORT_DESCR>
          <P>Ffds</P>
        </SHORT_DESCR>
        <NO_OPTIONS />
        <NO_EU_PROGR_RELATED />
      </OBJECT_DESCR>
    </OBJECT_CONTRACT>
    <PROCEDURE>
      <DIRECTIVE_2014_23_EU>
        <PT_AWARD_CONTRACT_WITHOUT_PUBLICATION>
          <D_ACCORDANCE_ARTICLE />
          <D_JUSTIFICATION>
            <P>fdsaasdf</P>
          </D_JUSTIFICATION>
        </PT_AWARD_CONTRACT_WITHOUT_PUBLICATION>
      </DIRECTIVE_2014_23_EU>
      <NO_CONTRACT_COVERED_GPA />
    </PROCEDURE>
    <AWARD_CONTRACT ITEM="1">
      <TITLE>
        <P>Käyttöoikeussopimus</P>
      </TITLE>
      <AWARDED_CONTRACT>
        <DATE_CONCLUSION_CONTRACT>2020-04-04</DATE_CONCLUSION_CONTRACT>
        <CONTRACTORS>
          <NO_AWARDED_TO_GROUP />
          <CONTRACTOR>
            <ADDRESS_CONTRACTOR>
              <OFFICIALNAME>Uusi yhteystieto</OFFICIALNAME>
              <NATIONALID>8768333-3</NATIONALID>
              <TOWN>asdf</TOWN>
              <COUNTRY VALUE="FI" />
              <E_MAIL>asdf@fdsa.fd</E_MAIL>
              <n2016:NUTS CODE="FI" xmlns:n2016="http://publications.europa.eu/resource/schema/ted/2016/nuts" />
            </ADDRESS_CONTRACTOR>
            <NO_SME />
          </CONTRACTOR>
        </CONTRACTORS>
        <VALUES>
          <VAL_ESTIMATED_TOTAL CURRENCY="EUR">123321.0</VAL_ESTIMATED_TOTAL>
          <VAL_RANGE_TOTAL CURRENCY="EUR">
            <LOW>123123.0</LOW>
            <HIGH>132456.0</HIGH>
          </VAL_RANGE_TOTAL>
        </VALUES>
      </AWARDED_CONTRACT>
    </AWARD_CONTRACT>
    <COMPLEMENTARY_INFO>
      <ADDRESS_REVIEW_BODY>
        <OFFICIALNAME>Markkinaoikeus</OFFICIALNAME>
        <ADDRESS>Radanrakentajantie 5</ADDRESS>
        <TOWN>Helsinki</TOWN>
        <POSTAL_CODE>00520</POSTAL_CODE>
        <COUNTRY VALUE="FI" />
        <PHONE>+358 295643300</PHONE>
        <E_MAIL>noreply@cloudia.fi</E_MAIL>
        <URL>http://www.oikeus.fi/markkinaoikeus</URL>
      </ADDRESS_REVIEW_BODY>
      <DATE_DISPATCH_NOTICE>2020-04-07</DATE_DISPATCH_NOTICE>
    </COMPLEMENTARY_INFO>
  </F15_2014>
</FORM_SECTION>
`
**Additional context**
Issue seems to be in production also.

**Comment by tuomastolvanen** [comment]
We are invrestigating the issue, there is possibly a special case issue in combination ProcurementCetegory.License and MainActivityUtilities for F15.

**Comment by tuomastolvanen** [comment]
We have identied the issue related to documentation and TED handling of this special case.

In order to use scenario ContractingEntity and Concession directive, following fields mut be set: 

`notice.Project.ProcurementCategory = ProcurementCategory.Lisence;
 notice.Project.ContractType = ContractType.Services;
 notice.Project.Organisation.ContractingType = ContractingType.ContractingEntity;
 notice.Project.Organisation.MainActivityUtilities = MainActivityUtilities.MainactivWater;`

Note that also ContractingType is needed to be set to ContractingEntity in this scenario.

**Comment by tuomastolvanen** [comment]
This update has now been deployed to staging and production
