### ISSUE TITLE
F15 passes POST validation but TED rejects

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#33]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
F15 with "Other justification for the award of the concession without prior publication of a concession notice in the Official Journal of the European Union" passes POST validation but TED rejects with "D_ACCORDANCE_ARTICLE empty: Annex D-1: Justification: mandatory." Does not seem right as this should be Annex D4.

**To Reproduce**
PUT https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/devel_1075
[put_payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4444251/put_payload.txt)

**Expected behavior**

**API response**
Hilma receives notice just fine
[request_response.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4444270/request_response.txt)

**Additional context**
But TED rejects with error.

{
  "noticeNumber": "2020-029320",
  "creationDate": "2020-04-07T12:23:10.7436674",
  "modificationDate": "2020-04-07T12:25:02.9765626",
  "hilmaStatus": 1,
  "etsIdentifier": "devel_1075",
  "organisationId": "1088146-2",
  "projectId": 23558,
  "noticeId": 29320,
  "tedStatus": 5,
  "tedSubmissionId": "20200407-000070",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": [{
      "name": "R900",
      "valid": false,
      "severity": "ERROR",
      "message": "D_ACCORDANCE_ARTICLE empty: Annex D-1: Justification: mandatory."
    }]
  }]
}

**Comment by rantati7** [comment]
This is in code review and we aim to publish the fix today (8.4.2020) when there are less users

**Comment by tuomastolvanen** [comment]
The fix has been deployed to production
