### ISSUE TITLE
F2 corrigendum rejected by TED because name change done apparently by Hilma

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#34]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
TED rejected F2 corrigendum because 1.1) Nimi ja osoitteet (Virallinen nimi) does not match original notice. In JSON name is not changed so this must have happened in Hilma.

**To Reproduce**
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_14934?parentId=etsidfixed_14522&projectId=31862

[Corrigendum_payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4474432/Corrigendum_payload.txt)

**Expected behavior**
Corrigendum to be published without error or TED rejection

**API response**
Hilma sent notice to TED so Hilma API response is not that interesting. TED rejection seen through hilma API on the other hand is again quite uninformative:
{
  "noticeNumber": "2020-043791",
  "creationDate": "2020-04-09T13:37:29.0149584",
  "modificationDate": "2020-04-10T09:00:02.354267",
  "hilmaStatus": 1,
  "etsIdentifier": "production_14934",
  "organisationId": "2296962-1",
  "projectId": 31862,
  "noticeId": 43791,
  "tedStatus": 7,
  "tedSubmissionId": "20200409-006260",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": []
  }]
}

**Additional context**
TED apparently has sent a message about this notice:
Tiedot, joita haluatte muuttaa osiossa 1.1) "Nimi ja osoitteet" ("Virallinen nimi" -kohta) eivät täysin vastaa TED-sivustolla (viite 2020/S 070-167026) julkaistun alkuperäisen hankintailmoituksen tietoja. "Oikaistava tieto" -kohdassa esitettävän muutettavan tekstin on vastattava täsmällisesti alkuperäisessä ilmoituksessa julkaistua tekstiä. Olkaa hyvä ja huomioikaa myös, että virallisten nimien muuttaminen ei automaattisesti muuta osoite- ja yhteystietja. Olkaa hyvä ja toimittakaa korjausilmoitus, jossa oikaistavat tiedot on ilmoitettu oikein. Kiitos.

**Comment by tuomastolvanen** [comment]
We have investigated the issue and the conclusion is that the contracting authority list (coPurchasers) have changes from the original notice. This will result in changes in F14. The contracting authority information cannot be changed with F14 notice.

**Comment by cloudia-jt** [comment]
Here is the original payload. If you compare with corrigendum payload you can see that we did not change contracting authority.
[original_payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4479502/original_payload.txt)

Note the goal of this corrigendum is not to change contracting authority.

**Comment by tuomastolvanen** [comment]
We will investigate this further

**Comment by tuomastolvanen** [comment]
There was issue in Hilma change factory in matching coPurchaser changes based on businessId. In this case the changes were detected in the copurchaser list as they have same business id. The logic has been updated to match correct changes and the fix is being published later today. This corrigendum has been rejected by ted and new corrigendum should be submitted.

**Comment by tuomastolvanen** [comment]
The fix has been published to production. The corrigendum can be now sent.
