### ISSUE TITLE
Providing ParentId when OjsNumber is provided

### ISSUE THREAD

**Issue by jaandk** [Hankintailmoitukset/hilma-api#35]
When trying to publish a F03 i get the following error message:
PreviousNoticeOjsNumber=2019/S 217-532954 was provided and its parent was found, but parentId was not set. Please provide the parentId

My question is, if the the parrent is found then why do I need to provide a parrentid ?

**Comment by henrihietala** [comment]
Currently the parent notice validation requires to provide the `parentid` also. We will take a deeper look into this and see if we can remove this requirement for F03 since it's not really necessary.

**Comment by tuomastolvanen** [comment]
You can use the original notice number as parentId

**Comment by jaandk** [comment]
I'm trying to use the original notice number but i get this error when trying:
No such notice Id=2019-023102?projectId=0 found in current Ets API subscription.
Can you help ?
