### ISSUE TITLE
LOT_MAX_NUMBER set as 0 even thought it has value in JSON

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#36]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
POST/PUT results in BadRequest with error "The notice cannot be published to TED: The 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception:LOT_MAX_NUMBER' element is invalid - The value '0' is invalid according to its datatype 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception:nb_lot' - The MinExclusive constraint failed. ,"
JSON has
"QuantityOfLots": 8,
"LotsSubmittedFor": 4,
"LotsSubmittedForQuantity": 8,

**To Reproduce**
https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/test_202004171022
[lotmax_payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4491572/lotmax_payload.txt)

**Expected behavior**
LOT_MAX_NUMBER should be 8 thus having not error complaining about value being 0

**API response**
400 Bad Request

The notice did not pass validation. Following sections contains errors: 
The 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception:LOT_MAX_NUMBER' element is invalid - The value '0' is invalid according to its datatype 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception:nb_lot' - The MinExclusive constraint failed.

[lotmax_response.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4491583/lotmax_response.txt)

**Additional context**

**Comment by henrihietala** [comment]
The bug has been found and will be fixed and deployed today

**Comment by henrihietala** [comment]
This is fixed in the staging environment now

**Comment by henrihietala** [comment]
Deployed to production
