### ISSUE TITLE
Documentation missing ContractAwarded for national direct purchase

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#37]
National direct purchase documentation for awardcontract object does not include ContractAwarded selection. If left out of json notice does not display results section content.

![image](https://user-images.githubusercontent.com/60221724/79562919-78f4d000-80b4-11ea-984c-34d4e3cc7959.png)

**Comment by henrihietala** [comment]
National Direct Award notice expects to have objectDescriptions.awardContract.contractAwarded with value of 1 (AwardedContract). It is not a visible selection in Hilma and therefore it's not showing up in online documentation either.
I added a mention about this to instructions for notice type 9905.

![image](https://user-images.githubusercontent.com/6830448/79566903-fb34c280-80bb-11ea-8aa7-2aa4830a3978.png)

**Comment by cloudia-jt** [comment]
I don't like this solution as documentation doesn't really describe the structure of valid json. Also in time there will be list of "ATTENTION" info that has to be taken notice while reading the actual documentation.
