### ISSUE TITLE
Read api does not find notice with Ojs number

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#38]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Notice can be found with etsidentifier via write api but it can not be found with read api. Looks similar to [Issue #21 ](https://github.com/Hankintailmoitukset/hilma-api/issues/21)

**To Reproduce**
POST https://api.hankintailmoitukset.fi/avp/notices/docs/search HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json
Ocp-Apim-Subscription-Key: foobar

Body in attachment: [read request body.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4539949/read.request.body.txt)

**Expected behavior**
As notice can be seen from write api it should be seen as well from read api.

**API response**
Pragma: no-cache
request-id: 0f151588-d893-4aea-be04-dbfa7112e4c3
elapsed-time: 300
OData-Version: 4.0
Preference-Applied: odata.include-annotations="*"
Strict-Transport-Security: max-age=15724800; includeSubDomains
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-cache
Date: Mon, 27 Apr 2020 13:26:40 GMT
Content-Length: 134
Content-Type: application/json; odata.metadata=minimal
Expires: -1

{
  "@odata.context": "https://hns-hilma-prod-search.search.windows.net/indexes('notices')/$metadata#docs(*)",
  "@odata.count": 0,
  "value": []
}

**Additional context**
GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_14235?includeNotice=False HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key: foobar

Response status

200 OK
Response latency
383 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Mon, 27 Apr 2020 13:26:10 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-043339",
  "noticeOjsNumber": "2020/S 069-163463",
  "creationDate": "2020-04-03T13:31:53.608186",
  "modificationDate": "2020-04-07T07:00:14.2508973",
  "hilmaStatus": 2,
  "hilmaPublicationDate": "2020-04-05T13:35:08.3593724",
  "etsIdentifier": "etsidfixed_14235",
  "organisationId": "1567535-0",
  "projectId": 33984,
  "noticeId": 43339,
  "tedPublicationInfo": {
    "documentNumber": "2020/S 069-163463",
    "links": {
      "fi": "http://ted.europa.eu/udl?uri=TED:NOTICE:163463-2020:TEXT:FI:HTML"
    },
    "orderNumberInSeries": "069",
    "publicationDate": "2020-04-07T07:00:00",
    "publicationRequestedDate": "2020-04-03T13:31:54"
  },
  "tedStatus": 4,
  "tedSubmissionId": "20200403-006284",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": []
  }]
}

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
For some reason the noticeOjsNumber wasn't populated into the index. I rebuilt the index and now the query works.
I will try to find a reason for why the number is not always populated to the index.

**Comment by tuomastolvanen** [comment]
Fix for the search OJS issue has been released to production. This issues was occuring for notices that were published in Hilma based on the 48h rule before they were assigned OJS number by TED.
