### ISSUE TITLE
F20 Internal server error

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#4]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
TED POST validation results in internal server error

**To Reproduce**
```
POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_2991 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foo
```
- sample request payload
check email

**Expected behavior**
Validation result

**API response**
Response status

500 Internal Server Error
Response latency
664 ms
Response content

```
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Mon, 27 Jan 2020 10:10:14 GMT
Content-Length: 0
```

**Comment by cloudia-jt** [comment]
Made modifications to payload to include new Modifications section.

Still same Internal server error.

Request:
POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/test_202001281656 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foo

Response:
Response status

500 Internal Server Error
Response latency
233 ms
Response content

Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Tue, 28 Jan 2020 14:58:01 GMT
Content-Length: 0

Check email for payload.

**Comment by tuomastolvanen** [comment]
Thank you for the update. 

We identified and issue in the F20 api handling that caused the further 500. The fix will be deployed shortly into production today. 

There was another issue with the message. ContractNumber was null and it caused TED xml to fail since it is a required field. Adding contract number will pass the validation.

**Comment by tuomastolvanen** [comment]
The issue in the api is now published. The notice can be published by fixing the missin contract number
