### ISSUE TITLE
Notice waiting to be published unexpectedly long time

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#40]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Notice was sent 6.5.2020 to hilma and it has been waiting to be published since. At the moment notice has not been published.

**To Reproduce**
GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_17916?includeNotice=False HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key fooo

**Expected behavior**
Expect notice to be published or rejected.

**API response**
Response status

200 OK
Response latency
201 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
X-Azure-Ref: 0MSm5XgAAAAA6QSAWLlDeSo1I+upvL4psQlJVMzBFREdFMDQxNQAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=
Cache-Control: no-store, no-cache
Date: Mon, 11 May 2020 10:30:09 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-045861",
  "creationDate": "2020-05-06T11:14:49.1121595",
  "modificationDate": "2020-05-11T09:05:01.0454545",
  "hilmaStatus": 4,
  "etsIdentifier": "production_17916",
  "organisationId": "0201256-6",
  "projectId": 34191,
  "noticeId": 45861,
  "tedStatus": 3,
  "tedSubmissionId": "20200511-005593",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": []
  }]

**Additional context**
According to our logs notice was sent to hilma 6.5.2020 and it's been waiting to be published in hilma eversince

**Comment by tuomastolvanen** [comment]
We have investigated the issue and the undelying issue was that the ted submit failed originally beacuse of a network issue. The notice has now been submitted to TED.
