### ISSUE TITLE
Corrigendum notice cannot be made to notice that has expired TendersOrRequestsToParticipateDueDateTime

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#41]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Apparently corrigendum can not be published after original notice TendersOrRequestsToParticipateDueDateTime has been reached, even though it has been extended by earlier corrigendum.

**To Reproduce**
POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/test_202005111601?parentId=production_15227&projectId=34583 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foo

[Corrigendum_payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4609780/Corrigendum_payload.txt)

**Expected behavior**
There should not be problem as TendersOrRequestsToParticipateDueDateTime has been extended with previous corrigendum.

**API response**
Response status
400 Bad Request
Response latency
928 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
X-Azure-Ref: 0Pk25XgAAAACABInjalaFT6YdcdSo6ypyQlJVMzBFREdFMDQyMAAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=
Cache-Control: no-store, no-cache
Date: Mon, 11 May 2020 13:03:58 GMT
Content-Type: text/plain; charset=utf-8

The notice did not pass validation. Following sections contains errors: 
Corrigendum notice cannot be made to notice that has expired TendersOrRequestsToParticipateDueDateTime: ExpirationTime: 05/10/2020 12:00:00, Current local time: 05/11/2020 16:03:58

**Additional context**

**Comment by tuomastolvanen** [comment]
This is most likely a bug in the due date validation. Investigating.

**Comment by tuomastolvanen** [comment]
We have identified the issue and the fix will be deployed later today

**Comment by tuomastolvanen** [comment]
Closing after deployed

**Comment by cloudia-jt** [comment]
Any idea time of deployment?

**Comment by tuomastolvanen** [comment]
We are depoying the fix now. I will confirm when the change has been published.

**Comment by tuomastolvanen** [comment]
Fix is deployed
