### ISSUE TITLE
Notice waiting to be published in Hilma but seems to be published in TED

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#43]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Hilma status stuck in waiting to be published but ted status states published.

**To Reproduce**
GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_18410?includeNotice=False HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key: foo

**Expected behavior**
If published in TED, Hilma publishing expected.

**API response**
Response status

200 OK
Response latency
254 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
X-Azure-Ref: 0fD2+XgAAAAAtPSih36ekR5ENLddhCN6vQlJVMzBFREdFMDQwNgAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=
Cache-Control: no-store, no-cache
Date: Fri, 15 May 2020 06:58:04 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-046171",
  "noticeOjsNumber": "2020/S 092-219753",
  "creationDate": "2020-05-11T07:09:28.9273216",
  "modificationDate": "2020-05-12T07:00:13.2761976",
  "hilmaStatus": 4,
  "etsIdentifier": "production_18410",
  "organisationId": "0679480-9",
  "projectId": 34039,
  "noticeId": 46171,
  "tedPublicationInfo": {
    "documentNumber": "2020/S 092-219753",
    "links": {
      "fi": "http://ted.europa.eu/udl?uri=TED:NOTICE:219753-2020:TEXT:FI:HTML"
    },
    "orderNumberInSeries": "092",
    "publicationDate": "2020-05-12T07:00:00",
    "publicationRequestedDate": "2020-05-11T07:09:32"
  },
  "tedStatus": 4,
  "tedSubmissionId": "20200511-005225",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": []
  }]
}

**Additional context**

**Comment by jannef** [comment]
The notice is now published.

Notice was stuck on similar error state as in issue #39. This time the specific error that caused the publication to fail in Hilma was the corrigendum published past the due date. The issue has since been fixed.

**Comment by jannef** [comment]
Closing the issue as there is no new activity, and the problem seems fixed.
