### ISSUE TITLE
F18 PayableDocuments causes TED validation fail

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#45]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
For F18 hilma api documentation does not include PayableDocuments at all. If PayableDocuments is ommitted it seems to default to false value which causes NO_PAYABLE_DOCUMENTS element in TED XML resulting in error The element 'ADMINISTRATIVE_INFORMATION_CONTRACT_AWARD_DEFENCE' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception' has invalid child element 'CONDITIONS_OBTAINING_SPECIFICATIONS' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception'. If PayableDocuments is set as true and XML does not contain invalid element.

**To Reproduce**
POST https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/test_202005191546 HTTP/1.1
Host: hns-hilma-staging-apim.azure-api.net
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foobar

[fails validation.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4650546/fails.validation.txt)

**Expected behavior**
As api documentation does not include PayableDocuments for F18 it should not have any affect for for TED XML generated.

**API response**

400 Bad Request
Response latency
1408 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:60071d4c-cdb6-420c-9fe4-6e9d212ede47
X-Azure-Ref: 0VtXDXgAAAABn2t8rP/KgRaYtEqyQ/1qLQlJVMzBFREdFMDQyMAA1ODEwZWQ3Ni0xODAzLTQ2ZDMtYWM2Yy0wZWRjZDgyNDFmY2E=
Cache-Control: no-store, no-cache
Date: Tue, 19 May 2020 12:47:18 GMT
Content-Type: text/plain; charset=utf-8

The notice did not pass validation. Following sections contains errors: 
The element 'ADMINISTRATIVE_INFORMATION_CONTRACT_AWARD_DEFENCE' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception' has invalid child element 'CONDITIONS_OBTAINING_SPECIFICATIONS' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception'.

TED message formed:
[invalid xml.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4650595/invalid.xml.txt)

**Additional context**
Sample payload of PayableDocuments having value true. [passes validation.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4650570/passes.validation.txt)

[generated valid xml.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4650582/generated.valid.xml.txt)

Valid one des not have 
          <CONDITIONS_OBTAINING_SPECIFICATIONS>
            <NO_PAYABLE_DOCUMENTS />
          </CONDITIONS_OBTAINING_SPECIFICATIONS>

**Comment by jannef** [comment]
This issue is now being investigated.

**Comment by jannef** [comment]
Our current XML-factory implementation seems to wrongly assume that ProcedureType.ProctypeCompDialogue should cause the element in question to be outputted. In reality, the element should only be present on F17 notice (not F16 and F18).

The offending code:
``` csharp
_notice.ProcedureInformation.ProcedureType == ProcedureType.ProctypeCompDialogue
  ? Element("CONDITIONS_OBTAINING_SPECIFICATIONS",
      DateElement("TIME_LIMIT", defenceAdministrativeInformation.TimeLimitForReceipt),
      !defenceAdministrativeInformation.PayableDocuments
          ? Element("NO_PAYABLE_DOCUMENTS")
          : Element("PAYABLE_DOCUMENTS",
              ElementWithAttribute("DOCUMENT_COST", "CURRENCY", defenceAdministrativeInformation.DocumentPrice?.Currency, defenceAdministrativeInformation.DocumentPrice?.Value),
              PElement("DOCUMENT_METHOD_OF_PAYMENT", defenceAdministrativeInformation.PaymentTermsAndMethods)))
  : null,
```

Fix has been implemented and is pending validation and deployment.
