### ISSUE TITLE
Corrigendum is rejected in TED's manual verification because section II.2.2 has not changed

### ISSUE THREAD

**Issue by esaiko** [Hankintailmoitukset/hilma-api#47]
We were instructed by the Hilma support  to make a ticket of this issue in this channel (Hilma API forum)

**Describe the bug**

User has successfully published contract notice. 
One of the criteria has an attachment which should be filled by the contenders. 
This attachment is changed after publishing the contract notice. 
User tries to publish corrigendum by filling section VII.2 (explaining what changed in the attachments). 
This is not accepted in TED's manual validation with an explanation saying that section II.2.2 has not changed.

**To Reproduce**
Create contract notice. Try to publish a change (corrigendum) without changing section II.2.2.

**Expected behavior**
If changes to section II.2.2 are required in corrigendum, then Hilma API should also require such changes and reject the notice (corrigendum).

**Comment by arinurkkala** [comment]
II.2.2 refers to additional CPV code.

Could you provide some more info on the notice, so I can find the problem? Like the ets identifier

**Comment by esaiko** [comment]
etsIdentifier: 747, TED submissionId: 20200602-005044

This is all the info we have received:

![8999A632-12A4-4DA1-A8A3-62ACB065319E](https://user-images.githubusercontent.com/4319273/84025401-29d06a80-a994-11ea-8567-fccbd4c38649.png)

**Comment by arinurkkala** [comment]
Fix is pending deployment. I will update to production after 16:00

**Comment by arinurkkala** [comment]
Production updated
