### ISSUE TITLE
notice is waiting for sending to ted

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#48]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
notice is sended to hilma 5.6. and it is still "SendingToTed" state (1)

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**
from write api get

"hilmaStatus": 4,
"etsIdentifier": "production_21503",
"tedStatus": 1,

**Comment by tuomastolvanen** [comment]
Investigating

**Comment by tuomastolvanen** [comment]
The notice has now been published to TED. Based on the logs the publish failed originally because of a network issue.
