### ISSUE TITLE
CPV codes show up as undefined when submitting a form

### ISSUE THREAD

**Issue by jaandk** [Hankintailmoitukset/hilma-api#5]
**Describe the bug**
When submitting any form ant not setting the text on a cpv code it shows up as undefined.

**To Reproduce**
Subbmit a form where only the code og the cpv code is set and not the name. This will result in this error.

**Expected behavior**
I expect to only set the CPV code and the the system will show the correct cpv name. When looking at the documentation it also states that the code should be defined. 

**API response**

**Additional context**
Please se https://testhilma.hansel.fi/fi/public/procurement/106012/notice/111977/overview as an example.

**Comment by jannef** [comment]
Please submit the CPV-code name, in the language of the notice, in addition to the code. The migration example supplied does not do this.

Documentation will be updated to reflect this more clearly.
