### ISSUE TITLE
Corrigendums get rejected in TED with information already corrected with previous

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#50]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Corrigendum notice passes POST/PUT validations but TED rejects with error message like "korjatut versiot on jo julkaistu edellisellä korjausilmoituksella". Apparently there are multiple notices in state like this.

**To Reproduce**
PUT https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_22491?parentId=production_20786&projectId=35577 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foobar

[Corrigendum_payload.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4786147/Corrigendum_payload.txt)

**Expected behavior**
Expect Hilma to make valid TED corrigendum.

**API response**
[Corrigendum_response.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4786167/Corrigendum_response.txt)

**Additional context**
Status message about rejection.
[Corrigendum_status.txt](https://github.com/Hankintailmoitukset/hilma-api/files/4786191/Corrigendum_status.txt)

**Comment by cloudia-jt** [comment]
Any news about this issue?

For example there is this notice with ets identifier production_21093 that were tried to correct with production_22591. There was change of date. Now in TED time limit for receipt of tenders or requests to participate is the one with corrigendum, but Hilma shows the original (incorrect) date as corrigendum was rejected.

Is there a fix for this? Even a temporary one?

**Comment by jannef** [comment]
Fyi to everyone, this issue is should be resolved. TED is no longer manually modifying the original notices.
