### ISSUE TITLE
Publication canceled but notice still waiting for publishing

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#51]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
This morning (2020-06-18) 8:39 publishing of notice with ets identifier production_23063 was canceled. Notice is still in waiting to be published state.

**To Reproduce**
GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_23063?includeNotice=False HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key: fooo

**Expected behavior**
Status change is expected to reflect not publishing as it does in test environment.

**API response**
Response status
200 OK
Response latency
62 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
X-Azure-Ref: 0eyfrXgAAAAD9akhmaUufQK+OJAJyKKisQU1TRURHRTA1MDkAMDExMzA0YmYtYzMxNi00NWEwLWFlYTgtMWFkMDBjMmU2YjI3
Cache-Control: no-store, no-cache
Date: Thu, 18 Jun 2020 08:36:11 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-049379",
  "creationDate": "2020-06-18T05:21:26.8370732",
  "modificationDate": "2020-06-18T05:25:08.1169427",
  "hilmaStatus": 4,
  "etsIdentifier": "production_23063",
  "organisationId": "2859365-3",
  "projectId": 30206,
  "noticeId": 49379,
  "tedStatus": 3,
  "tedSubmissionId": "20200618-005055",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": []
  }]
}

**Additional context**

**Comment by JuhaHonkaranta** [comment]
Investigating

**Comment by JuhaHonkaranta** [comment]
This notice appears as canceled both in Hilma and TED.

**Comment by cloudia-jt** [comment]
Any problems with cancellation? Or any reason for so slow state change?

**Comment by JuhaHonkaranta** [comment]
TED needs to review and approve the cancellation before we can update the notice.
