### ISSUE TITLE
Hilma gives "InternalServerError"

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#52]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**

**To Reproduce**
We send notice by email

**Expected behavior**

**API response**
InternalServerError response headers: X-Azure-Ref: 0Md75XgAAAACJK6MoT52jTqYkqXM1sGebQU1TRURHRTA1MTcAMDExMzA0YmYtYzMxNi00NWEwLWFlYTgtMWFkMDBjMmU2YjI3 Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5 Date: Mon, 29 Jun 2020 12:27:28 GMT

**Additional context**

**Comment by JuhaHonkaranta** [comment]
Investigating

**Comment by JuhaHonkaranta** [comment]
You should try again. This was possibly fixed yesterday after the error happened.

**Comment by anttiremes** [comment]
BadRequest The notice cannot be published to 
TED: The element 'TYPE_OF_PROCEDURE_DETAIL_FOR_CONTRACT_NOTICE_DEFENCE' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception' has invalid child element 
'PT_COMPETITIVE_NEGOTIATION' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception'. 
List of possible elements expected: 'PT_RESTRICTED, PT_ACCELERATED_RESTRICTED_CHOICE, PT_NEGOTIATED_CHOICE, F17_PT_ACCELERATED_NEGOTIATED, PT_COMPETITIVE_DIALOGUE' in namespace 
'http://publications.europa.eu/resource/schema/ted/R2.0.8/reception'. ,

**Comment by jannef** [comment]
Closing the issue, as the original issue has been resolved.

The error message given seems to be working as expected, suggesting given ProcedureType is not legal in the R2.0.8 schema.
