### ISSUE TITLE
couldn't publish notice, because of national identifier is not valid

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#54]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
couldn't publish notice:  BadRequest Given national Identifier 15675350-0 is not valid!.

**To Reproduce**

"NationalRegistrationNumber": "15675350-0",

**Expected behavior**
Notice should be published

**API response**
BadRequest response headers: Pragma: no-cache  Transfer-Encoding: chunked  Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5  X-Azure-Ref: 0quf+XgAAAAD6u/pDkCjyS4rkmLitgrfWQlJVMzBFREdFMDQxNwAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=  Cache-Control: no-store, no-cache  Date: Fri, 03 Jul 2020 08:09:14 GMT  

**Additional context**
https://www.finder.fi/Maakuntien+liitot+ja+kuntayhtym%C3%A4t/HUS-kuntayhtym%C3%A4/Helsinki/yhteystiedot/136906?phone=show

**Comment by jannef** [comment]
The national identifier is not valid and does not match the one in the link. Please double check.
