### ISSUE TITLE
InternalServerError when trying to publish a notice

### ISSUE THREAD

**Issue by tonikasurinen** [Hankintailmoitukset/hilma-api#55]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Hilma responds with "InternalServerError" when trying to publish a notice.

**To Reproduce**
Notice was sent to https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_24556?parentId=production_23832&projectId=38679

**API response**
InternalServerError response headers: X-Azure-Ref: 0hiUDXwAAAAAaC9FFReXaRLOMYpsKJKPNQU1TRURHRTA1MDkAMDExMzA0YmYtYzMxNi00NWEwLWFlYTgtMWFkMDBjMmU2YjI3  Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5  Date: Mon, 06 Jul 2020 13:22:15 GMT

**Comment by jannef** [comment]
You are creating a corrigendum. Please supply the parentId. The API incorrectly does not reject the request to make corrigendum without supplied parent Id.

Please try updating the notice while adding correct parentId.

**Comment by tonikasurinen** [comment]
After investigating this further it turned out that a corrigendum had already been successfully sent to Hilma. I don't have header information for that request, but the corrigendum was sent from us at 2020-07-06 13:52:16.210 (or 2020-07-06 10:52:16.210 GMT). 

Corrigendum was sent to endpoint 
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_24556?parentId=production_23832&projectId=38679

So there was a parentId production_23832 that references the original notice.

It seems that the corrigendum was rejected by TED, because if I search for it in Hilma API (https://hns-hilma-prod-apim.portal.azure-api.net/docs/services/ets-write-api/operations/Get/console) using etsIdentifier production_24556, I get this:

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
X-Azure-Ref: 00p0FXwAAAACC160NYS8IQoFWh8dP5P8lQU1TRURHRTA1MTcAMDExMzA0YmYtYzMxNi00NWEwLWFlYTgtMWFkMDBjMmU2YjI3
Cache-Control: no-store, no-cache
Date: Wed, 08 Jul 2020 10:20:02 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2020-050616",
  "creationDate": "2020-07-06T10:52:17.0748435",
  "modificationDate": "2020-07-08T06:17:45.1431174",
  "hilmaStatus": 1,
  "etsIdentifier": "production_24556",
  "organisationId": "0952029-9",
  "projectId": 38679,
  "noticeId": 50616,
  "tedStatus": 5,
  "tedSubmissionId": "20200706-005820",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": false,
      "severity": "CRITICAL",
      "message": "XML file is valid against XSD.",
      "details": "Line:97;Column:46;Error:cvc-complex-type.2.4.b: The content of element 'SIMAP_ESENDER_NOTICE_REFERENCE' is not complete. One of '{NO_DOC_EXT}' is expected."
    }]
  }, null]
}

So the corrigendum had a parentId when it was sent to Hilma, but it seems that there has been some problem with NO_DOC_EXT referencing the original notice when it was sent from Hilma to TED.

That InternalServerError that I mentioned in the original message was probably due to user editing the same notice again and trying to send it to Hilma, even though the previous corrigendum wasn't yet published in Hilma. We probably need to prevent this in our system.

So can you check why TED has rejected the corrigendum?

**Comment by jannef** [comment]
Ongoing bug has been identified regarding this issue. Potential fix has been implemented and is pending validation and deployment. Please do not attempt to retry until further notice.

**Comment by jannef** [comment]
The fix has been deployed. Notice should be good to retry now: previously created notices should pass without manual intervention.

**Comment by tonikasurinen** [comment]
Again we got InternalServerError.

InternalServerError response headers: X-Azure-Ref: 0EMkGXwAAAACHwvJY64eNQ5oM4v/gTQjXQlJVMzBFREdFMDQxOAAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=  Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5  Date: Thu, 09 Jul 2020 07:36:48 GMT

RequestUri: 
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_24556?parentId=production_23832&projectId=38679

The url has parentId production_23832 that is the id of the original notice. production_24556 is the corrigendum that has been sent to TED and rejected there because of invalid SIMAP_ESENDER_NOTICE_REFERENCE. We are trying to publish this again.

So should we be able to publish this corrigendum using production_24556 as the id and production_23832 (the original notice) as the parent, or should we create a new corrigendum that would have new id and production_24556 as its parentId?

**Comment by jannef** [comment]
I'll be looking into this. My thinking was to attempt to resend the original corrigendum, instead of sending a new one.

**Comment by jannef** [comment]
ParentId must point to the latest published version of that notice.

The way you are trying to send the rejected notice again should work in general. The cause of the error is still to be found. As a workaround, you can try to abandon the rejected corrigendum and just create a new one targeting the original notice as the parent.

Regardless of the outcome, I try to figure out why the request is failing.

**Comment by jannef** [comment]
The second issue affecting the notice was identified and fixed, and is pending deployment.

**Comment by jannef** [comment]
Fix has been deployed. Please feel free to retry, unless you already have abandoned the rejected corrigendum and created a new one.

**Comment by tonikasurinen** [comment]
We sent the rejected corrigendum again and this time it was successfully sent to Hilma, so the issue that caused the InternalServerError seems to be fixed now.
