### ISSUE TITLE
Hilma does not accept migrated notice's code as parentId

### ISSUE THREAD

**Issue by esaiko** [Hankintailmoitukset/hilma-api#56]
**Describe the bug**
User tries to publish contract award notice (type 300). The contract notice was published 2019 and is (or should be) migrated to the new Hilma.
How ever, Hilma does not accept the contract award notice and gives error message:

No such notice Id=2019-021762 found in current Ets API subscription.

**To Reproduce**

POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/786?projectId
=18422&parentId=2019-021762
Content-Length: 55614
Ocp-Apim-Subscription-Key: ed4xxx

400 Bad Request
Cache-Control: no-store,no-cache
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
X-Azure-Ref: 0vYIVXcxxxx
Date: Mon, 20 Jul 2020 11:40:45 GMT
Connection: close

No such notice Id=2019-021762 found in current Ets API subscription.

**Expected behavior**
Hilma should accept the migrated notice's code as the parentId.

I checked our logs and it looks like there was a similar problem earlier in January 23rd (2020-01-23). It was fixed by some data update in Hilma (by Janne and/or Tuomas).

**Comment by rantati7** [comment]
The correct parent-ID is that of TED F02 (contract notice) when the customer is making a contract award notice. In this notitice there are three corrigendum notices and numbner 2019-021462 refers to the last corrigendum notice.
https://www.hankintailmoitukset.fi/fi/public/procurement/18422/notice/27615/overview

In this case the correct number should be parent-ID 2019-019567 - and TED number 2019/S 186-452034

If this won't work please come back to us!

**Comment by tuomastolvanen** [comment]
The correct way of sending this notice is to omit parentId and projectId from the request and use the PreviousNoticeOjsNumber for notice. This will create the notice with new project id for the requesting ETS user. We have identified that there is currently incorrect user check in this scenation when calling without parent id and we will release a patch for the issue as soon as possible.  We will update here when the patch has been released.

**Comment by tuomastolvanen** [comment]
Correction to previous post. The correct solutions is still to omit parentId and projectId from the request and use the PreviousNoticeOjsNumber for notice. There should not be any issue with sending the notice using this method. 

The ETS Userid must match the parentId then the parentId is used and parentId should always be used in other cases when the original notice is sent with the same ETS user.
