### ISSUE TITLE
Change in contract notice not registered as corrigendum

### ISSUE THREAD

**Issue by brianshdk** [Hankintailmoitukset/hilma-api#57]
Hi,

We have sent this notice to you (https://www.hankintailmoitukset.fi/en/public/procurement/38540/notice/50258/overview), but for some reason the change is not registered as a "Corrigendum" like in this one (https://www.hankintailmoitukset.fi/en/public/procurement/37842/notice/51667/overview).

Is it something we have done wrong or why has this happened?

Thanks,
Brian
Mercell

**Comment by arinurkkala** [comment]
Hi,

"isCorrigendum": false

This flag should be set to true for corrigendum notices.

Br,
Ari

**Comment by brianshdk** [comment]
Hi,

Thanks, we found the error!

Brian
