### ISSUE TITLE
Getting request is blocked in response

### ISSUE THREAD

**Issue by ThomasSiigNoergaard** [Hankintailmoitukset/hilma-api#58]
When trying to import tenders from the staging-environment we're getting the below error. Any ideas?

GET https://hns-hilma-staging-apim.azure-api.net/avp-notice/api/avp/notices/29688 HTTP/1.1
Host: hns-hilma-staging-apim.azure-api.net
Ocp-Apim-Subscription-Key: ••••••••••••••••••••••••••••••••

Response status
406 Not Acceptable

<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span></span></div></div></body></html>

**Comment by arinurkkala** [comment]
Investigating

**Comment by arinurkkala** [comment]
The same problem appears on test, but does not appear on dev. The code regarding AVP has not changed and backend isn't logging much, so there is probably something strange with Azure. We will continue investigating..

**Comment by arinurkkala** [comment]
Found an issue in the backend and this is now fixed.
