### ISSUE TITLE
Cannot get notice data

### ISSUE THREAD

**Issue by nimo-7** [Hankintailmoitukset/hilma-api#59]
We have a customer who is trying to publish a notice, based on another notice. When we try to get the validation status of the base notice, we get a reply that it doesn't exist. 
The base notice has an amendment. This is the notice we cannot find. It has status "Waiting for TED publication" in your system. 

If we use your API to get the notice validation before the amendment, we receive the validation result. It works with other notices. 

Shouldn't we be able to get a validation repsonse

**To Reproduce**
- Using Postman we call GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/[etsid]?includeNotice=True

- HTTP headers:
We send the Ocp-Apim-Subscription-Key
Cache-Control: no-store,no-cache
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8

**Expected behavior**

``` json
We would like to receive the validation status of the notice:
{
    "noticeNumber": "2020-053288",
    "creationDate": "",
    "modificationDate": "",
    "hilmaStatus": 2,
    "hilmaPublicationDate": "",
    "etsIdentifier": "",
    "organisationId": "",
    "projectId": ,
    "noticeId": ,
    "tedStatus": 3,
    "tedSubmissionId": "",
    "tedValidationReport": [
        {
            "type": "TECH",
            "items": [
                {
                    "name": "T001",
                    "valid": true,
                    "message": "XML file is valid against XSD."
                },
                {
                    "name": "T002",
                    "valid": true,
                    "message": "Metadata could be retrieved from the XML file."
                },
                {
                    "name": "T003",
                    "valid": true,
                    "message": "Unique key is active."
                }
            ]
        },
        {
            "type": "VALIDATION_RULES",
            "items": []
        }
    ]
}
```

**API response**
No such Notice etsId=[etsid]
Cache-Control: no-store,no-cache
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: text/plain; charset=utf-8
Request-Context
X-Azure-Ref
Date: Tue, 08 Sep 2020 13:34:56 GMT

**Additional context**
One of my colleagues has, as far as I know, asked for the amendment to be deleted from your system

**Comment by jannef** [comment]
I've been unable to reproduce or validate this problem. Can you provide further details? Using given notice number 2020-053288, I can see successful GETs (9/8/2020, 1:34:43.408 PM, 9/7/2020, 12:20:56.498 PM etc, times UTC).

2020-053288 refers to notice titled 'Ravintolapalvelut', is this the correct notice?

Please provide the actual EtsIdentifier you are using to make the request.

**Comment by jannef** [comment]
The issue was discovered, the client was trying to fetch with incorrect Etsidentifier.
