### ISSUE TITLE
Contract award notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#62]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Contract award notice - defence and security (TED F18) did not show information about ContractAwardsDefence

https://www.hankintailmoitukset.fi/fi/public/procurement/25884/notice/51903/defence-details

I send json by email

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by JuhaHonkaranta** [comment]
What exactly is missing and where? At least in Hilma public view I can see it.
![image](https://user-images.githubusercontent.com/26892713/94004396-4ce92380-fda5-11ea-8347-278f9d770973.png)

**Comment by JuhaHonkaranta** [comment]
Seems like the lot title missing is missing because the property in the JSON is typoed. It should be `LotTitle`
