### ISSUE TITLE
Error when publishing notice 

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#66]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
First time response was "ServiceUnavaible" and later "BadRequest Notice being updated is not a draft or publishedThenRejected. State=Published."

Notice is published in hilma despite of error message

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
2020-10-13 15:35:54.040

ServiceUnavailable response headers: X-Azure-Ref: 0CZ+FXwAAAAC47wmsb5PvSbl1urTAjfcfQlJVMzBFREdFMDQxMwAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=  Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5  Cache-Control: no-store  Date: Tue, 13 Oct 2020 12:35:53 GMT  

**Additional context**

**Comment by tuomastolvanen** [comment]
We have invertigated this and it appears to be single unexpected network issue
