### ISSUE TITLE
Award contract no previous ojs error

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#7]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
TED rejected award notice with validation error "PT_OPEN and missing NOTICE_NUMBER_OJ: S4-02-01: Please fill in the previous publication date which is mandatory according to the given procedure." Even though json has PreviousNoticeOjsNumber defined.

**To Reproduce**
GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_3407?includeNotice=False
response shows:
Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Wed, 29 Jan 2020 13:18:29 GMT
Content-Type: application/json; charset=utf-8
``` json
{
  "noticeNumber": "2020-037029",
  "creationDate": "2020-01-23T12:58:10.5397014",
  "modificationDate": "2020-01-23T13:00:06.3472165",
  "hilmaStatus": 1,
  "etsIdentifier": "production_3407",
  "organisationId": "2160307-0",
  "projectId": 29750,
  "noticeId": 37029,
  "tedStatus": 5,
  "tedSubmissionId": "20200123-006000",
  "tedValidationReport": [{
    "type": "TECH",
    "items": [{
      "name": "T001",
      "valid": true,
      "message": "XML file is valid against XSD."
    }, {
      "name": "T002",
      "valid": true,
      "message": "Metadata could be retrieved from the XML file."
    }, {
      "name": "T003",
      "valid": true,
      "message": "Unique key is active."
    }]
  }, {
    "type": "VALIDATION_RULES",
    "items": [{
      "name": "R560",
      "valid": false,
      "severity": "ERROR",
      "message": "PT_OPEN and missing NOTICE_NUMBER_OJ: S4-02-01: Please fill in the previous publication date which is mandatory according to the given procedure."
    }]
  }]
}
```
Previous notice payload that was sent: check email.

**Expected behavior**
NOTICE_NUMBER_OJ should not be empty when PreviousNoticeOjsNumber defined in json.

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by arinurkkala** [comment]
Issue has been resolved
