### ISSUE TITLE
Ted can't publish corrigendum notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#71]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Original:
production_31810

corrigendum:
production_35307

Ted reports
  "message": "Duplicate NO_DOC_EXT, a notice with the same identifier has already been received.",
      "details": "At least one notice with the same noDocExt '2020-057241' has already been submitted. 10 first existing notice(s) submission id is/are '20201030-005235'"
    

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by Zamm** [comment]
Corrigendum was already published in ted, for some reason the publishing request was send twice to ted.
Second was declined, its now fixed and the notice is also published in hilma.

**Comment by anttiremes** [comment]
Same issue:

production_33098
production_29026

**Comment by anttiremes** [comment]
production_19544

message": "Duplicate NO_DOC_EXT, a notice with the same identifier has already been received.",
      "details": "At least one notice with the same noDocExt '2020-057725' has already been submitted. 10 first existing notice(s) submission id is/are '20201105-006278'"
    
Notice is published in ted

**Comment by anttiremes** [comment]
production_33098 is published in ted:

https://ted.europa.eu/udl?uri=TED:NOTICE:484631-2020:TEXT:FI:HTML&src=0

but not in hankintailmoitukset.fi

**Comment by jannef** [comment]
For this notice, TED has integrated the corrigendum into the original notice and rejected the corrigendum. I try to find out what the proper fix is.

**Comment by jannef** [comment]
The business side takes the lead on this one.
