### ISSUE TITLE
Problems publish contract award notice-utilities

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#74]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
seems value cannot be 0.0

Finaltotalvalue.value= 0.0

"FinalTotalValue": {
						"Type": 1,
						"Value": 0.0,
						"Currency": "EUR",
						"DisagreeToBePublished": true

**To Reproduce**
etsidfixed_38928

**API response**
The notice cannot be published to TED: The 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception:VAL_TOTAL' element is invalid - The value '0.00' is invalid according to its datatype 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception:val' - The MinExclusive constraint failed. , The 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception:VAL_TOTAL' element is invalid - The value '0.00' is invalid according to its datatype 

**Additional context**
<xs:simpleType name="cost">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
			<xs:pattern value="\d{1,13}(\.\d{1,2})?"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="val">
		<xs:simpleContent>
			<xs:extension base="cost">
				<xs:attribute name="CURRENCY" type="currencies" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

**Comment by JuhaHonkaranta** [comment]
The minimum value is exclusive so the value needs to be greater than 0.

**Comment by arinurkkala** [comment]
Issue discussed at weekly meeting and agreed to be closed.
