### ISSUE TITLE
Cancel notice did not work

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#75]
**Describe the bug**
7.12 we send cancel publication. Api response was "Publication stopped" but hilma published notice. 
Search can find canceled notice, but it cannot be opened. Yesteday notice was open.

Orginally version says (vanha versio) and no button for "osallistu"
https://www.hankintailmoitukset.fi/fi/public/procurement/43331/notice/57682/contact

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
Publication stopped

**Additional context**
canceled notice ets: production_39507
old version: production_33499

**Comment by arinurkkala** [comment]
Investigating

**Comment by tuomastolvanen** [comment]
Original version status is updated to active
