### ISSUE TITLE
ted rejects old hilma notice's corrigendum notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#76]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
orginal notice is published to old hilma and now ted rejects corrigendum notice

etsidentifier: production_33855

"TendersMustBeValidOption": 0,

 IV.2.6), eivät vastaa TED-sivustolla (viite 2018/S 178-403556) julkaistun alkuperäisen ilmoituksen tietoja.

"section": "IV.2.6",
      "label": "Kuukausina",
      "oldText": ["0"],
      "newText": [""]

**Comment by arinurkkala** [comment]
It refers to the field
TendersMustBeValidForMonths
which is 0 in the old notice and in the corrigendum notice it wasn't sent.

I have created a hotfix for this (checks if TendersMustBeValidOption is set) and it will take some time before it is deployed into production.

**Comment by tuomastolvanen** [comment]
This fix will be deployed to production on monday

**Comment by arinurkkala** [comment]
Prod updated
