### ISSUE TITLE
Error publishing Kansallinen suorahankinta 9905 notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#77]
**Describe the bug**
BadRequest There was unexpected value in the model. 
This is an error with the ETS API, please report this issue. Hint to self diagnose the violating field: 
Organisations.Information.Email. RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_40654

Seems that api requires Email address

**Comment by tuomastolvanen** [comment]
In the current notice specification in the api, the Email for Organisation is required for all notices.

**Comment by anttiremes** [comment]
I cant find what fields is required as mandatory in api document. In UI-side there is no email-address for organisation.

**Comment by tuomastolvanen** [comment]
![image](https://user-images.githubusercontent.com/57632209/103208329-0b6a9600-4909-11eb-9648-54e86ab3c51d.png)

Here is the UI for contracting authority contact information on form. In Hilma the email is required.

**Comment by tuomastolvanen** [comment]
There might be inaccuracy on the api documents for this field
