### ISSUE TITLE
Hilma changes previousNoticeOjsNumber from notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#79]
Orginal notice is migrated from old hilma

"noticeNumber": "2021-062252", 

sended noticeojsnumber:
"PreviousNoticeOjsNumber": "2018/S 186-421050", 

from ets write api
"previousNoticeOjsNumber": "2019/S 249-619380",

https://ted.europa.eu/udl?uri=TED:NOTICE:421050-2018:TEXT:FI:HTML&tabId=0

https://ted.europa.eu/udl?uri=TED:NOTICE:619380-2019:TEXT:FI:HTML&tabId=0

also seems problematic changes about lots information

**Comment by Zamm** [comment]
Old corrigendum notices didn't have previousojsNumber, this is now fixed and the new corrigendum notice can resend to ted.

EtsIdentifier:
production_42935
Notice number:
2021-062252

**Comment by anttiremes** [comment]
TED rejects notice because it has wrong changes.

Example

section": "II.2.1",
      "label": "Osa nro",
      "lotNumber": "3",
      "oldText": [null],
      "newText": ["3"]

**Comment by jannef** [comment]
What is the context? Please create a new issue with clearly defined context, based on which the issue can be investigated.

**Comment by anttiremes** [comment]
it releates to same notice:

EtsIdentifier:
production_42935
