### ISSUE TITLE
EU-suorahankinta, julkaisu ei onnistu

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#8]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**

**To Reproduce**
 RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_3728            

Check email

**Expected behavior**

**API response**
28.1.2020 8:03:15

BadRequest The notice cannot be published to TED: The element 'PROCEDURE' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'CONTRACT_COVERED_GPA' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. List of possible elements expected: 'DIRECTIVE_2014_23_EU, DIRECTIVE_2014_24_EU, DIRECTIVE_2014_25_EU, DIRECTIVE_2009_81_EC' in       
...
 <PROCEDURE> <CONTRACT_COVERED_GPA /> </PROCEDURE> 

**Additional context**

**Comment by jannef** [comment]
There seems to be some data missing from the issue template. Also, I do not have access to any json payload in my email. Please provide a version with all the sensitive data stripped in the issue to ensure the issued handler has access to all the data.

The error suggests an element is missing from the produced XML. Without seeing the payload, my guess is that ProcurementCategory is not within allowed range for the specific notice type.

**Comment by jannef** [comment]
I have looked into the logs regarding this issue. The request was malformed and missing mandatory fields.

The error message in question is raised by missing data in  dto.Project. Please refer to documentation (type EtsProjectContract) and provide all required fields and retry the request.

**Comment by jannef** [comment]
Please note, that ProcurementCategory should be supplied to avoid any confusion. API makes some effort to deduce missing ProcurementCategory, when possible, but this is prone to failure and defaulting to Undefined when not immediately evident from the context.

**Comment by jannef** [comment]
Also please note, that ProcedureType should be within allowed range. Currently online documentation is having challenges reflecting the multiple ProcurementCategories in F15.

The allowed ProcedureTypes are as follows:

- D1-D3: [9, 15]
- D4: [9, 16]

Former of the two enum values signifying the procurement is outside the scope of the directive. Latter is the procedure given in case structured justifications in the annex is required to be supplied.

**Comment by henrihietala** [comment]
FYI issue for fixing the online documentation reagrding this matter has been created to Hilma dev backlog
