### ISSUE TITLE
TED rejects notice because wrong changes 

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#81]
etsidentifier =  'production_42935'

![MicrosoftTeams-image](https://user-images.githubusercontent.com/60220798/105848488-b42f1280-5fe7-11eb-88a1-7b3f937254fe.png)

**Comment by jannef** [comment]
It appears that the migration of the corrigendum notices from old hilma has failed and some data has been lost. This needs to be manually corrected.

Is it possible that you send the previous version of this notice to koulutus environment, from where we could copy the data? 

Another option is, that you provide a list of actual expected changes to be published with this corrigendum - including old and new both.
