### ISSUE TITLE
Ted rejects corrigendum notice 

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#84]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
TED rejects notice "production_45599" because VI.6 "väärä ilmoituksen viite"

![index](https://user-images.githubusercontent.com/60220798/107742523-d9c25880-6d17-11eb-80d7-9eab4bba0636.png)

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by tuomastolvanen** [comment]
Fix for this issue was relesed on Friday 12.2.2021
