### ISSUE TITLE
Publishing notice gives TED error

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#85]
Both notices has lots of nuts codes

Etsidentifier: production_46171 and production_46209

**Describe the bug**
BadRequest The notice cannot be published to TED: The element 'OBJECT_DESCR' 
in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has invalid child element 'NUTS' 
in namespace 'http://publications.europa.eu/resource/schema/ted/2016/nuts'. 
List of possible elements expected: 'MAIN_SITE, SHORT_DESCR' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'.

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
2021-02-16 08:24:44.027

2021-02-16 08:22:24.240

**Additional context**

**Comment by tuomastolvanen** [comment]
The error indicates that the description is missing for the lot object.

**Comment by anttiremes** [comment]
Both notices have "DescrProcurement" in json

**Comment by tuomastolvanen** [comment]
This error occures because TED Schema limits NUTS code selection to 20 items `<xs:element ref="n2016:NUTS" maxOccurs="20"/>`
