### ISSUE TITLE
500 Internal server error when validating

### ISSUE THREAD

**Issue by jaandk** [Hankintailmoitukset/hilma-api#87]
**Describe the bug**
I get 500 internal server error when trying to validate a form.

**To Reproduce**
POST attached form
[ValidationForm.txt](https://github.com/Hankintailmoitukset/hilma-api/files/5995699/ValidationForm.txt)
 to https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/123456

**Expected behavior**
200 or validation errors

**API response**
500 internal server error

**Comment by jannef** [comment]
An issue has been identified validating corrigendum notices with the POST endpoint. I've created an issue to our backlog. There is no workaround.

**Comment by tuomastolvanen** [comment]
We are testing a fix for the issue and will release a fix later today.

**Comment by tuomastolvanen** [comment]
Hotfix for this issue has been released to production.
