### ISSUE TITLE
Hilma gives InternalServerError when publishing notice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#88]
etsidentifier: production_48078

And API portal gives 404 Not Found for that notice

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by tuomastolvanen** [comment]
This notice was rejected by the api because the previous notice had not been published in Ted at the time of submission. Error message explaining the situation should have been returned. If this was not the case, we will look into the error responses.

**Comment by tuomastolvanen** [comment]
It is possible that this error was not handled in the api correctly causing 500 response. Investigating.

**Comment by tuomastolvanen** [comment]
The immediate issue with response 500 was fixed yesterday in a patch. Currently the scenario will return 400 BadRequest -response with error message. We are changing the response for this issue to be 409 Conflict response instead and will publish the fix later this week.
