### ISSUE TITLE
Award notice can not be published as original notice migrated from old hilma with wrong language

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#9]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
While trying to POST award notice for notice that was originally published in old hilma new hilma complains about change in language.

**To Reproduce**
POST https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_4460?parentId=2019-021705&projectId=19467 HTTP/1.1
Host: api.hankintailmoitukset.fi
Content-Type: application/json-patch+json
Ocp-Apim-Subscription-Key: foo
- sample request payload
check email

**Expected behavior**
Notice is expected to be published without error.

**API response**
Response status

400 Bad Request
Response latency
233 ms
Response content

Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Fri, 31 Jan 2020 08:26:27 GMT
Content-Type: text/plain; charset=utf-8

Notice language cannot change. Use parent language EN instead.

**Additional context**
It seems that original notice migrated from old hilma has suddenly changed languages.
Original notice was sent with     <F02_2014 LG="FI" CATEGORY="ORIGINAL" FORM="F02">

but

GET https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/2019-021705?includeNotice=true HTTP/1.1
Host: api.hankintailmoitukset.fi
Ocp-Apim-Subscription-Key: foo

Response content:
Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Fri, 31 Jan 2020 08:38:26 GMT
Content-Type: application/json; charset=utf-8

{
  "noticeNumber": "2019-021705",
  "noticeOjsNumber": "2019/S 207-503926",
  "creationDate": "2019-12-31T15:36:58.9174444",
  "modificationDate": "2020-01-08T23:29:18.2438879",
  "hilmaStatus": 2,
  "hilmaPublicationDate": "2019-10-24T16:45:04",
  "etsIdentifier": "2019-021705",
  "organisationId": "0245491-1",
  "projectId": 19467,
  "noticeId": 28907,
  "tedPublicationInfo": {
    "documentNumber": "2019/S 207-503926",
    "links": {},
    "orderNumberInSeries": "2019/S 207-503926",
    "publicationDate": "2019-10-25T10:00:00",
    "publicationRequestedDate": "2019-10-22T00:00:00"
  },
  "tedStatus": 4,
  "tedSubmissionId": "20191023-005104",
  "notice": {
    "id": 28907,
    "totalValue": {
      "type": 0
    },
    "legalBasis": "32014L0024",
    "communicationInformation": {
      "procurementDocumentsAvailable": 1,
      "procurementDocumentsUrl": "https://hanki.tarjouspalvelu.fi/hanki",
      "additionalInformation": 1,
      "additionalInformationAddress": {
        "validationState": 0
      },
      "otherAddressForProcurementDocuments": {
        "validationState": 0
      },
      "sendTendersOption": 1,
      "electronicAddressToSendTenders": "https://hanki.tarjouspalvelu.fi/hanki?id=241546&tpk=0152af0b-962a-4f75-a42e-36bbe5e54568",
      "addressToSendTenders": {
        "validationState": 0
      },
      "electronicCommunicationRequiresSpecialTools": false,
      "documentsEntirelyInHilma": false,
      "specsAndAdditionalDocuments": 0,
      "validationState": 2
    },
    "complementaryInformation": {
      "isRecurringProcurement": false,
      "estimatedTimingForFurtherNoticePublish": [],
      "electronicOrderingUsed": true,
      "electronicInvoicingUsed": true,
      "electronicPaymentUsed": true,
      "additionalInformation": [],
      "validationState": 2
    },
    "conditionsInformation": {
      "professionalSuitabilityRequirements": [],
      "economicCriteriaToParticipate": false,
      "economicCriteriaDescription": [],
      "economicRequiredStandards": [],
      "technicalCriteriaToParticipate": false,
      "technicalCriteriaDescription": [],
      "technicalRequiredStandards": [],
      "rulesForParticipation": [],
      "restrictedToShelteredWorkshop": false,
      "restrictedToShelteredProgram": false,
      "reservedOrganisationServiceMission": false,
      "depositsRequired": [],
      "financingConditions": [],
      "legalFormTaken": [],
      "ciriteriaForTheSelectionOfParticipants": [],
      "executionOfServiceIsReservedForProfession": false,
      "referenceToRelevantLawRegulationOrProvision": [],
      "participationIsReservedForProfession": false,
      "contractPerformanceConditions": [],
      "obligationToIndicateNamesAndProfessionalQualifications": false,
      "validationState": 2
    },
    "conditionsInformationNational": {
      "validationState": 0,
      "reservedForShelteredWorkshopOrProgram": false
    },
    "contactPerson": {
      "name": "Juhani Kauppo",
      "email": "juhani.kauppo@stat.fi"
    },
    "estimatedValue": {
      "type": 0,
      "value": 600000.00,
      "currency": "EUR",
      "disagreeToBePublished": false
    },
    "links": [],
    "lotsInfo": {
      "divisionLots": false,
      "lotsSubmittedFor": 0,
      "lotsSubmittedForQuantity": 0,
      "lotsMaxAwarded": false,
      "lotsMaxAwardedQuantity": 0,
      "lotCombinationPossible": false,
      "validationState": 2
    },
    "mainCpvCode": {
      "code": "48200000",
      "name": "Networking, Internet and intranet software package",
      "vocCodes": []
    },
    "objectDescriptions": [{
      "mainCpvCode": {},
      "additionalCpvCodes": [{
        "code": "48000000",
        "name": "Software package and information systems",
        "vocCodes": []
      }, {
        "code": "32426000",
        "name": "Network publishing system",
        "vocCodes": []
      }, {
        "code": "72000000",
        "name": "",
        "vocCodes": []
      }, {
        "code": "72212200",
        "name": "",
        "vocCodes": []
      }],
      "nutsCodes": ["FI"],
      "mainsiteplaceWorksDelivery": [],
      "descrProcurement": ["Please see Annex 1 \"Description of the subject matter\" for a more detailed description. Requirements for the system are described in the Annex 2 \"Requirement Specification\". "],
      "disagreeAwardCriteriaToBePublished": false,
      "awardCriteria": {
        "criterionTypes": 8,
        "qualityCriteria": [],
        "costCriteria": [],
        "priceCriterion": {},
        "criterion": [],
        "criteriaStatedInProcurementDocuments": false
      },
      "estimatedValue": {
        "type": 0
      },
      "timeFrame": {
        "type": 2,
        "days": 0,
        "months": 24,
        "canBeRenewed": true,
        "renewalDescription": ["The contract period starts from the signing of the contract as a 24 months fixed term. Thereafter, the contract period remains in force until further notice as described in the draft contract."]
      },
      "candidateNumberRestrictions": {
        "envisagedNumber": 0,
        "envisagedMinimumNumber": 0,
        "envisagedMaximumNumber": 0,
        "objectiveCriteriaForChoosing": [],
        "selected": 0
      },
      "optionsAndVariants": {
        "variantsWillBeAccepted": false,
        "partialOffersWillBeAccepted": false,
        "options": true,
        "optionsDescription": ["Statistics Finland aims to develop the solution further during the contract period. Therefore, Statistics Finland may purchase add-ons, components and related consulting work. For example, they may be services for monitoring the availability and performance of a website, services for quality assurance of a website, or separate connectors for MS Dynamics and Sharepoint. \n\nA preliminary list of these components and services is included in Annex 1, \"Description of Subject Matter\", section 2.5.\n\nThe Contract Authority estimates that value of these components and additional work is less than 30 000 eur / year during the contract period. The estimated value of the procurement (section II.1.5) includes the estimate."],
        "optionType": 0
      },
      "tendersMustBePresentedAsElectronicCatalogs": false,
      "euFunds": {
        "procurementRelatedToEuProgram": false
      },
      "additionalInformation": ["Hansel Ltd acts as a consultant in the project.\n\nThe value of the contract announced in II.1.5) is an estimate of the total value of the contract for four-years period. The aforementioned estimate does not bind the Contract Authority."],
      "awardContract": {
        "contractAwarded": 0,
        "noAwardedContract": {
          "failureReason": 0,
          "originalNoticeSentVia": 0
        },
        "awardedContract": {
          "numberOfTenders": {
            "disagreeTenderInformationToBePublished": false,
            "total": 0
          },
          "disagreeContractorInformationToBePublished": false,
          "contractors": [],
          "initialEstimatedValueOfContract": {},
          "finalTotalValue": {
            "type": 0
          },
          "likelyToBeSubcontracted": false,
          "valueOfSubcontract": {},
          "notPublicFields": {
            "communityOrigin": false,
            "nonCommunityOrigin": false,
            "awardedToTendererWithVariant": false,
            "abnormallyLowTendersExcluded": false
          }
        }
      },
      "validationState": 2
    }],
    "organisation": {
      "information": {
        "officialName": "Tilastokeskus",
        "nationalRegistrationNumber": "0245491-1",
        "nutsCodes": ["FI"],
        "postalAddress": {
          "streetAddress": "Työpajankatu 13",
          "postalCode": "00580",
          "town": "Helsinki",
          "country": "FI"
        },
        "email": "juhani.kauppo@stat.fi",
        "contactPerson": "Juhani Kauppo",
        "mainUrl": "http://www.tilastokeskus.fi",
        "validationState": 2
      },
      "contractingAuthorityType": 2,
      "contractingType": 1,
      "mainActivity": 1,
      "mainActivityUtilities": 0
    },
    "noticeOjsNumber": "2019/S 207-503926",
    "previousNoticeOjsNumber": "2019/S 098-236698",
    "project": {
      "id": 0,
      "contractType": 1,
      "referenceNumber": "TK-32-1475-19",
      "title": "Content Management System",
      "procurementCategory": 1,
      "jointProcurement": false,
      "procurementLaw": [],
      "centralPurchasing": false,
      "coPurchasers": [],
      "defenceWorks": 0,
      "defenceSupplies": 0,
      "agricultureWorks": 0
    },
    "shortDescription": ["Statistics Finland is purchasing a license to a Content Management system, and support for implementation project of the system, as described in this Request to Tender and its annexes.\n\nThe content management system is intended to support separate web applications developed by Statistics Finland, to create a new version of the Statistics FInland's web portal. The new content management system should enable Statistics Finland to create, manage and disseminate modular and reusable content to various channels.\n\nThe content management system is intended to manage several hundreds of thousands of content items with around one hundred different types. The typical content includes text, images and videos, but also both static and dynamic graphs, tables and maps that can be used both independently or as a set, for example as a part of an article. The content is expected to be delivered annually to around 6 million end users.\n\nThe system is intended to be in use for several years."],
    "type": 200,
    "tenderingInformation": {
      "tendersOrRequestsToParticipateDueDateTime": "2019-11-25T10:00:00",
      "languages": ["EN"],
      "tendersMustBeValidOption": 2,
      "tendersMustBeValidForMonths": 6,
      "tenderOpeningConditions": {
        "openingDateAndTime": "2019-11-25T10:15:00",
        "place": [],
        "informationAboutAuthorisedPersons": ["The opening of the tenders is not public."]
      },
      "estimatedExecutionTimeFrame": {
        "type": 3,
        "canBeRenewed": false
      },
      "validationState": 2
    },
    **"language": "EN",**
    "procedureInformation": {
      "procedureType": 1,
      "acceleratedProcedure": false,
      "justificationForAcceleratedProcedure": [],
      "contestType": 0,
      "frameworkAgreement": {
        "includesFrameworkAgreement": false,
        "includesConclusionOfFrameworkAgreement": false,
        "frameworkAgreementType": 0,
        "frameworkEnvisagedType": 0,
        "includesDynamicPurchasingSystem": false,
        "dynamicPurchasingSystemInvolvesAdditionalPurchasers": false,
        "justificationForDurationOverFourYears": [],
        "dynamicPurchasingSystemWasTerminated": false,
        "estimatedTotalValue": {
          "type": 0
        },
        "duration": {
          "type": 0,
          "canBeRenewed": false
        }
      },
      "reductionRecourseToReduceNumberOfSolutions": false,
      "reserveRightToAwardWithoutNegotiations": false,
      "electronicAuctionWillBeUsed": false,
      "procurementGovernedByGPA": true,
      "disagreeCriteriaForEvaluationOfProjectsPublish": false,
      "mainFeaturesAward": [],
      "validationState": 2
    },
    "proceduresForReview": {
      "reviewBody": {
        "officialName": "Markkinaoikeus",
        "postalAddress": {
          "streetAddress": "Radanrakentajantie 5",
          "postalCode": "00520",
          "town": "Helsinki",
          "country": "FI"
        },
        "telephoneNumber": "+358 295643300",
        "email": "markkinaoikeus@oikeus.fi",
        "mainUrl": "http://www.oikeus.fi/markkinaoikeus",
        "validationState": 0
      },
      "reviewProcedure": [],
      "validationState": 2
    },
    "isCorrigendum": false,
    "isCancelled": false,
    "corrigendumAdditionalInformation": []
  }
}

**Comment by tuomastolvanen** [comment]
In old hilma then notice is marked as languge = "EN"
<HILMA_METADATA>    <NO_DOC_EXT>2019-021705</NO_DOC_EXT>  </HILMA_METADATA>  <FORM_SECTION>    <F02_2014 LG="EN" CATEGORY="ORIGINAL" FORM="F02">

We will investigate the issue further. One option is to send the following notice also with language EN

**Comment by tuomastolvanen** [comment]
The notice language is also in TED English and the content is also written in english. There seems to be no error in the language. The following notice should also be in english. The Api error seems to be correct as is suggest to use english as language. 

https://ted.europa.eu/udl?uri=TED:NOTICE:503926-2019:DATA:EN:HTML&tabId=3

**Comment by tuomastolvanen** [comment]
Resolution is to use: Language: "EN" as suggested
