### ISSUE TITLE
Publishing F01 (101) notice gives ted error

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#90]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
BadRequest The notice cannot be published to TED: The element 'AC' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' has incomplete content. 
List of possible elements expected: 'AC_QUALITY, AC_COST, AC_PRICE' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception'. , TED message formed: 

**To Reproduce**
example AC criterions.

<AC>           
<AC_QUALITY>             
<AC_CRITERION>Hinta</AC_CRITERION>             
<AC_WEIGHTING>100</AC_WEIGHTING>           
</AC_QUALITY>         
</AC>    

<AC>           
<AC_PROCUREMENT_DOC />         
</AC>  

<AC>           
<AC_QUALITY>             
<AC_CRITERION>Hinta</AC_CRITERION>             
<AC_WEIGHTING>100</AC_WEIGHTING>           
</AC_QUALITY>           
<AC_PRICE>             
<AC_WEIGHTING>100</AC_WEIGHTING>          
</AC_PRICE>         
</AC>

**Expected behavior**

**Additional context**
time 2021-02-26 11:52:35.970
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_46131

**Comment by AlexEngblom** [comment]
Hi,

unfortunately we couldn't find any trace from our system logs for request to publish notice 'production_46131'.
Could you kindly provide us the award criterion section of your request payload?

**Comment by AlexEngblom** [comment]
Here is what I found after investigating the payload:

The lot number 1 has defined award criterion of types "Price and quality criteria mixed" (5). 
The price criterion provided is invalid. 
You need to provide valid value in AwardCriteria for PriceCriterion Weighting.

Please let us know, if this solved your issue or if any further issues arise.

Br,
Alex

**Comment by jannef** [comment]
Closed due inactivity.
