### ISSUE TITLE
National Notice Validation - Experimental validation

### ISSUE THREAD

**Issue by jaandk** [Hankintailmoitukset/hilma-api#91]
According to the documentation the National Notice Validation will be rolled out in the near future, is there any date for this?
When enabling the Experimental validation we see some strange validation error when trying to validate TED tenders but shouldn't this only be for national tenders ? 
Should the Experimental validation be enabled or disabled for production ?

**Comment by jannef** [comment]
It should be disabled. It seems unlikely it will roll out any time soon.

**Comment by jannef** [comment]
I've looked into the experimental validation in the API. Opting in to the optional validation for unsupported notice types should do nothing. The supported notice types only include 
NationalContractNotice (9902) and NationalAgricultureContract (9903).

``` csharp
public bool ValidateProperties(EtsNoticeContract etsNotice, out string[] err)
{
    var noticeContract = etsNotice.ToNoticeContract();
    var validator = new NoticeConfigurationsFactory(noticeContract);

    if (validator.NoticeTypeSupported())
    {
        validator.Validate(out var errors);
        err = errors;
        return err.Length == 0;
    }

    err = new string[0];
    return true;
}
```

What are the strange validation errors you have recieved? Could you provide an example for investigation?

**Comment by jannef** [comment]
Closed due inactivity.
