### ISSUE TITLE
Hilma gives InternalServerError

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#92]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**

**To Reproduce**
 InternalServerError . RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_48475?parentId=2019-003549&projectId=13753

**Expected behavior**

**API response**
InternalServerError

**Additional context**

**Comment by JuhaHonkaranta** [comment]
Investigating

**Comment by JuhaHonkaranta** [comment]
This bug has been fixed. Estimated deployment date is Wednesday 10.3.2021.

**Comment by tuomastolvanen** [comment]
Deployed to production
