### ISSUE TITLE
Hilma gives InternalServerError

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#94]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
InternalServerError when publishing notice production_50543

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
InternalServerError . RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_50543
9.3.2021 15:52:08 ERROR TarjPyyn id 338446 julkaisu epäonnistui. InternalServerError response headers: X-Azure-Ref: 0iH1HYAAAAADdV0os8bxbRIym5d60KoRSQlJVMzBFREdFMDQyMAAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc= Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5 Date: Tue, 09 Mar 2021 13:52:08 GMT

**Additional context**

**Comment by JuhaHonkaranta** [comment]
Investigating

**Comment by JuhaHonkaranta** [comment]
This issue was caused by an invalid unicode control character (U+0002) in the notice data. Now the API will return a bad request with the offending control character if one is encountered.
This fix is currently testable in staging environment and awaiting deployment to production.

**Comment by JuhaHonkaranta** [comment]
The fix is now in production
