### ISSUE TITLE
Strange error code in api response

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#95]
**API response**
NotFound { "statusCode": 404, "message": "Resource not found" }. RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/?parentId=production_42310&projectId=43427
TarjPyyn id 328575 julkaisu epäonnistui. NotFound response headers: Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5  Date: Fri, 12 Mar 2021 08:38:51 GMT  

**Additional context**

**Comment by JuhaHonkaranta** [comment]
investigating

**Comment by JuhaHonkaranta** [comment]
The request URI is missing etsIdentifier after /notice/, hence 404 is returned.
