### ISSUE TITLE
Publishing notice gives TED error

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#96]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
Etsidentifier: production_51023

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
BadRequest The notice cannot be published to TED: The value of the 'VERSION' attribute does not equal its fixed value. , 
The element 'ADDRESS_CONTRACTING_BODY' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' 
has invalid child element 'NUTS' in namespace 'http://publications.europa.eu/resource/schema/ted/2016/nuts'. 
List of possible elements expected: 'FAX' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' 
as well as 'NUTS' in namespace 'http://publications.europa.eu/resource/schema/ted/2021/nuts'. , 
The element 'OBJECT_DESCR' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' 
has invalid child element 'NUTS' in namespace 'http://publications.europa.eu/resource/schema/ted/2016/nuts'. 
List of possible elements expected: 'TITLE, LOT_NO, CPV_ADDITIONAL' in namespace 'http://publications.europa.eu/resource/schema/ted/R2.0.9/reception' 
as well as 'NUTS' in namespace 'http://publications.europa.eu/resource/schema/ted/2021/nuts'. , 

**Additional context**

**Comment by JuhaHonkaranta** [comment]
investigating

**Comment by JuhaHonkaranta** [comment]
This issue has been fixed in staging environment and will be deployed to production later

**Comment by JuhaHonkaranta** [comment]
The fix is now in production
