### ISSUE TITLE
Notice attachment URL query parameter order changed in Hilma 2.2 update

### ISSUE THREAD

**Issue by brianshdk** [Hankintailmoitukset/hilma-api#97]
Hi,

We have realized that the URL to notice attachments have changed after the latest release. There has been added some `&sig=...` in the end. Example https://hnshilmaprodsa.blob.core.windows.net/attachments/7ed29300-2bf4-42c9-2770-08d8e4567ff5?sv=2020-04-08&se=2021-03-23T06%3A32%3A28Z&sr=b&sp=r&rscd=attachment%3B+filename%3D%22Tarjouspyynto_Kortesjarvi_10032021.pdf%22&sig=zj7XMeL9wu6IHFeqN2w8cqslIpW6MsUAE6HQnJ%2B8Q0c%3D

What does this new `&sig=` mean? I can't see it mentioned in the release notes and as an integrator we haven't been informed.

Thanks,
Brian

**Comment by jannef** [comment]
Notice attachment are stored in a blob storage. The access to this storage container and files in it are blocked by default. Access to the files is granted by delegated access only. This delegated access is implemented in the form of shared access signature signed by Hilma on publish. This shared acces token is the sig-parameter.

The sig-parameter is not new, but in the latest release we upgraded from deprecated azure storage SDK. The newer SDK signs the parameters in different order and sig is now at the end of the string and thus more apparent.

Please feel free to ask if any futher clarification is required.

**Comment by brianshdk** [comment]
Thanks, for the explanation, that makes sense.

However changing the URL, should be considered a breaking change and should be communicated to all integrators I think. We're extracting the filename from the URL with a regex and it suddenly broke after URL was changed.

**Comment by jannef** [comment]
I have pinned this issue for now and added a note to readme.md of this repository. Going forward, we try to be more mindful of these types of changes.

Recommended solution for anyone stumbling upon this same issue is to use url-parser to find 'rscd' -query parameter before applying regular expression to extract the filename.
