### ISSUE TITLE
Missing information in Hilma

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#98]
https://www.hankintailmoitukset.fi/fi/public/procurement/44899/notice/66736/contact

https://ted.europa.eu/udl?uri=TED:NOTICE:119650-2021:TEXT:FI:HTML

Etsidentifier: etsidfixed_50056

There is no contractaward information in Hilma

**Comment by tuomastolvanen** [comment]
We have identified a bug in the ui that caused the award not to be rendered. Hotfix is estimated to be published today.

**Comment by tuomastolvanen** [comment]
Testable in the staging environment (https://koulutus.hankintailmoitukset.fi)

**Comment by tuomastolvanen** [comment]
The issue was related to scenarion the "likelyToBeSubcontacted" was true and no estimated value was set. This is a valid usage scenario and therefore a bug.
