### ISSUE TITLE
 avp-read-api:  Search notices gives wrong answer if searched by noticeOjsNumber

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#99]
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
search
noticeOjsNumber: 2021/S 035-085284 order by datePublished desc

gives notice national notice:
https://www.hankintailmoitukset.fi/fi/public/procurement/49662/notice/67634/overview

**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by jannef** [comment]
The search does not seem to be written in OData query language.  You are actually supplying following seach terms for the search:

`'noticeOjsNumber:', '2021/S', '035-085284', 'order', 'by', 'datePublished', 'desc'`

Thus, random results with very low match score are returned (top result match score 0.012972945, roughly 1.2%). Please refer to documentation and use correct search syntax.

https://docs.microsoft.com/en-us/azure/search/search-query-odata-filter
https://docs.microsoft.com/en-us/azure/search/search-query-odata-orderby

Example of a correct usage of OData query language

`$filter=noticeOjsNumber eq '2021/S 035-085284'&$orderby=datePublished`

**Comment by Zamm** [comment]
OJS number search:
$filter=noticeOjsNumber eq '2021/S 057-144011' 
URL encoded: filter=noticeOjsNumber%20eq%20'2021%2FS%20057-144011'
